import { GameMode, TrackId, AIDifficulty } from '../types';

export type GameDifficulty = 'EASY' | 'NORMAL' | 'HARD' | 'EXPERT' | 'MASTER';

export interface ModeHazardProfile {
  type: string;
  name: string;
  densityMultiplier: number;
  speedMultiplier: number;
  damage: number;
  warningLeadTimeSec: number; // Seconds warning indicator appears before collision
  hasWarningAudio: boolean;
  color: string;
  avoidanceWindow: string; // e.g., 'EVADE LEFT OR DRIFT'
}

export interface ModeSpecificSettings {
  mode: GameMode;
  modeName: string;
  category: 'SINGULARITY' | 'CIRCUIT' | 'SURVIVAL' | 'ANOMALY' | 'SPECIAL';
  trackId: TrackId;
  trackLengthMeters: number;
  checkpointCount: number;
  junctionCount: number;
  routeCount: number;
  baseLaps: number;
  defaultDifficulty: GameDifficulty;
  aiDifficulty: AIDifficulty;
  timeLimitSec?: number;
  targetObjectiveCount?: number;
  recoveryAvailability: 'INSTANT' | 'FAST' | 'STANDARD' | 'RESTRICTED' | 'HARDCORE';
  hazards: ModeHazardProfile[];
  mechanicsDescription: string;
  difficultyScaling: {
    [key in GameDifficulty]: {
      aiSpeedMultiplier: number;
      hazardDensity: number;
      hazardSpeed: number;
      timeLimitModifier: number;
      damageMultiplier: number;
      safeZoneWidthMultiplier: number;
      description: string;
    };
  };
}

export const DIFFICULTY_PRESETS: {
  [key in GameDifficulty]: {
    label: string;
    badgeColor: string;
    aiDifficulty: AIDifficulty;
    speedBonus: number;
    hazardDensity: number;
    hazardSpeed: number;
    damageMult: number;
    description: string;
  };
} = {
  EASY: {
    label: 'EASY',
    badgeColor: 'border-emerald-500/50 bg-emerald-950/60 text-emerald-300',
    aiDifficulty: 'RECRUIT',
    speedBonus: -20,
    hazardDensity: 0.65,
    hazardSpeed: 0.75,
    damageMult: 0.6,
    description: 'Relaxed pacing, slower hazards, generous reaction windows and gentle AI rivals.',
  },
  NORMAL: {
    label: 'NORMAL',
    badgeColor: 'border-cyan-500/50 bg-cyan-950/60 text-cyan-300',
    aiDifficulty: 'STANDARD',
    speedBonus: 0,
    hazardDensity: 1.0,
    hazardSpeed: 1.0,
    damageMult: 1.0,
    description: 'Balanced challenge, standard hazard speeds, and competitive AI.',
  },
  HARD: {
    label: 'HARD',
    badgeColor: 'border-amber-500/50 bg-amber-950/60 text-amber-300',
    aiDifficulty: 'VETERAN',
    speedBonus: 25,
    hazardDensity: 1.35,
    hazardSpeed: 1.25,
    damageMult: 1.3,
    description: 'Accelerated rivals, higher hazard density, and strict timing windows.',
  },
  EXPERT: {
    label: 'EXPERT',
    badgeColor: 'border-rose-500/50 bg-rose-950/60 text-rose-300',
    aiDifficulty: 'ACE',
    speedBonus: 50,
    hazardDensity: 1.7,
    hazardSpeed: 1.5,
    damageMult: 1.65,
    description: 'High-speed hazard swarms, narrow safe lanes, and hyper-aggressive AI opponents.',
  },
  MASTER: {
    label: 'MASTER',
    badgeColor: 'border-purple-500/50 bg-purple-950/60 text-purple-300 shadow-[0_0_12px_rgba(168,85,247,0.4)]',
    aiDifficulty: 'ELITE',
    speedBonus: 80,
    hazardDensity: 2.1,
    hazardSpeed: 1.8,
    damageMult: 2.0,
    description: 'Unforgiving gauntlet. Supersonic hazards, extreme damage, and ruthless ace pilots.',
  },
};

const DEFAULT_DIFFICULTY_SCALING = {
  EASY: {
    aiSpeedMultiplier: 0.85,
    hazardDensity: 0.65,
    hazardSpeed: 0.75,
    timeLimitModifier: 1.3,
    damageMultiplier: 0.6,
    safeZoneWidthMultiplier: 1.3,
    description: 'Wider safe corridors and forgiving timing.',
  },
  NORMAL: {
    aiSpeedMultiplier: 1.0,
    hazardDensity: 1.0,
    hazardSpeed: 1.0,
    timeLimitModifier: 1.0,
    damageMultiplier: 1.0,
    safeZoneWidthMultiplier: 1.0,
    description: 'Standard baseline speed and hazards.',
  },
  HARD: {
    aiSpeedMultiplier: 1.15,
    hazardDensity: 1.35,
    hazardSpeed: 1.25,
    timeLimitModifier: 0.88,
    damageMultiplier: 1.3,
    safeZoneWidthMultiplier: 0.85,
    description: 'Narrower safe lanes and faster hazards.',
  },
  EXPERT: {
    aiSpeedMultiplier: 1.3,
    hazardDensity: 1.7,
    hazardSpeed: 1.5,
    timeLimitModifier: 0.78,
    damageMultiplier: 1.65,
    safeZoneWidthMultiplier: 0.7,
    description: 'Extremely dense hazard fields and rapid reactions required.',
  },
  MASTER: {
    aiSpeedMultiplier: 1.45,
    hazardDensity: 2.1,
    hazardSpeed: 1.8,
    timeLimitModifier: 0.68,
    damageMultiplier: 2.0,
    safeZoneWidthMultiplier: 0.55,
    description: 'Supersonic velocity, razor-thin clearances, zero tolerance for error.',
  },
};

export const ALL_MODES_CONFIG: Record<GameMode, ModeSpecificSettings> = {
  // 01 — SINGULARITY RUN
  SINGULARITY_RUN: {
    mode: 'SINGULARITY_RUN',
    modeName: '01 — SINGULARITY RUN',
    category: 'SINGULARITY',
    trackId: 'circuit_alpha',
    trackLengthMeters: 10400,
    checkpointCount: 26,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    timeLimitSec: 150,
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'Gravitational escape route around a supermassive black hole. Slingshot through gravity surge corridors.',
    hazards: [
      {
        type: 'GRAVITY_WELL',
        name: 'Event Horizon Grav-Shear',
        densityMultiplier: 1.2,
        speedMultiplier: 1.1,
        damage: 35,
        warningLeadTimeSec: 2.5,
        hasWarningAudio: true,
        color: '#d000ff',
        avoidanceWindow: 'BOOST OUTWARD // REVERSE CENTRIPETAL PULL',
      },
      {
        type: 'COLLAPSING_CORRIDOR',
        name: 'Shattered Planetary Plate',
        densityMultiplier: 1.0,
        speedMultiplier: 1.3,
        damage: 25,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#ff0055',
        avoidanceWindow: 'SLALOM LEFT OR JUMP UPPER APEX',
      },
      {
        type: 'GRAVITY_WAVE',
        name: 'Gravitational Pulse Ripple',
        densityMultiplier: 1.4,
        speedMultiplier: 1.4,
        damage: 20,
        warningLeadTimeSec: 1.8,
        hasWarningAudio: true,
        color: '#9d4edd',
        avoidanceWindow: 'TIME JUMP AT APEX TO RIDE THE CREST',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 02 — NEON CIRCUIT
  NEON_CIRCUIT: {
    mode: 'NEON_CIRCUIT',
    modeName: '02 — NEON CIRCUIT',
    category: 'CIRCUIT',
    trackId: 'neon_orbit',
    trackLengthMeters: 9800,
    checkpointCount: 24,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'High-speed 3-lane neon highway above floating megalopolis. High-G banking curves and traffic laser gates.',
    hazards: [
      {
        type: 'LASER_BARRIER',
        name: 'Pulsing Grid Barrier',
        densityMultiplier: 1.2,
        speedMultiplier: 1.0,
        damage: 20,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#00f0ff',
        avoidanceWindow: 'WEAVE THROUGH OPEN GAP LANE',
      },
      {
        type: 'TRAFFIC_POD',
        name: 'Automated Skyway Hauler',
        densityMultiplier: 1.0,
        speedMultiplier: 0.9,
        damage: 25,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: false,
        color: '#ffaa00',
        avoidanceWindow: 'OVERTAKE ON ADJACENT RUNWAY',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 03 — ASTEROID RUN
  ASTEROID_RUN: {
    mode: 'ASTEROID_RUN',
    modeName: '03 — ASTEROID RUN',
    category: 'CIRCUIT',
    trackId: 'asteroid_run',
    trackLengthMeters: 11200,
    checkpointCount: 28,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 3,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Deep mining trench across high-density asteroid belt. Use plasma destruction beam to disintegrate boulders.',
    hazards: [
      {
        type: 'ROTATING_ASTEROID',
        name: 'Iron Core Asteroid',
        densityMultiplier: 1.8,
        speedMultiplier: 1.1,
        damage: 30,
        warningLeadTimeSec: 2.5,
        hasWarningAudio: true,
        color: '#ff9900',
        avoidanceWindow: 'FIRE DESTRUCTION BEAM OR EVADE LATERAL',
      },
      {
        type: 'MINING_CRANE',
        name: 'Heavy Extraction Arm',
        densityMultiplier: 0.8,
        speedMultiplier: 1.2,
        damage: 40,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#ff3300',
        avoidanceWindow: 'DIVE UNDERNEATH CRANE SHAFT',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 04 — WORMHOLE EXPRESS
  WORMHOLE_EXPRESS: {
    mode: 'WORMHOLE_EXPRESS',
    modeName: '04 — WORMHOLE EXPRESS',
    category: 'ANOMALY',
    trackId: 'quantum_highway',
    trackLengthMeters: 10800,
    checkpointCount: 26,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    timeLimitSec: 130,
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Chain-linked spatial wormholes traversing disconnected sectors. Choose stable vortex portals.',
    hazards: [
      {
        type: 'SPATIAL_TURBULENCE',
        name: 'Dimensional Shear Vortex',
        densityMultiplier: 1.3,
        speedMultiplier: 1.3,
        damage: 22,
        warningLeadTimeSec: 1.9,
        hasWarningAudio: true,
        color: '#00ffcc',
        avoidanceWindow: 'STABILIZE VECTOR ALONG CENTRAL AXIS',
      },
      {
        type: 'COLLAPSED_PORTAL',
        name: 'Unstable Rift Remnant',
        densityMultiplier: 1.0,
        speedMultiplier: 1.0,
        damage: 35,
        warningLeadTimeSec: 2.4,
        hasWarningAudio: true,
        color: '#ff0055',
        avoidanceWindow: 'VEER RIGHT INTO REINFORCED BYPASS',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 05 — SOLAR STORM
  SOLAR_STORM: {
    mode: 'SOLAR_STORM',
    modeName: '05 — SOLAR STORM',
    category: 'SURVIVAL',
    trackId: 'cosmic_ring',
    trackLengthMeters: 12200,
    checkpointCount: 30,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 2,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'Orbital perihelion flight skimming a coronal mass ejection. Manage ship heat and cool at shielding nodes.',
    hazards: [
      {
        type: 'SOLAR_FLARE',
        name: 'Coronal Plasma Ejection',
        densityMultiplier: 1.5,
        speedMultiplier: 1.4,
        damage: 28,
        warningLeadTimeSec: 2.6,
        hasWarningAudio: true,
        color: '#ff5500',
        avoidanceWindow: 'DIVE SHADOW OF HEAT SHIELD GANTRY',
      },
      {
        type: 'MAGNETIC_STORM',
        name: 'Magnetic Flux Wall',
        densityMultiplier: 1.2,
        speedMultiplier: 1.2,
        damage: 18,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#ffaa00',
        avoidanceWindow: 'REDUCE BOOST SPEED TO PREVENT CORE OVERHEAT',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 06 — GRAVITY FREE
  GRAVITY_FREE: {
    mode: 'GRAVITY_FREE',
    modeName: '06 — GRAVITY FREE',
    category: 'ANOMALY',
    trackId: 'void_rift',
    trackLengthMeters: 11500,
    checkpointCount: 28,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Zero-gravity aerobatic course with floating kinetic rings, corkscrews, and drift combo multipliers.',
    hazards: [
      {
        type: 'TUMBLING_DEBRIS',
        name: 'Floating Cargo Hull',
        densityMultiplier: 1.2,
        speedMultiplier: 0.9,
        damage: 20,
        warningLeadTimeSec: 2.4,
        hasWarningAudio: false,
        color: '#7000ff',
        avoidanceWindow: 'BARREL ROLL AROUND CONTAINER EDGE',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 07 — PLASMA STORM
  PLASMA_STORM: {
    mode: 'PLASMA_STORM',
    modeName: '07 — PLASMA STORM',
    category: 'SURVIVAL',
    trackId: 'nebula_rift',
    trackLengthMeters: 11800,
    checkpointCount: 28,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 2,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'A catastrophic plasma wall sweeps forward behind racers. Maintain supersonic speeds or be incinerated.',
    hazards: [
      {
        type: 'PLASMA_WALL',
        name: 'Advancing Plasma Wall',
        densityMultiplier: 1.0,
        speedMultiplier: 1.2,
        damage: 50,
        warningLeadTimeSec: 3.0,
        hasWarningAudio: true,
        color: '#ff00aa',
        avoidanceWindow: 'STAY AHEAD OF 100M DANGER RADIUS',
      },
      {
        type: 'LIGHTNING_ARC',
        name: 'Atmospheric Ion Bolt',
        densityMultiplier: 1.5,
        speedMultiplier: 1.5,
        damage: 25,
        warningLeadTimeSec: 1.6,
        hasWarningAudio: true,
        color: '#00f0ff',
        avoidanceWindow: 'RAPID LATERAL DRIFT AWAY FROM ION GROUND',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 08 — SKYLINE RUSH
  SKYLINE_RUSH: {
    mode: 'SKYLINE_RUSH',
    modeName: '08 — SKYLINE RUSH',
    category: 'CIRCUIT',
    trackId: 'neon_orbit',
    trackLengthMeters: 10200,
    checkpointCount: 25,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Multi-tiered highway weaving between orbital megatowers with vertical drops and narrow skybridges.',
    hazards: [
      {
        type: 'LASER_BARRIER',
        name: 'Skybridge Security Grid',
        densityMultiplier: 1.3,
        speedMultiplier: 1.1,
        damage: 22,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#00e5ff',
        avoidanceWindow: 'SLIPSTREAM INTO CENTER CATWALK',
      },
      {
        type: 'MOVING_PLATFORM',
        name: 'Trans-Orbital Shuttle',
        densityMultiplier: 1.1,
        speedMultiplier: 1.0,
        damage: 30,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: true,
        color: '#ffbb00',
        avoidanceWindow: 'SLIPSTREAM BENEATH SHUTTLE ENGINE',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 09 — DEBRIS SURVIVAL
  DEBRIS_SURVIVAL: {
    mode: 'DEBRIS_SURVIVAL',
    modeName: '09 — DEBRIS SURVIVAL',
    category: 'SURVIVAL',
    trackId: 'asteroid_run',
    trackLengthMeters: 12600,
    checkpointCount: 30,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 2,
    defaultDifficulty: 'EXPERT',
    aiDifficulty: 'ACE',
    timeLimitSec: 120,
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'Massive orbital debris field collapsing inward. Dodge or vaporize derelict satellites and kinetic shrapnel.',
    hazards: [
      {
        type: 'FALLING_DEBRIS',
        name: 'Shattered Satellite Core',
        densityMultiplier: 2.2,
        speedMultiplier: 1.4,
        damage: 32,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#ff3366',
        avoidanceWindow: 'FIRE MISSILE / DESTRUCTION BEAM',
      },
      {
        type: 'SHOCKWAVE',
        name: 'Explosive Shrapnel Wave',
        densityMultiplier: 1.6,
        speedMultiplier: 1.3,
        damage: 24,
        warningLeadTimeSec: 1.8,
        hasWarningAudio: true,
        color: '#ffaa00',
        avoidanceWindow: 'DEPLOY ACTIVE SHIELD BUBBLE',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 10 — QUANTUM TIME TRIAL
  QUANTUM_TIME_TRIAL: {
    mode: 'QUANTUM_TIME_TRIAL',
    modeName: '10 — QUANTUM TIME TRIAL',
    category: 'SPECIAL',
    trackId: 'quantum_highway',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 1,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Precision course against ghost telemetry. Gold (45s), Silver (52s), Bronze (60s). High-velocity quantum gates.',
    hazards: [
      {
        type: 'TIME_DISTORTION',
        name: 'Chrono Drag Barrier',
        densityMultiplier: 1.0,
        speedMultiplier: 1.0,
        damage: 10,
        warningLeadTimeSec: 1.8,
        hasWarningAudio: true,
        color: '#39ff14',
        avoidanceWindow: 'ALIGN APEX SPEED TO PRESERVE MOMENTUM',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 11 — ENERGY HEIST
  ENERGY_HEIST: {
    mode: 'ENERGY_HEIST',
    modeName: '11 — ENERGY HEIST',
    category: 'SPECIAL',
    trackId: 'circuit_alpha',
    trackLengthMeters: 10600,
    checkpointCount: 26,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    timeLimitSec: 100,
    targetObjectiveCount: 8,
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Infiltrate high-security energy refinery. Extract 8 unstable energy cores and reach the extraction gateway.',
    hazards: [
      {
        type: 'SECURITY_DRONE',
        name: 'Refinery Defense Sentry',
        densityMultiplier: 1.4,
        speedMultiplier: 1.1,
        damage: 22,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: true,
        color: '#ff0033',
        avoidanceWindow: 'LAUNCH HOMING MISSILE BEFORE CONTACT',
      },
      {
        type: 'LASER_GRID',
        name: 'Locked Perimeter Grid',
        densityMultiplier: 1.2,
        speedMultiplier: 1.0,
        damage: 28,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#00f0ff',
        avoidanceWindow: 'DIVERT INTO ACCESS TUNNEL SHORTCUT',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 12 — DRONE ASSAULT
  DRONE_ASSAULT: {
    mode: 'DRONE_ASSAULT',
    modeName: '12 — DRONE ASSAULT',
    category: 'SPECIAL',
    trackId: 'void_rift',
    trackLengthMeters: 11400,
    checkpointCount: 28,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 2,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    targetObjectiveCount: 18,
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Combat assault sector overrun by enemy drones. Utilize missiles, front beam, and active shields to survive.',
    hazards: [
      {
        type: 'COMBAT_DRONE',
        name: 'Assault Swarm Drone',
        densityMultiplier: 1.8,
        speedMultiplier: 1.3,
        damage: 25,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: true,
        color: '#ff0044',
        avoidanceWindow: 'FIRE HOMING MISSILE (M) OR LASER BEAM',
      },
      {
        type: 'TURRET_CANNON',
        name: 'Spire Energy Cannon',
        densityMultiplier: 1.0,
        speedMultiplier: 1.4,
        damage: 35,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#ff9900',
        avoidanceWindow: 'ACTIVATE SHIELD (C) UPON TARGET LOCK',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 13 — COLLAPSING TRACK
  COLLAPSING_TRACK: {
    mode: 'COLLAPSING_TRACK',
    modeName: '13 — COLLAPSING TRACK',
    category: 'SURVIVAL',
    trackId: 'neon_orbit',
    trackLengthMeters: 12000,
    checkpointCount: 28,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 2,
    defaultDifficulty: 'EXPERT',
    aiDifficulty: 'ACE',
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'Disintegrating orbital megastructure. Segments plunge into the abyss behind you. Real-time minimap route updates.',
    hazards: [
      {
        type: 'FALLING_PLATFORM',
        name: 'Track Structural Failure',
        densityMultiplier: 1.5,
        speedMultiplier: 1.3,
        damage: 45,
        warningLeadTimeSec: 2.5,
        hasWarningAudio: true,
        color: '#ff0000',
        avoidanceWindow: 'BRANCH TO INTACT ELEVATED OVERPASS',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 14 — RING RUNNER
  RING_RUNNER: {
    mode: 'RING_RUNNER',
    modeName: '14 — RING RUNNER',
    category: 'SPECIAL',
    trackId: 'cosmic_ring',
    trackLengthMeters: 11000,
    checkpointCount: 26,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    targetObjectiveCount: 16,
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Continuous rotating orbital rings suspended around gas giant. Thread rings in sequence for score combos.',
    hazards: [
      {
        type: 'ROTATING_RING_EDGE',
        name: 'Kinetic Ring Collider',
        densityMultiplier: 1.2,
        speedMultiplier: 1.3,
        damage: 20,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#00ffcc',
        avoidanceWindow: 'ALIGN ROLL ANGLE WITH RING APERTURE',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 15 — HYPERSPACE SPRINT
  HYPERSPACE_SPRINT: {
    mode: 'HYPERSPACE_SPRINT',
    modeName: '15 — HYPERSPACE SPRINT',
    category: 'ANOMALY',
    trackId: 'quantum_highway',
    trackLengthMeters: 13500,
    checkpointCount: 32,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 2,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Warp speed beyond 500 KM/H. Ultra-fast reflex lane changes between energy walls and supersonic lane blockers.',
    hazards: [
      {
        type: 'ENERGY_WALL',
        name: 'Subspace Refraction Barrier',
        densityMultiplier: 1.5,
        speedMultiplier: 1.6,
        damage: 30,
        warningLeadTimeSec: 1.7,
        hasWarningAudio: true,
        color: '#ff0066',
        avoidanceWindow: 'INSTANT SLIPSTREAM LANE CHANGE',
      },
      {
        type: 'TURBULENCE_ZONE',
        name: 'Warp Shear Field',
        densityMultiplier: 1.3,
        speedMultiplier: 1.4,
        damage: 18,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#00f0ff',
        avoidanceWindow: 'ENGAGE CENTER ACCELERATION STRIP',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 16 — RIVAL DUEL
  RIVAL_DUEL: {
    mode: 'RIVAL_DUEL',
    modeName: '16 — RIVAL DUEL',
    category: 'CIRCUIT',
    trackId: 'nebula_rift',
    trackLengthMeters: 10500,
    checkpointCount: 26,
    junctionCount: 3,
    routeCount: 7,
    baseLaps: 3,
    defaultDifficulty: 'EXPERT',
    aiDifficulty: 'ACE',
    recoveryAvailability: 'FAST',
    mechanicsDescription: '1v1 grudge match against ace ace "Zer0". The rival utilizes real-time missiles, shields, and tactical shortcuts.',
    hazards: [
      {
        type: 'RIVAL_MISSILE',
        name: 'Rival Homing Missile',
        densityMultiplier: 1.0,
        speedMultiplier: 1.2,
        damage: 35,
        warningLeadTimeSec: 2.8,
        hasWarningAudio: true,
        color: '#ff0033',
        avoidanceWindow: 'DEPLOY SHIELD (C) OR DROP FLARE',
      },
      {
        type: 'ENERGY_BARRIER',
        name: 'Track Choke Energy Grid',
        densityMultiplier: 1.1,
        speedMultiplier: 1.0,
        damage: 20,
        warningLeadTimeSec: 2.1,
        hasWarningAudio: true,
        color: '#ffaa00',
        avoidanceWindow: 'DIVE INSIDE THE INNER APEX',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 17 — RELAY RACE
  RELAY_RACE: {
    mode: 'RELAY_RACE',
    modeName: '17 — RELAY RACE',
    category: 'CIRCUIT',
    trackId: 'circuit_alpha',
    trackLengthMeters: 13000,
    checkpointCount: 30,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: '3-stage team relay. Automatic ship swap at specialized relay stations: Speed, Handling, and Combat hulls.',
    hazards: [
      {
        type: 'RELAY_GATE_OBSTACLE',
        name: 'Docking Alignment Barrier',
        densityMultiplier: 1.2,
        speedMultiplier: 1.1,
        damage: 22,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: true,
        color: '#00e5ff',
        avoidanceWindow: 'CENTER FLIGHT VECTOR THROUGH RELAY RING',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 18 — SURVIVAL ELIMINATION
  SURVIVAL_ELIMINATION: {
    mode: 'SURVIVAL_ELIMINATION',
    modeName: '18 — SURVIVAL ELIMINATION',
    category: 'SURVIVAL',
    trackId: 'asteroid_run',
    trackLengthMeters: 11600,
    checkpointCount: 28,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 4,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'Last place racer is eliminated every 25 seconds. Arena danger zone expands rapidly.',
    hazards: [
      {
        type: 'KNOCKOUT_PULSE',
        name: 'Rear Elimination Shockwave',
        densityMultiplier: 1.0,
        speedMultiplier: 1.2,
        damage: 100,
        warningLeadTimeSec: 5.0,
        hasWarningAudio: true,
        color: '#ff0000',
        avoidanceWindow: 'OVERTAKE NEAREST RIVAL BEFORE COUNTDOWN',
      },
      {
        type: 'KINETIC_BOULDER',
        name: 'Track Shrapnel Hazard',
        densityMultiplier: 1.5,
        speedMultiplier: 1.2,
        damage: 25,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: true,
        color: '#ff8800',
        avoidanceWindow: 'EVADE WIDE TO PRESERVE POSITION',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 19 — COSMIC TREASURE HUNT
  COSMIC_TREASURE_HUNT: {
    mode: 'COSMIC_TREASURE_HUNT',
    modeName: '19 — COSMIC TREASURE HUNT',
    category: 'SPECIAL',
    trackId: 'void_rift',
    trackLengthMeters: 12400,
    checkpointCount: 30,
    junctionCount: 4,
    routeCount: 10,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    timeLimitSec: 160,
    targetObjectiveCount: 3,
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Ancient alien ruins with branching subterranean paths. Use the tactical radar scanner to extract 3 sacred relics.',
    hazards: [
      {
        type: 'RUIN_MINE',
        name: 'Proximity Guardian Mine',
        densityMultiplier: 1.6,
        speedMultiplier: 1.0,
        damage: 28,
        warningLeadTimeSec: 2.4,
        hasWarningAudio: true,
        color: '#00ffcc',
        avoidanceWindow: 'DETONATE WITH FRONT BEAM AT DISTANCE',
      },
      {
        type: 'COLLAPSING_RUIN',
        name: 'Ancient Column Collapse',
        densityMultiplier: 1.2,
        speedMultiplier: 1.3,
        damage: 35,
        warningLeadTimeSec: 2.0,
        hasWarningAudio: true,
        color: '#ff00aa',
        avoidanceWindow: 'DRIFT INTO LOWER CRYPT RUNWAY',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // 20 — VOID CHAMPIONSHIP
  VOID_CHAMPIONSHIP: {
    mode: 'VOID_CHAMPIONSHIP',
    modeName: '20 — VOID CHAMPIONSHIP',
    category: 'CIRCUIT',
    trackId: 'neon_orbit',
    trackLengthMeters: 12800,
    checkpointCount: 32,
    junctionCount: 3,
    routeCount: 8,
    baseLaps: 3,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    targetObjectiveCount: 6,
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: '6-stage premier championship. Stages: Neon Circuit -> Asteroid Run -> Solar Storm -> Collapsing Track -> Rival Duel -> Hyperspace Sprint.',
    hazards: [
      {
        type: 'CHAMPIONSHIP_HAZARD',
        name: 'Touring Grand Prix Hazard Field',
        densityMultiplier: 1.4,
        speedMultiplier: 1.2,
        damage: 25,
        warningLeadTimeSec: 2.2,
        hasWarningAudio: true,
        color: '#00f0ff',
        avoidanceWindow: 'BALANCED DEFENSIVE AND ATTACK DRIVING',
      },
    ],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },

  // Fallbacks
  STANDARD: {
    mode: 'STANDARD',
    modeName: 'STANDARD GRAND PRIX',
    category: 'CIRCUIT',
    trackId: 'circuit_alpha',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Standard competitive championship racing.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  GRAND_PRIX: {
    mode: 'GRAND_PRIX',
    modeName: 'GRAND PRIX',
    category: 'CIRCUIT',
    trackId: 'circuit_alpha',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Multi-lap grand prix tournament.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  TIME_TRIAL: {
    mode: 'TIME_TRIAL',
    modeName: 'TIME TRIAL',
    category: 'SPECIAL',
    trackId: 'circuit_alpha',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 1,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Solo lap time attack.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  SURVIVAL: {
    mode: 'SURVIVAL',
    modeName: 'SURVIVAL',
    category: 'SURVIVAL',
    trackId: 'asteroid_run',
    trackLengthMeters: 10400,
    checkpointCount: 26,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 2,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'RESTRICTED',
    mechanicsDescription: 'Endurance survival race.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  ELIMINATION: {
    mode: 'ELIMINATION',
    modeName: 'ELIMINATION',
    category: 'SURVIVAL',
    trackId: 'circuit_alpha',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Elimination knockout racing.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  ELIMINATOR: {
    mode: 'ELIMINATOR',
    modeName: 'ELIMINATOR',
    category: 'SURVIVAL',
    trackId: 'circuit_alpha',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 3,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Progressive knockout eliminator.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  ENDURANCE: {
    mode: 'ENDURANCE',
    modeName: 'ENDURANCE',
    category: 'CIRCUIT',
    trackId: 'neon_orbit',
    trackLengthMeters: 10800,
    checkpointCount: 28,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 5,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'VETERAN',
    recoveryAvailability: 'STANDARD',
    mechanicsDescription: 'Long distance endurance challenge.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  DUEL: {
    mode: 'DUEL',
    modeName: 'DUEL',
    category: 'CIRCUIT',
    trackId: 'nebula_rift',
    trackLengthMeters: 9600,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 2,
    defaultDifficulty: 'HARD',
    aiDifficulty: 'ACE',
    recoveryAvailability: 'FAST',
    mechanicsDescription: '1v1 pilot duel.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  CHALLENGE: {
    mode: 'CHALLENGE',
    modeName: 'CHALLENGE',
    category: 'SPECIAL',
    trackId: 'void_rift',
    trackLengthMeters: 10000,
    checkpointCount: 26,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 2,
    defaultDifficulty: 'NORMAL',
    aiDifficulty: 'STANDARD',
    recoveryAvailability: 'FAST',
    mechanicsDescription: 'Tactical flight challenges.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
  FREE_RIDE: {
    mode: 'FREE_RIDE',
    modeName: 'FREE RIDE',
    category: 'SPECIAL',
    trackId: 'neon_orbit',
    trackLengthMeters: 9800,
    checkpointCount: 24,
    junctionCount: 2,
    routeCount: 6,
    baseLaps: 99,
    defaultDifficulty: 'EASY',
    aiDifficulty: 'RECRUIT',
    recoveryAvailability: 'INSTANT',
    mechanicsDescription: 'Exploration and test cruising.',
    hazards: [],
    difficultyScaling: DEFAULT_DIFFICULTY_SCALING,
  },
};

export function getModeConfig(mode: GameMode): ModeSpecificSettings {
  return ALL_MODES_CONFIG[mode] || ALL_MODES_CONFIG.NEON_CIRCUIT;
}

export function getDifficultyProfile(mode: GameMode, difficulty: GameDifficulty) {
  const cfg = getModeConfig(mode);
  return cfg.difficultyScaling[difficulty] || cfg.difficultyScaling.NORMAL;
}
