import { GameMode } from '../../types';
import { ExtendedPathConfig } from './extendedPathTypes';
import {
  MODE_PATH_01_SINGULARITY,
  MODE_PATH_02_NEON,
  MODE_PATH_03_ASTEROID,
  MODE_PATH_04_WORMHOLE,
  MODE_PATH_05_SOLAR,
} from './modePaths1to5';
import {
  MODE_PATH_06_GRAVITY_FREE,
  MODE_PATH_07_PLASMA_STORM,
  MODE_PATH_08_SKYLINE,
  MODE_PATH_09_DEBRIS,
  MODE_PATH_10_QUANTUM_TIME,
} from './modePaths6to10';
import {
  MODE_PATH_11_ENERGY_HEIST,
  MODE_PATH_12_DRONE_ASSAULT,
  MODE_PATH_13_COLLAPSING_TRACK,
  MODE_PATH_14_RING_RUNNER,
  MODE_PATH_15_HYPERSPACE,
} from './modePaths11to15';
import {
  MODE_PATH_16_RIVAL_DUEL,
  MODE_PATH_17_RELAY_RACE,
  MODE_PATH_18_SURVIVAL_ELIMINATION,
  MODE_PATH_19_TREASURE_HUNT,
  MODE_PATH_20_VOID_CHAMPIONSHIP,
} from './modePaths16to20';

export const ALL_MODE_EXTENDED_PATHS: Partial<Record<GameMode, ExtendedPathConfig>> = {
  SINGULARITY_RUN: MODE_PATH_01_SINGULARITY,
  NEON_CIRCUIT: MODE_PATH_02_NEON,
  ASTEROID_RUN: MODE_PATH_03_ASTEROID,
  WORMHOLE_EXPRESS: MODE_PATH_04_WORMHOLE,
  SOLAR_STORM: MODE_PATH_05_SOLAR,
  GRAVITY_FREE: MODE_PATH_06_GRAVITY_FREE,
  PLASMA_STORM: MODE_PATH_07_PLASMA_STORM,
  SKYLINE_RUSH: MODE_PATH_08_SKYLINE,
  DEBRIS_SURVIVAL: MODE_PATH_09_DEBRIS,
  QUANTUM_TIME_TRIAL: MODE_PATH_10_QUANTUM_TIME,
  ENERGY_HEIST: MODE_PATH_11_ENERGY_HEIST,
  DRONE_ASSAULT: MODE_PATH_12_DRONE_ASSAULT,
  COLLAPSING_TRACK: MODE_PATH_13_COLLAPSING_TRACK,
  RING_RUNNER: MODE_PATH_14_RING_RUNNER,
  HYPERSPACE_SPRINT: MODE_PATH_15_HYPERSPACE,
  RIVAL_DUEL: MODE_PATH_16_RIVAL_DUEL,
  RELAY_RACE: MODE_PATH_17_RELAY_RACE,
  SURVIVAL_ELIMINATION: MODE_PATH_18_SURVIVAL_ELIMINATION,
  COSMIC_TREASURE_HUNT: MODE_PATH_19_TREASURE_HUNT,
  VOID_CHAMPIONSHIP: MODE_PATH_20_VOID_CHAMPIONSHIP,
};

export function getExtendedPathConfig(mode: GameMode): ExtendedPathConfig {
  return ALL_MODE_EXTENDED_PATHS[mode] || MODE_PATH_02_NEON;
}
