export type CosmicElementType =
  | 'PLANET'
  | 'PROTOPLANET'
  | 'MOON'
  | 'STATION'
  | 'ASTEROID'
  | 'RING_SEGMENT'
  | 'PLASMA_JET'
  | 'GAS_CLOUD'
  | 'COMET'
  | 'STRUCTURE'
  | 'CORE_REMNANT';

export interface CosmicEventElement {
  id: string;
  name: string;
  type: CosmicElementType;
  realAppearance: string;
  color: number;
  emissiveColor: number;
  radius: number;
  initialOrbitRadius: number; // distance from black hole center in meters
  orbitSpeed: number; // revolution angular velocity (rad/s)
  revolutionEccentricity: number; // 0 = circular, > 0 = elliptical Keplerian orbit
  collisionTimeRatio: number; // normalized event phase when collision/encounter occurs (0.0 to 1.0)
  spaghettificationRate: number; // speed of tidal elongation and shredding into particle streams
  particleCount: number; // number of spaghettified particle filaments
  particleColor: number;
  occurrenceDescription: string;
  completionGuidance: string; // How this element helps the player complete the event
}

export interface CosmicEventPairData {
  eventIndex: number;
  eventId: string;
  element1: CosmicEventElement;
  element2: CosmicEventElement;
  eventOccurrenceNarrative: string;
  completionStrategy: string;
}

export const COSMIC_40_EVENT_PAIRS: Record<number, CosmicEventPairData> = {
  1: {
    eventIndex: 1,
    eventId: 'gravity_distortion',
    element1: {
      id: 'e1_kepler77',
      name: 'Outer Asteroid Kepler-77',
      type: 'ASTEROID',
      realAppearance: 'Porous carbonaceous chondrite with frozen methane rime, charcoal gray with cyan glints',
      color: 0x475569,
      emissiveColor: 0x06b6d4,
      radius: 45,
      initialOrbitRadius: 2800,
      orbitSpeed: 0.12,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.25,
      particleCount: 160,
      particleColor: 0x38bdf8,
      occurrenceDescription: 'Bends inward toward the black hole along an unstable trajectory, shedding surface methane ice into glowing particle streaks.',
      completionGuidance: 'Follow the slipstream behind Kepler-77 to shield against early gravitational cross-winds.',
    },
    element2: {
      id: 'e2_sensor_sigma',
      name: 'Deep-Space Sensor Buoy Sigma',
      type: 'STATION',
      realAppearance: 'Hexagonal titanium relay spire with rotating telemetry rings and pulsing cyan beacons',
      color: 0x0284c7,
      emissiveColor: 0x38bdf8,
      radius: 26,
      initialOrbitRadius: 2650,
      orbitSpeed: 0.15,
      revolutionEccentricity: 0.15,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.2,
      particleCount: 120,
      particleColor: 0x22d3ee,
      occurrenceDescription: 'Revolves synchronously with the asteroid before its gyro stabilizers overload and disperse sensor telemetry particles.',
      completionGuidance: 'Align your flight vector with Buoy Sigma to recalibrate navigational gyros and nullify steering drift.',
    },
    eventOccurrenceNarrative: 'The black hole tidal gradient perturbs Kepler-77 and Sensor Buoy Sigma into mutual orbital convergence; tidal shear peels asteroid dust into a luminous particle filament while Sigma broadcasts emergency escape vectors.',
    completionStrategy: 'Ride the green telemetry corridor projected between Sensor Buoy Sigma and Asteroid Kepler-77 to neutralize gravity distortion.',
  },

  2: {
    eventIndex: 2,
    eventId: 'orbital_failure',
    element1: {
      id: 'e1_phobos_iv',
      name: 'Silicate Moon Phobos-IV',
      type: 'MOON',
      realAppearance: 'Scarred cratered basaltic moonlet with glowing tectonic fractures and pulverized regolith ribbons',
      color: 0x64748b,
      emissiveColor: 0xf59e0b,
      radius: 88,
      initialOrbitRadius: 2700,
      orbitSpeed: 0.18,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.55,
      spaghettificationRate: 0.35,
      particleCount: 220,
      particleColor: 0xfbbf24,
      occurrenceDescription: 'Loses Keplerian stability, revolving in a decaying inward spiral while ejecting glowing tectonic dust filaments.',
      completionGuidance: 'Use Phobos-IV gravitational slingshot to preserve forward momentum without consuming boost reserves.',
    },
    element2: {
      id: 'e2_habitat_ring',
      name: 'Orbital Habitat Ring Genesis',
      type: 'STATION',
      realAppearance: 'Revolving dual torus superstructure with amber observation domes and solar photovoltaic arrays',
      color: 0x334155,
      emissiveColor: 0x0ea5e9,
      radius: 110,
      initialOrbitRadius: 2450,
      orbitSpeed: 0.22,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.55,
      spaghettificationRate: 0.3,
      particleCount: 190,
      particleColor: 0x38bdf8,
      occurrenceDescription: 'Centrifugal station keeping fails; docking struts buckle into a shower of illuminated structural particles.',
      completionGuidance: 'Thread through the central zero-gravity aperture of Habitat Ring Genesis to bypass the orbital cross-drift zone.',
    },
    eventOccurrenceNarrative: 'Moon Phobos-IV and Habitat Ring Genesis lose orbital equilibrium; the moon shears through the habitat outer perimeter, unleashing an expanding ring of spaghettified hull particles spiraling toward the black hole.',
    completionStrategy: 'Execute a high-G roll through the hollow center of Habitat Ring Genesis just as Phobos-IV completes its closest orbital pass.',
  },

  3: {
    eventIndex: 3,
    eventId: 'tidal_wave',
    element1: {
      id: 'e1_megatower_alpha',
      name: 'Suspension Megatower Alpha',
      type: 'STRUCTURE',
      realAppearance: 'Monolithic carbon-nanotube spire with high-tension mooring cables and amber hazard lights',
      color: 0x1e293b,
      emissiveColor: 0xf97316,
      radius: 130,
      initialOrbitRadius: 2500,
      orbitSpeed: 0.14,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.45,
      particleCount: 240,
      particleColor: 0xfb923c,
      occurrenceDescription: 'Undergoes immense tensile stretching along the singularity axis, bending 60 degrees before fracture.',
      completionGuidance: 'Maintain center-lane positioning beneath the suspension arch before tensile cables snap.',
    },
    element2: {
      id: 'e2_conduit_rail',
      name: 'Magnetic Conduit Rail Nexus',
      type: 'RING_SEGMENT',
      realAppearance: 'Segmented superconducting maglev conduit ring pulsing with cerulean plasma arcs',
      color: 0x0f172a,
      emissiveColor: 0x06b6d4,
      radius: 95,
      initialOrbitRadius: 2300,
      orbitSpeed: 0.19,
      revolutionEccentricity: 0.15,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.4,
      particleCount: 210,
      particleColor: 0x67e8f9,
      occurrenceDescription: 'Superconducting conduit rails stretch and rupture, spraying high-voltage ion particles into space.',
      completionGuidance: 'Catch the magnetic boost pulse along the conduit segment to surge ahead of the tidal wave crest.',
    },
    eventOccurrenceNarrative: 'Differential gravitational pull stretches Megatower Alpha and Conduit Rail Nexus into elongated spaghettified ribbons; high-voltage arcs discharge across the vacuum as structures dissolve into glowing ion streams.',
    completionStrategy: 'Boost beneath Megatower Alpha precisely as Conduit Rail Nexus releases its electromagnetic discharge.',
  },

  4: {
    eventIndex: 4,
    eventId: 'planetary_collision',
    element1: {
      id: 'e1_planet_aurelia',
      name: 'Primary Planet Aurelia',
      type: 'PLANET',
      realAppearance: 'Vast continental terrestrial world with glowing magma rifts, azure oceans, and violet atmospheric swirl',
      color: 0x2563eb,
      emissiveColor: 0xef4444,
      radius: 220,
      initialOrbitRadius: 2900,
      orbitSpeed: 0.24,
      revolutionEccentricity: 0.45,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.65,
      particleCount: 420,
      particleColor: 0xf97316,
      occurrenceDescription: 'Revolves in decaying Keplerian ellipse; after collision, molten crust spaghettifies into hundreds of glowing particles spiraling into singularity.',
      completionGuidance: 'Dive beneath Aurelia expanding planetary shockwave to ride its gravity assist envelope.',
    },
    element2: {
      id: 'e2_proto_zephyr',
      name: 'Proto-Planet Zephyr',
      type: 'PROTOPLANET',
      realAppearance: 'Molten iron-silicate rogue proto-world with fractured glowing crust and dense sulfur volcanic plumes',
      color: 0xd97706,
      emissiveColor: 0xf59e0b,
      radius: 170,
      initialOrbitRadius: 2750,
      orbitSpeed: -0.28,
      revolutionEccentricity: 0.5,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.7,
      particleCount: 450,
      particleColor: 0xfbbf24,
      occurrenceDescription: 'Collides head-on with Aurelia; kinetic impact generates colossal shockwave ring before remnants spaghettify into the black hole.',
      completionGuidance: 'Avoid the high-density impact epicenter by veering 25 degrees port along the shockwave perimeter.',
    },
    eventOccurrenceNarrative: 'Primary Planet Aurelia and Proto-Planet Zephyr collide in hyper-velocity impact! The impact converts kinetic energy into an expanding plasma shockwave. The fractured remnants revolve in a chaotic mutual barycenter orbit before being caught in the black hole tidal shear, spaghettifying into hundreds of glowing molten particle filaments that spiral directly into the singularity!',
    completionStrategy: 'Throttle up through the clear vacuum pocket between the revolving colliding planets before the spaghettified particle storm envelops the corridor.',
  },

  5: {
    eventIndex: 5,
    eventId: 'accretion_surge',
    element1: {
      id: 'e1_plasma_inflow',
      name: 'Relativistic Plasma Inflow Jet',
      type: 'PLASMA_JET',
      realAppearance: 'Helical vortex stream of superheated orange-amber ionized matter accelerating toward the event horizon',
      color: 0xf97316,
      emissiveColor: 0xffedd5,
      radius: 140,
      initialOrbitRadius: 2200,
      orbitSpeed: 0.35,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.65,
      spaghettificationRate: 0.6,
      particleCount: 380,
      particleColor: 0xfde047,
      occurrenceDescription: 'Inflow stream spins up to relativistic velocity, shedding glowing synchrotron radiation particles.',
      completionGuidance: 'Skim the outer boundary of the plasma jet to supercharge your shield capacitors and gain emergency boost.',
    },
    element2: {
      id: 'e2_fragment_core',
      name: 'Sub-stellar Fragment Core',
      type: 'CORE_REMNANT',
      realAppearance: 'Hyper-dense white-hot iron core remnant glowing with intense electromagnetic corona',
      color: 0xf8fafc,
      emissiveColor: 0x38bdf8,
      radius: 65,
      initialOrbitRadius: 1950,
      orbitSpeed: 0.42,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.65,
      spaghettificationRate: 0.75,
      particleCount: 340,
      particleColor: 0xbae6fd,
      occurrenceDescription: 'Revolves at near relativistic speed; tidal friction peels its surface into glowing particle filaments drawn inward.',
      completionGuidance: 'Align directly behind the core remnant wake to exploit its gravitational drag-reduction corridor.',
    },
    eventOccurrenceNarrative: 'The white-hot Fragment Core plunges through the Relativistic Plasma Inflow Jet, creating an explosive accretion flash that accelerates spaghettified plasma streams directly into the black hole accretion disk.',
    completionStrategy: 'Ride the magnetic wake 40 meters behind the revolving core remnant to complete the sector before plasma turbulence peaks.',
  },

  6: {
    eventIndex: 6,
    eventId: 'destruction_front',
    element1: {
      id: 'e1_spire_zero',
      name: 'Sector Megastructure Spire Zero',
      type: 'STRUCTURE',
      realAppearance: 'Monolithic hexagonal composite lattice tower with illuminated transit docks crumbling into vacuum',
      color: 0x334155,
      emissiveColor: 0xef4444,
      radius: 160,
      initialOrbitRadius: 2100,
      orbitSpeed: 0.16,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.4,
      spaghettificationRate: 0.5,
      particleCount: 280,
      particleColor: 0xf87171,
      occurrenceDescription: 'Shears cleanly at its foundation, rotating end-over-end as its structural girders spaghettify into the void.',
      completionGuidance: 'Maintain continuous velocity above 200 km/h to keep ahead of Spire Zero falling debris radius.',
    },
    element2: {
      id: 'e2_fracture_front',
      name: 'Cosmic Fracture Wave Front',
      type: 'GAS_CLOUD',
      realAppearance: 'Supersonic planar distortion wave tearing through spacetime and vaporizing unshielded structures',
      color: 0x7c3aed,
      emissiveColor: 0xa855f7,
      radius: 260,
      initialOrbitRadius: 2400,
      orbitSpeed: 0.3,
      revolutionEccentricity: 0.05,
      collisionTimeRatio: 0.4,
      spaghettificationRate: 0.8,
      particleCount: 360,
      particleColor: 0xc084fc,
      occurrenceDescription: 'Sweeps along the track at 65 m/s, consuming trailing route segments into pure spaghettified particle mist.',
      completionGuidance: 'Hit boost pads along the forward runway to extend your clearance distance ahead of the wave front.',
    },
    eventOccurrenceNarrative: 'Spire Zero collapses directly into the advancing Cosmic Fracture Wave Front, pulverizing millions of tons of composite matter into a curtain of purple-glowing spaghettified particles flowing toward the singularity.',
    completionStrategy: 'Commit to full forward burn without braking; use the compression shockwave behind Spire Zero for exit acceleration.',
  },

  7: {
    eventIndex: 7,
    eventId: 'gravity_reversal',
    element1: {
      id: 'e1_buoy_node',
      name: 'Quantum Stabilizer Buoy Node',
      type: 'STATION',
      realAppearance: 'Floating octagonal quantum stabilizer module pulsing with emerald electromagnetic levitation rings',
      color: 0x059669,
      emissiveColor: 0x34d399,
      radius: 48,
      initialOrbitRadius: 2000,
      orbitSpeed: 0.22,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.4,
      particleCount: 200,
      particleColor: 0x6ee7b7,
      occurrenceDescription: 'Undulates vertically in harmonic resonance, emitting green counter-gravity particle rings.',
      completionGuidance: 'Pass directly through the green levitation rings of the Buoy Node to stabilize craft inverted pitch.',
    },
    element2: {
      id: 'e2_lithos_cluster',
      name: 'Inverted Asteroid Cluster Lithos',
      type: 'ASTEROID',
      realAppearance: 'Cluster of porous crystalline rocks with glowing luminescent veins floating against gravity',
      color: 0x475569,
      emissiveColor: 0x10b981,
      radius: 85,
      initialOrbitRadius: 1850,
      orbitSpeed: -0.26,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.55,
      particleCount: 260,
      particleColor: 0xa7f3d0,
      occurrenceDescription: 'Revolves in an inverted vertical loop around the buoy, shedding stretched crystalline needle particles.',
      completionGuidance: 'Invert roll angle to mirror Lithos Cluster trajectory and exploit the negative-G lift corridor.',
    },
    eventOccurrenceNarrative: 'Interference patterns between competing relativistic frame-dragging fields cause Buoy Node and Asteroid Lithos to oscillate in reverse gravity loops, casting glowing emerald particle arcs into the flight corridor.',
    completionStrategy: 'Invert craft orientation by 180 degrees beneath the Buoy Node to ride the negative gravity surge across the sector.',
  },

  8: {
    eventIndex: 8,
    eventId: 'spaghettification_wave',
    element1: {
      id: 'e1_asteroid_m38',
      name: 'Iron-Nickel Asteroid M-38',
      type: 'ASTEROID',
      realAppearance: 'Dense metallic oblong asteroid undergoing extreme tensile stretching along the singularity axis',
      color: 0x64748b,
      emissiveColor: 0xf43f5e,
      radius: 75,
      initialOrbitRadius: 1900,
      orbitSpeed: 0.28,
      revolutionEccentricity: 0.6,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.85,
      particleCount: 360,
      particleColor: 0xfb7185,
      occurrenceDescription: 'Stretches by 340% into a needle-thin metallic ribbon before disintegrating into glowing red particle streams.',
      completionGuidance: 'Fly parallel to the stretched axis of Asteroid M-38 to minimize tidal lateral shear on your wings.',
    },
    element2: {
      id: 'e2_transit_spine',
      name: 'Segmented Transit Spine',
      type: 'STRUCTURE',
      realAppearance: 'Modular magnetic maglev transit spine with glowing crimson danger beacons and stretching pylons',
      color: 0x1e293b,
      emissiveColor: 0xe11d48,
      radius: 120,
      initialOrbitRadius: 1750,
      orbitSpeed: 0.32,
      revolutionEccentricity: 0.5,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.8,
      particleCount: 320,
      particleColor: 0xffa3a3,
      occurrenceDescription: 'Pylons pull apart like taffy, spinning in an elongated helix and spraying structural particles inward.',
      completionGuidance: 'Thread the needle through the central gap of the separating transit spine modules before complete collapse.',
    },
    eventOccurrenceNarrative: 'Extreme tidal shear stretches Asteroid M-38 and the Transit Spine into paper-thin luminous ribbons that revolve at near relativistic speed before completely evaporating into streaming particle geodesics falling toward the black hole.',
    completionStrategy: 'Steer precisely along the central compression null-line between both elongating bodies where tidal stress cancels out.',
  },

  9: {
    eventIndex: 9,
    eventId: 'station_collapse',
    element1: {
      id: 'e1_station_hub',
      name: 'Citadel Station Central Hub',
      type: 'STATION',
      realAppearance: 'Titanium-reinforced cylindrical space citadel with glowing pressurized habitat windows and communication masts',
      color: 0x334155,
      emissiveColor: 0x38bdf8,
      radius: 150,
      initialOrbitRadius: 2100,
      orbitSpeed: 0.19,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.6,
      particleCount: 310,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Buckles under tidal torque, venting glowing atmosphere particles while spinning into a death spiral.',
      completionGuidance: 'Ride the decompression jet venting from the hub to propel your ship through the debris field.',
    },
    element2: {
      id: 'e2_docking_arch',
      name: 'Detached Docking Arch Beta',
      type: 'RING_SEGMENT',
      realAppearance: 'Curved habitat ring segment with blinking crimson emergency strobes and fractured hydraulic couplings',
      color: 0x1e293b,
      emissiveColor: 0xf59e0b,
      radius: 115,
      initialOrbitRadius: 1900,
      orbitSpeed: -0.23,
      revolutionEccentricity: 0.28,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.65,
      particleCount: 290,
      particleColor: 0xfde047,
      occurrenceDescription: 'Tears free from the hub and revolves on an intersecting vector, spaghettifying into hundreds of hull fragments.',
      completionGuidance: 'Fly directly through the archway of Docking Arch Beta before its rotational inertia closes the window.',
    },
    eventOccurrenceNarrative: 'Tidal torque severs Docking Arch Beta from Citadel Station Central Hub; the binary structures collide and tumble together, casting an expanding halo of spaghettified hull particles toward the black hole event horizon.',
    completionStrategy: 'Speed through the hollow center of Docking Arch Beta as it shears past Citadel Station Central Hub.',
  },

  10: {
    eventIndex: 10,
    eventId: 'debris_storm',
    element1: {
      id: 'e1_hyper_chondrite',
      name: 'Hyper-Velocity Chondrite Swarm',
      type: 'ASTEROID',
      realAppearance: 'Cluster of dense iron-nickel meteorites traveling at Mach 50 with incandescent ablative fire trails',
      color: 0x78716c,
      emissiveColor: 0xf97316,
      radius: 90,
      initialOrbitRadius: 2000,
      orbitSpeed: 0.45,
      revolutionEccentricity: 0.65,
      collisionTimeRatio: 0.45,
      spaghettificationRate: 0.7,
      particleCount: 400,
      particleColor: 0xfb923c,
      occurrenceDescription: 'Revolves through the outer accretion zone at hyper-velocity, carving a high-density trail of glowing molten particles.',
      completionGuidance: 'Follow the wake punched by the lead chondrite meteorite to pass safely through the dense debris curtain.',
    },
    element2: {
      id: 'e2_solar_sail',
      name: 'Fractured Solar Sail Array',
      type: 'STRUCTURE',
      realAppearance: 'Reflective gold-foil photovoltaic sail torn into fluttering kilometers-wide spaghettified ribbons',
      color: 0xeab308,
      emissiveColor: 0xfef08a,
      radius: 140,
      initialOrbitRadius: 1800,
      orbitSpeed: -0.38,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.45,
      spaghettificationRate: 0.75,
      particleCount: 380,
      particleColor: 0xfef9c3,
      occurrenceDescription: 'Impacts the chondrite swarm and disintegrates into shimmering golden reflective particles caught in the accretion pull.',
      completionGuidance: 'Use the reflective gold-foil particle cloud to blind chasing rival craft and slip past obstacles.',
    },
    eventOccurrenceNarrative: 'The Hyper-Velocity Chondrite Swarm impacts the Fractured Solar Sail Array in a blinding kinetic flash; gold-foil ribbons and iron fragments revolve around the black hole, spaghettifying into thousands of glittering particles.',
    completionStrategy: 'Lock onto the lead meteorite trajectory and slipstream directly behind it through the golden debris storm.',
  },

  // Events 11 to 20
  11: {
    eventIndex: 11,
    eventId: 'event_horizon_influence',
    element1: {
      id: 'e1_lensed_dwarf',
      name: 'Gravitationally Lensed Dwarf Star',
      type: 'CORE_REMNANT',
      realAppearance: 'Distant white dwarf star sheared by extreme gravitational lensing into a glowing horseshoe Einstein ring',
      color: 0xe0f2fe,
      emissiveColor: 0x38bdf8,
      radius: 95,
      initialOrbitRadius: 1700,
      orbitSpeed: 0.36,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.7,
      particleCount: 350,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Orbits near the photon sphere, its light distorted into relativistic optical particle arcs.',
      completionGuidance: 'Use the bright apex of the Einstein ring as your navigational crosshair to maintain track heading.',
    },
    element2: {
      id: 'e2_photonic_arc',
      name: 'Relativistic Photonic Arc',
      type: 'PLASMA_JET',
      realAppearance: 'Curving photonic light filament tracing the innermost stable circular photon orbit around the event horizon',
      color: 0x38bdf8,
      emissiveColor: 0xa855f7,
      radius: 160,
      initialOrbitRadius: 1500,
      orbitSpeed: 0.48,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.8,
      particleCount: 390,
      particleColor: 0xc084fc,
      occurrenceDescription: 'Revolves at light-speed boundary, casting glowing ultraviolet photon particles into space.',
      completionGuidance: 'Fly inside the shadow notch of the photonic arc to prevent cockpit HUD sensor wash-out.',
    },
    eventOccurrenceNarrative: 'The Lensed Dwarf Star and Photonic Arc intersect along the photon sphere boundary, creating a dazzling ring of lensed light that spaghettifies surrounding dust into radiant optical particle filaments.',
    completionStrategy: 'Align ship crosshairs with the dark null-node between both photonic arcs to bypass sensor glare.',
  },

  12: {
    eventIndex: 12,
    eventId: 'gravitational_lockdown',
    element1: {
      id: 'e1_transit_corridor',
      name: 'Alternate Transit Corridor Gamma',
      type: 'STRUCTURE',
      realAppearance: 'Tubular composite vacuum highway snapping into segmented arcs under gravitational strain',
      color: 0x1e293b,
      emissiveColor: 0x06b6d4,
      radius: 170,
      initialOrbitRadius: 1800,
      orbitSpeed: 0.22,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.65,
      particleCount: 300,
      particleColor: 0x22d3ee,
      occurrenceDescription: 'Snaps into three twisting segments that revolve in free-fall while shedding structural particles.',
      completionGuidance: 'Break off from the alternate branch and dive onto the central emergency conduit before the seal locks.',
    },
    element2: {
      id: 'e2_beacon_pylon',
      name: 'Magnetic Guidance Pylon 12',
      type: 'STRUCTURE',
      realAppearance: 'Illuminated cyan beacon pylon collapsing inward and discharging electromagnetic shielding bursts',
      color: 0x0f172a,
      emissiveColor: 0x3b82f6,
      radius: 80,
      initialOrbitRadius: 1600,
      orbitSpeed: 0.28,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.6,
      particleCount: 260,
      particleColor: 0x60a5fa,
      occurrenceDescription: 'Collapses toward Corridor Gamma, triggering a containment rupture that streams ionized particles inward.',
      completionGuidance: 'Activate your EMP discharge capacitor near Pylon 12 to unlock the emergency bypass gate.',
    },
    eventOccurrenceNarrative: 'Transit Corridor Gamma and Guidance Pylon 12 collide as gravitational lockdown seals the sector; collapsing frameworks revolve and spaghettify into glowing cyan particles rushing into the singularity.',
    completionStrategy: 'Veer hard right into the emergency evacuation spur before the collapsing pylon crushes the corridor entrance.',
  },

  13: {
    eventIndex: 13,
    eventId: 'accelerated_infall',
    element1: {
      id: 'e1_comet_c9',
      name: 'Captured Cometary Nucleus C/9',
      type: 'COMET',
      realAppearance: 'Dirty crystalline ice comet nucleus with boiling cyan volatile jets and glowing dust coma',
      color: 0x0284c7,
      emissiveColor: 0x38bdf8,
      radius: 110,
      initialOrbitRadius: 1750,
      orbitSpeed: 0.4,
      revolutionEccentricity: 0.7,
      collisionTimeRatio: 0.55,
      spaghettificationRate: 0.85,
      particleCount: 440,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Accelerates to 120 km/s on a steep infall spiral, outgassing thousands of spaghettified ice particles.',
      completionGuidance: 'Ride the expanding cometary vapor tail for a massive thrust multiplier.',
    },
    element2: {
      id: 'e2_cargo_atlas',
      name: 'Titan Ore Barge Atlas',
      type: 'STATION',
      realAppearance: 'Heavily armored industrial freighter buckling as its magnetic cargo containers tear loose',
      color: 0x475569,
      emissiveColor: 0xf59e0b,
      radius: 130,
      initialOrbitRadius: 1550,
      orbitSpeed: 0.46,
      revolutionEccentricity: 0.6,
      collisionTimeRatio: 0.55,
      spaghettificationRate: 0.8,
      particleCount: 380,
      particleColor: 0xfbbf24,
      occurrenceDescription: 'Collides with the cometary nucleus; cargo pods rupture and spaghettify into glowing ore particles.',
      completionGuidance: 'Dodge the scattering ore pods by barrel-rolling through the cometary vapor channel.',
    },
    eventOccurrenceNarrative: 'Comet C/9 and Ore Barge Atlas are sucked into the accelerated infall funnel, colliding in an explosion of ice and molten metal that revolves into a stretched particle filament flowing into the event horizon.',
    completionStrategy: 'Enter the cometary tail slipstream to gain +60 km/h escape velocity away from the accelerated infall vortex.',
  },

  14: {
    eventIndex: 14,
    eventId: 'complete_breakdown',
    element1: {
      id: 'e1_relay_tower',
      name: 'Sector Relay Matrix Tower',
      type: 'STRUCTURE',
      realAppearance: 'Fractured quantum communication spire disintegrating into thousands of structural trusses',
      color: 0x1e293b,
      emissiveColor: 0xec4899,
      radius: 150,
      initialOrbitRadius: 1650,
      orbitSpeed: 0.32,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.7,
      particleCount: 350,
      particleColor: 0xf472b6,
      occurrenceDescription: 'Lattice collapses sequentially, spraying glowing quantum communication particles into the void.',
      completionGuidance: 'Use the blinking red aviation beacons on the falling mast to identify the open transit gap.',
    },
    element2: {
      id: 'e2_fuel_depot',
      name: 'De-orbiting Promethium Depot',
      type: 'STATION',
      realAppearance: 'Spherical orbital fuel storage facility glowing with supercritical thermal runaway plasma',
      color: 0x991b1b,
      emissiveColor: 0xf87171,
      radius: 75,
      initialOrbitRadius: 1450,
      orbitSpeed: -0.38,
      revolutionEccentricity: 0.45,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 460,
      particleColor: 0xef4444,
      occurrenceDescription: 'Suffers catastrophic thermal detonation, creating an expanding fireball that spaghettifies into relativistic plasma.',
      completionGuidance: 'Boost past the fuel depot before its containment field timer reaches zero to escape the blast wave.',
    },
    eventOccurrenceNarrative: 'The collapsing Relay Matrix Tower strikes the de-orbiting Promethium Depot, producing a thermonuclear eruption whose fireball revolves rapidly and spaghettifies into glowing particle jets falling into the black hole.',
    completionStrategy: 'Execute a maximum-thrust sprint straight through the communication tower gap to outdistance the depot blast.',
  },

  15: {
    eventIndex: 15,
    eventId: 'singularity_awakening',
    element1: {
      id: 'e1_ergosphere_sheath',
      name: 'Inner Ergosphere Plasma Sheath',
      type: 'PLASMA_JET',
      realAppearance: 'Swirling toroidal sheath of violet and amber relativistic matter dragged by black hole rotation',
      color: 0x6b21a8,
      emissiveColor: 0xa855f7,
      radius: 200,
      initialOrbitRadius: 1400,
      orbitSpeed: 0.55,
      revolutionEccentricity: 0.15,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.9,
      particleCount: 500,
      particleColor: 0xd8b4fe,
      occurrenceDescription: 'Rotates at 0.6c, dragging spacetime and shredding any crossing object into fundamental particles.',
      completionGuidance: 'Skim the retrograde edge of the sheath to counter the extreme frame-dragging lateral pull.',
    },
    element2: {
      id: 'e2_quantum_vortex',
      name: 'Spacetime Quantum Vortex',
      type: 'GAS_CLOUD',
      realAppearance: 'Blinding white-cyan vortex filament tunneling into the gravitational singularity core',
      color: 0x06b6d4,
      emissiveColor: 0xffffff,
      radius: 120,
      initialOrbitRadius: 1200,
      orbitSpeed: 0.62,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.95,
      particleCount: 480,
      particleColor: 0x67e8f9,
      occurrenceDescription: 'Consumes surrounding matter streams, transforming them into spaghettified particle filaments disappearing past the horizon.',
      completionGuidance: 'Keep steering pinned 15 degrees against the vortex rotation to maintain track lock.',
    },
    eventOccurrenceNarrative: 'The Singularity Awakening expands the Ergosphere Plasma Sheath into the Quantum Vortex; revolving at extreme relativistic velocities, both entities spaghettify all orbital matter into blinding particle spirals.',
    completionStrategy: 'Surge along the outer static limit boundary to harvest frame-dragging kinetic assist without falling past the horizon.',
  },

  16: {
    eventIndex: 16,
    eventId: 'chrono_dilation_pulse',
    element1: {
      id: 'e1_chronos_ring',
      name: 'Relativistic Dilation Ring',
      type: 'RING_SEGMENT',
      realAppearance: 'Expanding concentric wave of distorted blue-shifted light where subjective time decelerates',
      color: 0x1d4ed8,
      emissiveColor: 0x60a5fa,
      radius: 180,
      initialOrbitRadius: 1550,
      orbitSpeed: 0.35,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.6,
      particleCount: 320,
      particleColor: 0x93c5fd,
      occurrenceDescription: 'Pulses outward every 2 seconds, slowing perceived movement of nearby debris particles.',
      completionGuidance: 'Time your thruster bursts during the dilation pulse wave to execute razor-sharp micro-adjustments.',
    },
    element2: {
      id: 'e2_temporal_buoy',
      name: 'Tachyon Chrono-Beacon Omega',
      type: 'STATION',
      realAppearance: 'Gyroscopic ring station with sapphire phase emitters rotating along competing temporal axes',
      color: 0x0369a1,
      emissiveColor: 0x38bdf8,
      radius: 60,
      initialOrbitRadius: 1350,
      orbitSpeed: -0.42,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.7,
      particleCount: 290,
      particleColor: 0x38bdf8,
      occurrenceDescription: 'Sheds crystalline tachyon particles as its chronological synchronization fails.',
      completionGuidance: 'Align craft clocks with Beacon Omega to maintain flight computer target predictions.',
    },
    eventOccurrenceNarrative: 'The Relativistic Dilation Ring washes over Chrono-Beacon Omega, causing its gyroscopic modules to revolve at differing temporal rates before spaghettifying into sapphire time-dilation particles.',
    completionStrategy: 'Utilize the momentary time-dilation slowdown to navigate the narrow chicane between both revolving elements.',
  },

  17: {
    eventIndex: 17,
    eventId: 'frame_dragging_torrent',
    element1: {
      id: 'e1_kerr_swirl',
      name: 'Kerr Metric Frame-Dragging Torrent',
      type: 'GAS_CLOUD',
      realAppearance: 'Swirling luminous indigo vortex where space itself is forced to rotate around the black hole spin axis',
      color: 0x4338ca,
      emissiveColor: 0x818cf8,
      radius: 220,
      initialOrbitRadius: 1450,
      orbitSpeed: 0.6,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.85,
      particleCount: 420,
      particleColor: 0xa5b4fc,
      occurrenceDescription: 'Pulls the entire local reference frame into an unyielding circular vortex of spaghettified dust.',
      completionGuidance: 'Lean your craft into the spin direction to ride the frame-dragging current rather than fighting it.',
    },
    element2: {
      id: 'e2_gyro_platform',
      name: 'Counter-Torque Gyro Platform',
      type: 'STATION',
      realAppearance: 'Heavy tetrahedral orbital anchor station with counter-rotating flywheel drums spinning at critical RPM',
      color: 0x312e81,
      emissiveColor: 0x6366f1,
      radius: 85,
      initialOrbitRadius: 1250,
      orbitSpeed: -0.48,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.8,
      particleCount: 360,
      particleColor: 0xc7d2fe,
      occurrenceDescription: 'Flywheels burst through the hull, revolving wildly before dissolving into glowing indigo particle ribbons.',
      completionGuidance: 'Draft in the hydrodynamic shadow of the Gyro Platform to avoid unrecoverable spin out.',
    },
    eventOccurrenceNarrative: 'The Kerr Metric Torrent engulfs the Gyro Platform; the immense frame-dragging torque shears the platform into spinning spaghettified ribbons of metal that spiral into the black hole at relativistic speed.',
    completionStrategy: 'Drift with the frame-dragging torrent around the Gyro Platform to emerge directly onto the exit straightaway.',
  },

  18: {
    eventIndex: 18,
    eventId: 'relativistic_beaming_sweep',
    element1: {
      id: 'e1_doppler_beam',
      name: 'Doppler-Boosted Relativistic Beam',
      type: 'PLASMA_JET',
      realAppearance: 'Blinding white-blue relativistic plasma searchlight sweeping across the sector with extreme Doppler brightness',
      color: 0x38bdf8,
      emissiveColor: 0xffffff,
      radius: 160,
      initialOrbitRadius: 1500,
      orbitSpeed: 0.68,
      revolutionEccentricity: 0.15,
      collisionTimeRatio: 0.45,
      spaghettificationRate: 0.9,
      particleCount: 500,
      particleColor: 0xe0f2fe,
      occurrenceDescription: 'Sweeps across the route every 3 seconds, emitting ionizing radiation particles that overload sensor grids.',
      completionGuidance: 'Duck behind track elevation barriers whenever the beam sweeps into your forward viewport.',
    },
    element2: {
      id: 'e2_mirror_shield',
      name: 'Super-Conducting Mirror Deflector',
      type: 'STRUCTURE',
      realAppearance: 'Parabolic diamond-coated reflector dish glowing with thermal ablation as it deflects the beam',
      color: 0x0284c7,
      emissiveColor: 0x38bdf8,
      radius: 95,
      initialOrbitRadius: 1300,
      orbitSpeed: 0.5,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.45,
      spaghettificationRate: 0.85,
      particleCount: 420,
      particleColor: 0xbae6fd,
      occurrenceDescription: 'Deflects the beam until its diamond coating vaporizes into thousands of shimmering spaghettified diamond particles.',
      completionGuidance: 'Stay sheltered behind the Mirror Deflector until its structural integrity warning flashes yellow.',
    },
    eventOccurrenceNarrative: 'The Relativistic Beam impacts the Mirror Deflector, incinerating its lattice into a blinding cone of diamond and plasma particles that revolve and stretch along the black hole gravitational gradient.',
    completionStrategy: 'Follow the shadows cast by the Mirror Deflector to traverse the sweep corridor unscathed.',
  },

  19: {
    eventIndex: 19,
    eventId: 'photon_sphere_inversion',
    element1: {
      id: 'e1_photon_orbit',
      name: 'Photon Sphere Boundary Shell',
      type: 'RING_SEGMENT',
      realAppearance: 'Luminous spherical shell at 1.5 Schwarzschild radii where trapped light loops infinitely',
      color: 0xfbbf24,
      emissiveColor: 0xffedd5,
      radius: 175,
      initialOrbitRadius: 1350,
      orbitSpeed: 0.72,
      revolutionEccentricity: 0.05,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.95,
      particleCount: 480,
      particleColor: 0xfef08a,
      occurrenceDescription: 'Inverts optical perspective so you see the rear of your own craft; sheds trapped light particles.',
      completionGuidance: 'Trust your forward inertial vector rather than optical reflections while crossing the photon sphere.',
    },
    element2: {
      id: 'e2_lensed_probe',
      name: 'Relativistic Recon Drone Nova',
      type: 'STATION',
      realAppearance: 'Sleek triangular titanium probe trapped in a closed photon orbit, mirrored infinite times',
      color: 0x475569,
      emissiveColor: 0xf59e0b,
      radius: 35,
      initialOrbitRadius: 1200,
      orbitSpeed: -0.65,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 380,
      particleColor: 0xfde047,
      occurrenceDescription: 'Revolves at circular photon velocity, breaking down into spaghettified optical sensor particles.',
      completionGuidance: 'Follow Drone Nova telemetry broadcast to distinguish true flight gates from optical mirages.',
    },
    eventOccurrenceNarrative: 'Drone Nova is trapped within the Photon Sphere Boundary Shell; optical inversion causes both to revolve in an infinite loop of optical echoes before collapsing into spaghettified light particle streams.',
    completionStrategy: 'Ignore the looping optical mirages and steer strictly along the primary track centerline waypoint.',
  },

  20: {
    eventIndex: 20,
    eventId: 'roche_disruption_cascade',
    element1: {
      id: 'e1_roche_moon',
      name: 'Icy Moonlet Ganymede-X',
      type: 'MOON',
      realAppearance: 'Crystalline nitrogen-ice moonlet breaking apart under tidal shear into majestic orbital rings',
      color: 0x38bdf8,
      emissiveColor: 0x0284c7,
      radius: 100,
      initialOrbitRadius: 1450,
      orbitSpeed: 0.38,
      revolutionEccentricity: 0.45,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 520,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Crosses the Roche limit; tidal forces disintegrate its icy mantle into millions of sparkling ring particles.',
      completionGuidance: 'Fly along the ice particle ring plane to reduce hull thermal friction during acceleration.',
    },
    element2: {
      id: 'e2_crystalline_belt',
      name: 'Crystalline Ice Fragment Belt',
      type: 'RING_SEGMENT',
      realAppearance: 'Dense band of shimmering blue-white ice spires and crystal plates revolving around the singularity',
      color: 0x0284c7,
      emissiveColor: 0xe0f2fe,
      radius: 150,
      initialOrbitRadius: 1300,
      orbitSpeed: -0.44,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.88,
      particleCount: 460,
      particleColor: 0xbae6fd,
      occurrenceDescription: 'Revolves in retrograde against Moonlet Ganymede-X, grinding ice chunks into fine spaghettified mist.',
      completionGuidance: 'Use your ship kinetic plow to shatter small crystal plates without losing forward velocity.',
    },
    eventOccurrenceNarrative: 'Moonlet Ganymede-X breaches its fluid Roche limit and disintegrates into the Crystalline Ice Belt; the binary collision pulverizes both bodies into an iridescent spaghettified particle ring funneling into the black hole.',
    completionStrategy: 'Carve through the fractured ice rift between Ganymede-X and the belt to exit the Roche danger zone.',
  },

  // Events 21 to 30
  21: {
    eventIndex: 21,
    eventId: 'magnetic_flux_eruption',
    element1: {
      id: 'e1_flux_tube',
      name: 'Twisted Magnetic Flux Tube',
      type: 'PLASMA_JET',
      realAppearance: 'Coiling corkscrew arch of emerald and cyan magnetic plasma erupting from the inner accretion disk',
      color: 0x10b981,
      emissiveColor: 0x34d399,
      radius: 170,
      initialOrbitRadius: 1400,
      orbitSpeed: 0.52,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.8,
      particleCount: 450,
      particleColor: 0x6ee7b7,
      occurrenceDescription: 'Twists into a high-energy kink instability, detonating into thousands of charged plasma particles.',
      completionGuidance: 'Align your shield polarity to green to convert magnetic flux hits into instant boost meter recharge.',
    },
    element2: {
      id: 'e2_containment_pylon',
      name: 'Super-Conducting Flux Pylon',
      type: 'STRUCTURE',
      realAppearance: 'Colossal containment tower with pulsing magnetic pinch coils discharging ionized arcs into space',
      color: 0x064e3b,
      emissiveColor: 0x059669,
      radius: 75,
      initialOrbitRadius: 1200,
      orbitSpeed: 0.45,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.75,
      particleCount: 380,
      particleColor: 0xa7f3d0,
      occurrenceDescription: 'Coils melt under flux overload, spraying spaghettified copper and superconductor particles inward.',
      completionGuidance: 'Draft in the magnetic vacuum behind the pylon base to avoid the coronal loop discharge.',
    },
    eventOccurrenceNarrative: 'The Magnetic Flux Tube snaps across the Super-Conducting Flux Pylon, triggering magnetic reconnection that vaporizes the structure and launches a spiral of spaghettified green plasma particles into the abyss.',
    completionStrategy: 'Charge through the reconnection eye at the center of the flux loop while the magnetic field is momentarily zeroed.',
  },

  22: {
    eventIndex: 22,
    eventId: 'polar_jet_discharge',
    element1: {
      id: 'e1_north_jet',
      name: 'Blandford-Znajek Relativistic Polar Jet',
      type: 'PLASMA_JET',
      realAppearance: 'Columnar relativistic jet of violet-magenta plasma erupting vertically from the black hole rotational pole',
      color: 0xa855f7,
      emissiveColor: 0xf43f5e,
      radius: 240,
      initialOrbitRadius: 1600,
      orbitSpeed: 0.2,
      revolutionEccentricity: 0.05,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.92,
      particleCount: 550,
      particleColor: 0xe879f9,
      occurrenceDescription: 'Erupts at 0.98c along the rotational axis, ejecting millions of relativistic particles into intergalactic space.',
      completionGuidance: 'Do not fly directly across the jet axis; utilize the lateral magnetic collimation ridge for safe passage.',
    },
    element2: {
      id: 'e2_harvester_platform',
      name: 'Orbital Jet Harvester Platform',
      type: 'STATION',
      realAppearance: 'Megastructure ring encircling the polar jet with antimatter intake funnels and glowing energy banks',
      color: 0x3b0764,
      emissiveColor: 0xc084fc,
      radius: 120,
      initialOrbitRadius: 1350,
      orbitSpeed: -0.3,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.88,
      particleCount: 420,
      particleColor: 0xd8b4fe,
      occurrenceDescription: 'Intake funnels overload, revolving in a catastrophic spin that dissolves into spaghettified particle ribbons.',
      completionGuidance: 'Fly through the intake funnel throat of the Harvester Platform before the containment field ruptures.',
    },
    eventOccurrenceNarrative: 'The Polar Jet erupts with immense relativistic power, incinerating the Harvester Platform; the binary interaction produces a helical plume of spaghettified magenta particles shooting thousands of kilometers outward.',
    completionStrategy: 'Execute a lateral dive along the magnetic collimation boundary of the Polar Jet to clear the sector.',
  },

  23: {
    eventIndex: 23,
    eventId: 'ergosphere_shear',
    element1: {
      id: 'e1_shear_ribbon',
      name: 'Relativistic Velocity Shear Ribbon',
      type: 'GAS_CLOUD',
      realAppearance: 'Hyper-turbulent ribbon of incandescent plasma shearing between differing orbital velocity zones',
      color: 0xd97706,
      emissiveColor: 0xfbbf24,
      radius: 150,
      initialOrbitRadius: 1350,
      orbitSpeed: 0.65,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 440,
      particleColor: 0xfde047,
      occurrenceDescription: 'Tears apart any material crossing its boundary with millions of tons of differential shear force.',
      completionGuidance: 'Align your velocity vector to match the ribbon speed precisely to eliminate destructive lateral friction.',
    },
    element2: {
      id: 'e2_mining_rig',
      name: 'Deep-Ergosphere Penrose Mining Rig',
      type: 'STATION',
      realAppearance: 'Heavy industrial refinery with carbon-carbide drill tethers extended toward the event horizon',
      color: 0x451a03,
      emissiveColor: 0xf59e0b,
      radius: 90,
      initialOrbitRadius: 1150,
      orbitSpeed: -0.58,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.92,
      particleCount: 410,
      particleColor: 0xfcd34d,
      occurrenceDescription: 'Tethers snap under shear, revolving in an uncontrolled spiral that spaghettifies into metallic particle clouds.',
      completionGuidance: 'Follow the severed tether line out of the high-shear zone toward the safe outer perimeter.',
    },
    eventOccurrenceNarrative: 'The Ergosphere Shear Ribbon catches the Penrose Mining Rig; the differential velocity rips the heavy refinery into spaghettified ribbons of molten carbide that revolve into the black hole accretion pool.',
    completionStrategy: 'Match your throttle to the exact velocity of the Shear Ribbon while dodging the spinning mining rig debris.',
  },

  24: {
    eventIndex: 24,
    eventId: 'hawking_radiation_cascade',
    element1: {
      id: 'e1_hawking_flash',
      name: 'Hawking Quantum Radiation Flare',
      type: 'PLASMA_JET',
      realAppearance: 'Microscopic quantum evaporation flare radiating blinding azure and white Cherenkov photons',
      color: 0x0284c7,
      emissiveColor: 0xffffff,
      radius: 130,
      initialOrbitRadius: 1300,
      orbitSpeed: 0.42,
      revolutionEccentricity: 0.15,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.85,
      particleCount: 460,
      particleColor: 0xe0f2fe,
      occurrenceDescription: 'Flashes rhythmically as primordial micro-singularities evaporate, emitting virtual particle pairs.',
      completionGuidance: 'Ride the Cherenkov shock front of the Hawking flash for an electromagnetic boost wave.',
    },
    element2: {
      id: 'e2_virtual_pair',
      name: 'Entangled Virtual Particle Stream',
      type: 'GAS_CLOUD',
      realAppearance: 'Curving trail of entangled positron-electron pairs glowing with ethereal cyan luminescence',
      color: 0x38bdf8,
      emissiveColor: 0x0ea5e9,
      radius: 80,
      initialOrbitRadius: 1100,
      orbitSpeed: 0.55,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 420,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Negative energy particles fall into the horizon while positive particles spaghettify outward into space.',
      completionGuidance: 'Collect the positive energy particle stream to replenish depleted ship battery cells.',
    },
    eventOccurrenceNarrative: 'Hawking Radiation Cascades trigger virtual pair separation at the event horizon; the positive particle stream revolves and spaghettifies outward into space, creating a breathtaking cyan halo of quantum light.',
    completionStrategy: 'Intercept the positive energy particle stream to recharge shield systems and boost out of the quantum storm.',
  },

  25: {
    eventIndex: 25,
    eventId: 'gravitational_redshift_blur',
    element1: {
      id: 'e1_redshift_bubble',
      name: 'Extreme Gravitational Redshift Envelope',
      type: 'GAS_CLOUD',
      realAppearance: 'Expanding deep crimson bubble where all visible light shifts down into infrared and radio wavelengths',
      color: 0x991b1b,
      emissiveColor: 0xef4444,
      radius: 190,
      initialOrbitRadius: 1400,
      orbitSpeed: 0.38,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.8,
      particleCount: 390,
      particleColor: 0xf87171,
      occurrenceDescription: 'Shifts all surrounding objects into deep spectral red, leaving behind trails of ruby spaghettified particles.',
      completionGuidance: 'Switch to infrared HUD targeting mode to maintain track visibility inside the redshift envelope.',
    },
    element2: {
      id: 'e2_infrared_beacon',
      name: 'Sub-Horizon Infrared Relay Alpha',
      type: 'STATION',
      realAppearance: 'Spherical navigational buoy broadcasting high-intensity pulsed laser guidance through the red haze',
      color: 0x7f1d1d,
      emissiveColor: 0xfca5a5,
      radius: 50,
      initialOrbitRadius: 1200,
      orbitSpeed: -0.45,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.82,
      particleCount: 340,
      particleColor: 0xfca5a5,
      occurrenceDescription: 'Revolves along the redshift boundary, discharging spaghettified ruby laser filaments.',
      completionGuidance: 'Follow the pulsing ruby laser beam emitted from Relay Alpha directly to the safe sector egress.',
    },
    eventOccurrenceNarrative: 'The Redshift Envelope consumes Relay Alpha; gravitational time dilation stretches its laser pulses into ruby particle ribbons that revolve slowly and spaghettify into the deep infrared horizon.',
    completionStrategy: 'Follow the red laser pulse path through the optical redshift haze to clear the sector safely.',
  },

  26: {
    eventIndex: 26,
    eventId: 'megastructure_bending',
    element1: {
      id: 'e1_dyson_arch',
      name: 'Orbital Ring Megastructure Segment',
      type: 'STRUCTURE',
      realAppearance: 'Hundreds-of-meters-long curved metallic highway spanning the horizon with glowing road markers',
      color: 0x334155,
      emissiveColor: 0x0284c7,
      radius: 200,
      initialOrbitRadius: 1500,
      orbitSpeed: 0.22,
      revolutionEccentricity: 0.15,
      collisionTimeRatio: 0.55,
      spaghettificationRate: 0.75,
      particleCount: 400,
      particleColor: 0x38bdf8,
      occurrenceDescription: 'Bends into an inverted hyperbolic curve under tidal strain before snapping into fractured road plates.',
      completionGuidance: 'Stay committed to the central asphalt lane while the outer shoulders flex and separate.',
    },
    element2: {
      id: 'e2_stabilizer_tower',
      name: 'Centrifugal Tension Counter-Tower',
      type: 'STRUCTURE',
      realAppearance: 'Monolithic reinforced concrete and steel support tower with severed tension cables waving in space',
      color: 0x1e293b,
      emissiveColor: 0xf97316,
      radius: 110,
      initialOrbitRadius: 1300,
      orbitSpeed: 0.26,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.55,
      spaghettificationRate: 0.8,
      particleCount: 370,
      particleColor: 0xfb923c,
      occurrenceDescription: 'Tumbles sideways onto the road deck, shattering into thousands of spaghettified structural particles.',
      completionGuidance: 'Perform an evasive chicane maneuver under the falling tower counter-weight to maintain momentum.',
    },
    eventOccurrenceNarrative: 'The Orbital Ring Segment bends beyond its material tolerance and collides with Counter-Tower; both megastructures revolve in structural agony, spaghettifying into millions of steel particles raining into the black hole.',
    completionStrategy: 'Slalom beneath the swaying tension cables of the counter-tower before the ring segment fractures.',
  },

  27: {
    eventIndex: 27,
    eventId: 'lunar_fracture_cataclysm',
    element1: {
      id: 'e1_silicate_themis',
      name: 'Silicate Moonlet Themis',
      type: 'MOON',
      realAppearance: 'Massive moon split into two halves by tidal stress, exposing its glowing orange molten core',
      color: 0x64748b,
      emissiveColor: 0xf97316,
      radius: 140,
      initialOrbitRadius: 1400,
      orbitSpeed: 0.32,
      revolutionEccentricity: 0.5,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.88,
      particleCount: 480,
      particleColor: 0xfbbf24,
      occurrenceDescription: 'Splits open along its equator; both hemispheres revolve around their mutual core before spaghettifying.',
      completionGuidance: 'Fly directly through the fiery chasm between both split halves of Themis to bypass the debris field.',
    },
    element2: {
      id: 'e2_iron_core',
      name: 'Exposed Metallic Core Fragment',
      type: 'CORE_REMNANT',
      realAppearance: 'Dense crystallized iron-nickel sphere glowing white-hot with intense magnetic flux ribbons',
      color: 0xf1f5f9,
      emissiveColor: 0xef4444,
      radius: 65,
      initialOrbitRadius: 1200,
      orbitSpeed: -0.42,
      revolutionEccentricity: 0.45,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.9,
      particleCount: 430,
      particleColor: 0xf87171,
      occurrenceDescription: 'Ejected at high speed, revolving in a tight death spiral while spraying liquid iron particles.',
      completionGuidance: 'Use the intense magnetic repulsion of the iron core to slingshot your craft into the exit tunnel.',
    },
    eventOccurrenceNarrative: 'Moonlet Themis fractures down to its core; the exposed iron core fragment and outer silicate crust revolve in a violent dance, spaghettifying into incandescent magma particles streaming toward the singularity.',
    completionStrategy: 'Dive straight through the glowing magma trench between both fracturing lunar hemispheres.',
  },

  28: {
    eventIndex: 28,
    eventId: 'gas_giant_stripping',
    element1: {
      id: 'e1_gas_envelope',
      name: 'Gas Giant Atmospheric Envelope',
      type: 'GAS_CLOUD',
      realAppearance: 'Vast swirling vortex of cyan, turquoise, and violet Jovian gas bands being stripped off the planet',
      color: 0x0284c7,
      emissiveColor: 0x06b6d4,
      radius: 260,
      initialOrbitRadius: 1550,
      orbitSpeed: 0.28,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 520,
      particleColor: 0x38bdf8,
      occurrenceDescription: 'Boils and elongates into a colossal Roche-lobe overflow streamer of spaghettified gas particles.',
      completionGuidance: 'Ride the outer gas atmospheric streamer to experience reduced aerodynamic drag and gain speed.',
    },
    element2: {
      id: 'e2_metallic_jupiter',
      name: 'Stripped Metallic Hydrogen Core',
      type: 'PLANET',
      realAppearance: 'Dense dark indigo planetary sphere glowing with intense internal dynamo lightning and auroral rings',
      color: 0x1e1b4b,
      emissiveColor: 0x4f46e5,
      radius: 110,
      initialOrbitRadius: 1300,
      orbitSpeed: 0.36,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.85,
      particleCount: 460,
      particleColor: 0x818cf8,
      occurrenceDescription: 'Revolves rapidly as its atmosphere is stripped away, trailing glowing metallic hydrogen particles.',
      completionGuidance: 'Avoid the intense auroral lightning bolts erupting from the metallic core poles.',
    },
    eventOccurrenceNarrative: 'The black hole tidal gravity strips the outer atmospheric envelope from the Gas Giant, leaving the bare metallic hydrogen core revolving alone as trillions of tons of gas spaghettify into the accretion disk.',
    completionStrategy: 'Surf along the turquoise gas overflow stream directly above the metallic core to escape the tidal funnel.',
  },

  29: {
    eventIndex: 29,
    eventId: 'auroral_tear',
    element1: {
      id: 'e1_curtain_aurora',
      name: 'Cosmic Magnetospheric Auroral Curtain',
      type: 'GAS_CLOUD',
      realAppearance: 'Towering shimmering emerald and violet curtain of ionized geomagnetic ribbons fluttering across space',
      color: 0x10b981,
      emissiveColor: 0xa855f7,
      radius: 200,
      initialOrbitRadius: 1400,
      orbitSpeed: 0.34,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.82,
      particleCount: 470,
      particleColor: 0x34d399,
      occurrenceDescription: 'Tears apart along geomagnetic lines, scattering glowing aurora particles like stardust.',
      completionGuidance: 'Follow the green auroral fold lines to navigate through the magnetic interference zone.',
    },
    element2: {
      id: 'e2_shield_collector',
      name: 'Orbital Magnetopause Collector',
      type: 'STATION',
      realAppearance: 'Spider-like orbital harvester with superconducting boom arms capturing auroral plasma energy',
      color: 0x064e3b,
      emissiveColor: 0x10b981,
      radius: 80,
      initialOrbitRadius: 1200,
      orbitSpeed: -0.4,
      revolutionEccentricity: 0.28,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.85,
      particleCount: 390,
      particleColor: 0x6ee7b7,
      occurrenceDescription: 'Collector arms snap under magnetic tension, revolving and spaghettifying into emerald particle sparks.',
      completionGuidance: 'Pass between the collector boom arms to supercharge your shield capacitors to 100%.',
    },
    eventOccurrenceNarrative: 'The Auroral Curtain tears open as the Magnetopause Collector collapses; revolving plasma ribbons spaghettify into glittering emerald and violet particles cascading toward the black hole.',
    completionStrategy: 'Glide straight through the center rift of the auroral curtain where magnetic turbulence is canceled.',
  },

  30: {
    eventIndex: 30,
    eventId: 'dark_tide',
    element1: {
      id: 'e1_dark_density',
      name: 'Non-Baryonic Dark Matter Tide',
      type: 'GAS_CLOUD',
      realAppearance: 'Subtle gravitational lensing distortion field bending starlight without emitting any optical light',
      color: 0x09090b,
      emissiveColor: 0x3b82f6,
      radius: 210,
      initialOrbitRadius: 1350,
      orbitSpeed: 0.4,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.88,
      particleCount: 420,
      particleColor: 0x60a5fa,
      occurrenceDescription: 'Creates an invisible gravitational drag wave, pulling objects inward with ghost-like tidal force.',
      completionGuidance: 'Watch your gravitation telemetry meter rather than eyes to anticipate dark matter pull vectors.',
    },
    element2: {
      id: 'e2_graviton_buoy',
      name: 'Graviton Sensor Array Delta',
      type: 'STATION',
      realAppearance: 'Luminescent spherical probe array emitting spherical pulse rings that illuminate the dark matter tide',
      color: 0x1e3a8a,
      emissiveColor: 0x60a5fa,
      radius: 65,
      initialOrbitRadius: 1150,
      orbitSpeed: -0.48,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.86,
      particleCount: 380,
      particleColor: 0x93c5fd,
      occurrenceDescription: 'Pulsing sonar rings reveal the invisible dark tide as the buoy dissolves into spaghettified blue particles.',
      completionGuidance: 'Follow the circular sonar wave ripples emitted by Array Delta to stay within the safe density channel.',
    },
    eventOccurrenceNarrative: 'The invisible Dark Matter Tide sweeps past Sensor Array Delta, lighting up in a wave of blue sensor particles as both revolve and spaghettify into the gravitational sink.',
    completionStrategy: 'Stay centered on Sensor Array Delta sonar pulses to avoid drifting into the dark matter gravity shear.',
  },

  // Events 31 to 40
  31: {
    eventIndex: 31,
    eventId: 'void_rift',
    element1: {
      id: 'e1_metric_rift',
      name: 'Spacetime Curvature Metric Rift',
      type: 'GAS_CLOUD',
      realAppearance: 'Pitch-black tear in the fabric of space surrounded by an intensely luminescent violet photonic halo',
      color: 0x000000,
      emissiveColor: 0xc084fc,
      radius: 170,
      initialOrbitRadius: 1300,
      orbitSpeed: 0.46,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.95,
      particleCount: 500,
      particleColor: 0xd8b4fe,
      occurrenceDescription: 'Acts as a pure gravitational vacuum, dragging all nearby debris into spaghettified particle filaments.',
      completionGuidance: 'Keep maximum thruster burn perpendicular to the rift to prevent your escape vector collapsing.',
    },
    element2: {
      id: 'e2_containment_arch',
      name: 'Quantum Containment Pylon Matrix',
      type: 'STRUCTURE',
      realAppearance: 'Triangular carbon-nanotube support frame attempting to brace the rift with sapphire forcefields',
      color: 0x1e1b4b,
      emissiveColor: 0x6366f1,
      radius: 95,
      initialOrbitRadius: 1100,
      orbitSpeed: 0.5,
      revolutionEccentricity: 0.25,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.9,
      particleCount: 430,
      particleColor: 0x818cf8,
      occurrenceDescription: 'Forcefields shatter like glass, revolving and spaghettifying into thousands of crystalline blue sparks.',
      completionGuidance: 'Pass under the crossbeam of the containment frame just as the forcefield cycles off.',
    },
    eventOccurrenceNarrative: 'The Metric Rift breaches the Containment Pylon Matrix, shattering forcefields into billions of spaghettified particles that revolve into the black void.',
    completionStrategy: 'Commit to full forward boost through the triangular frame before the metric rift collapses inward.',
  },

  32: {
    eventIndex: 32,
    eventId: 'multi_route_collapse',
    element1: {
      id: 'e1_route_bridge_a',
      name: 'Express Transit Viaduct Beta',
      type: 'STRUCTURE',
      realAppearance: 'Suspended dual-track maglev viaduct fracturing into segments and dropping into the void',
      color: 0x334155,
      emissiveColor: 0x0ea5e9,
      radius: 160,
      initialOrbitRadius: 1350,
      orbitSpeed: 0.24,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.8,
      particleCount: 400,
      particleColor: 0x38bdf8,
      occurrenceDescription: 'Pillars crumble as road slabs drop into free-fall, shedding spaghettified composite particles.',
      completionGuidance: 'Jump from the crumbling Viaduct Beta onto the lower emergency evacuation spur.',
    },
    element2: {
      id: 'e2_junction_tower',
      name: 'Multi-Route Junction Hub 4',
      type: 'STRUCTURE',
      realAppearance: 'Hexagonal switching tower with glowing directional green arrows spinning off its moorings',
      color: 0x1e293b,
      emissiveColor: 0x22c55e,
      radius: 85,
      initialOrbitRadius: 1150,
      orbitSpeed: -0.32,
      revolutionEccentricity: 0.3,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.85,
      particleCount: 360,
      particleColor: 0x4ade80,
      occurrenceDescription: 'Swings wildly and shears off, revolving into Viaduct Beta while spraying warning beacon particles.',
      completionGuidance: 'Follow the flashing green arrow on the falling junction tower to locate the only intact exit spur.',
    },
    eventOccurrenceNarrative: 'Transit Viaduct Beta and Junction Hub 4 collide in mid-air as the route network crumbles; both structures revolve and spaghettify into thousands of glowing road fragments falling into the black hole.',
    completionStrategy: 'Execute a timed hop off the falling edge of Viaduct Beta directly toward the green beacon of Junction Hub 4.',
  },

  33: {
    eventIndex: 33,
    eventId: 'dyson_ring_fracture',
    element1: {
      id: 'e1_dyson_segment',
      name: 'Titanium Dyson Ring Arch Alpha',
      type: 'RING_SEGMENT',
      realAppearance: 'Kilometer-long curved superstructure segment with glowing solar collection panels and cities',
      color: 0x475569,
      emissiveColor: 0xf59e0b,
      radius: 230,
      initialOrbitRadius: 1450,
      orbitSpeed: 0.35,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.88,
      particleCount: 500,
      particleColor: 0xfbbf24,
      occurrenceDescription: 'Snaps under hoop stress, curling inward into a giant spaghettified spiral of glowing metal particles.',
      completionGuidance: 'Fly through the open hollow structural tunnel inside the ring arch to maintain total cover.',
    },
    element2: {
      id: 'e2_stabilizer_pylon',
      name: 'Orbital Counter-Weight Pylon Zero',
      type: 'STRUCTURE',
      realAppearance: 'Massive tapered asteroid-mass anchor pylon tumbling end-over-end through the shattered ring gap',
      color: 0x1e293b,
      emissiveColor: 0xef4444,
      radius: 110,
      initialOrbitRadius: 1250,
      orbitSpeed: -0.42,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.52,
      spaghettificationRate: 0.85,
      particleCount: 420,
      particleColor: 0xf87171,
      occurrenceDescription: 'Tumbles across the ring breach, revolving chaotically before disintegrating into spaghettified stone particles.',
      completionGuidance: 'Time your sprint past the rotating anchor pylon when its long axis is oriented vertical.',
    },
    eventOccurrenceNarrative: 'Dyson Ring Arch Alpha snaps and strikes Counter-Weight Pylon Zero; the colossal collision shatters civilizations, revolving both monoliths into thousands of spaghettified particle arcs raining into the singularity.',
    completionStrategy: 'Cruise inside the hollow structural conduit of Dyson Ring Arch Alpha to bypass the tumbling anchor pylon.',
  },

  34: {
    eventIndex: 34,
    eventId: 'singularity_tide',
    element1: {
      id: 'e1_tidal_spike',
      name: 'Relativistic Singularity Gravitational Spike',
      type: 'GAS_CLOUD',
      realAppearance: 'Concentrated jet of warped spacetime stretching outward like a black spear with a razor-thin violet edge',
      color: 0x020617,
      emissiveColor: 0xa855f7,
      radius: 180,
      initialOrbitRadius: 1250,
      orbitSpeed: 0.55,
      revolutionEccentricity: 0.45,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.95,
      particleCount: 520,
      particleColor: 0xc084fc,
      occurrenceDescription: 'Pierces through the flight corridor, stretching matter into micro-thin spaghettified filaments in milliseconds.',
      completionGuidance: 'Counter-steer against the spike direction vector to stay outside its lethal tidal radius.',
    },
    element2: {
      id: 'e2_sacrificial_drone',
      name: 'Graviton Deflector Drone Titan',
      type: 'STATION',
      realAppearance: 'Heavily armored triangular drone projecting a counter-gravitational shield wedge against the spike',
      color: 0x1e1b4b,
      emissiveColor: 0x38bdf8,
      radius: 70,
      initialOrbitRadius: 1050,
      orbitSpeed: 0.6,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.92,
      particleCount: 450,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Shield collapses as it collides with the spike, dissolving into millions of spaghettified sapphire particles.',
      completionGuidance: 'Hide in the conical deflection shadow directly behind Drone Titan to survive the tidal spike impact.',
    },
    eventOccurrenceNarrative: 'The Singularity Gravitational Spike impales Drone Titan; the deflector drone explodes into sapphire particles that revolve in an elongated vortex and spaghettify into the black hole horizon.',
    completionStrategy: 'Stay tucked directly inside Drone Titan protective wake until the gravitational spike dissolves.',
  },

  35: {
    eventIndex: 35,
    eventId: 'cosmic_dust_veil',
    element1: {
      id: 'e1_pulverized_cloud',
      name: 'Cosmic Pulverization Particulate Cloud',
      type: 'GAS_CLOUD',
      realAppearance: 'Vast opaque black and charcoal dust storm blotting out distant stars, illuminated only by accretion glow',
      color: 0x18181b,
      emissiveColor: 0xf97316,
      radius: 280,
      initialOrbitRadius: 1350,
      orbitSpeed: 0.32,
      revolutionEccentricity: 0.2,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.85,
      particleCount: 550,
      particleColor: 0xfb923c,
      occurrenceDescription: 'Envelops the flight sector, reducing visibility to zero while scattering glowing orange dust particles.',
      completionGuidance: 'Rely on HUD holographic track waypoints and navigation arrows to steer through the dark cloud.',
    },
    element2: {
      id: 'e2_navigation_buoy',
      name: 'High-Luminance Radar Beacon 35',
      type: 'STATION',
      realAppearance: 'Floating tetrahedral lighthouse buoy with high-power yellow strobe lights cutting through the particulate veil',
      color: 0xca8a04,
      emissiveColor: 0xfde047,
      radius: 60,
      initialOrbitRadius: 1150,
      orbitSpeed: -0.38,
      revolutionEccentricity: 0.28,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.88,
      particleCount: 400,
      particleColor: 0xfef08a,
      occurrenceDescription: 'Flashes amber strobe beams through the dust veil before revolving into the black hole infall stream.',
      completionGuidance: 'Fly from one yellow strobe flash to the next to maintain true racing line through the dust storm.',
    },
    eventOccurrenceNarrative: 'The Cosmic Dust Veil swallows Radar Beacon 35; amber strobe beams sweep through billions of revolving, spaghettified dust particles that funnel relentlessly toward the event horizon.',
    completionStrategy: 'Lock eyes onto Beacon 35 flashing yellow strobe and use its radar vector to punch through the dust veil.',
  },

  36: {
    eventIndex: 36,
    eventId: 'collision_cascade',
    element1: {
      id: 'e1_debris_flock_a',
      name: 'Infalling Hull Plate Swarm Alpha',
      type: 'ASTEROID',
      realAppearance: 'Cluster of jagged titanium and ceramic hull plates glowing red-hot from atmospheric and tidal friction',
      color: 0x57534e,
      emissiveColor: 0xef4444,
      radius: 120,
      initialOrbitRadius: 1300,
      orbitSpeed: 0.52,
      revolutionEccentricity: 0.55,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.9,
      particleCount: 480,
      particleColor: 0xf87171,
      occurrenceDescription: 'Revolves in decaying orbit, crossing paths with Swarm Beta in a catastrophic secondary collision.',
      completionGuidance: 'Dive beneath the collision plane 2 seconds prior to impact to dodge the horizontal shrapnel spray.',
    },
    element2: {
      id: 'e2_debris_flock_b',
      name: 'Infalling Hull Plate Swarm Beta',
      type: 'ASTEROID',
      realAppearance: 'Cluster of twisted structural trusses and shattered photovoltaic panels traveling on counter-orbit',
      color: 0x44403c,
      emissiveColor: 0xf59e0b,
      radius: 110,
      initialOrbitRadius: 1100,
      orbitSpeed: -0.58,
      revolutionEccentricity: 0.5,
      collisionTimeRatio: 0.48,
      spaghettificationRate: 0.92,
      particleCount: 460,
      particleColor: 0xfbbf24,
      occurrenceDescription: 'Collides with Swarm Alpha, generating a cascade of thousands of spaghettified molten metal sparks.',
      completionGuidance: 'Follow the empty wake carved behind Swarm Beta to slip through the cascade envelope.',
    },
    eventOccurrenceNarrative: 'Hull Plate Swarms Alpha and Beta collide in a catastrophic cascade near the ISCO boundary; kinetic energy converts to a thermal flash as millions of fragments revolve and spaghettify into particle filaments.',
    completionStrategy: 'Pitch downward through the low-altitude gap beneath both colliding swarms before the shrapnel cloud expands.',
  },

  37: {
    eventIndex: 37,
    eventId: 'last_stable_orbits',
    element1: {
      id: 'e1_citadel_ruin',
      name: 'Shattered Megacity Spire Ruin',
      type: 'STRUCTURE',
      realAppearance: 'Ruins of a fallen space civilization: shattered towers, sky-bridges, and flickering city grids',
      color: 0x334155,
      emissiveColor: 0x38bdf8,
      radius: 180,
      initialOrbitRadius: 1200,
      orbitSpeed: 0.45,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.92,
      particleCount: 520,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Revolves on the last stable circular orbit, crumbling floor-by-floor into spaghettified particle streams.',
      completionGuidance: 'Fly through the central plaza canyon of the ruined megacity to shield against external tidal shear.',
    },
    element2: {
      id: 'e2_last_station',
      name: 'Final Orbital Bastion Prometheus',
      type: 'STATION',
      realAppearance: 'Armored spherical fortress station firing its final emergency thrusters against the inward pull',
      color: 0x1e293b,
      emissiveColor: 0xf97316,
      radius: 95,
      initialOrbitRadius: 1000,
      orbitSpeed: -0.52,
      revolutionEccentricity: 0.35,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.95,
      particleCount: 470,
      particleColor: 0xfb923c,
      occurrenceDescription: 'Thrusters fail, sending Bastion Prometheus into Spire Ruin; both revolve into spaghettified rubble.',
      completionGuidance: 'Ride the shockwave of Prometheus thruster failure for a final surge of forward acceleration.',
    },
    eventOccurrenceNarrative: 'The Megacity Spire Ruin and Bastion Prometheus lose their last stable orbits, colliding and revolving together as civilization final ruins spaghettify into glowing particle streams plunging into the abyss.',
    completionStrategy: 'Thread the needle between the collapsing skyscraper spires of the ruin toward the evacuation tower sanctuary.',
  },

  38: {
    eventIndex: 38,
    eventId: 'evacuation_corridor_collapse',
    element1: {
      id: 'e1_final_runway',
      name: 'Terminal Evacuation Runway Spur',
      type: 'STRUCTURE',
      realAppearance: 'Elevated runway with glowing amber runway lights dissolving sequentially right behind the player craft',
      color: 0x0f172a,
      emissiveColor: 0x06b6d4,
      radius: 150,
      initialOrbitRadius: 1100,
      orbitSpeed: 0.3,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.95,
      particleCount: 500,
      particleColor: 0x22d3ee,
      occurrenceDescription: 'Collapses like falling dominoes right at your exhaust trail, vaporizing into cyan spaghettified particles.',
      completionGuidance: 'Keep throttle pinned at 100%; never touch the brakes on the final runway spur.',
    },
    element2: {
      id: 'e2_shelter_tower',
      name: 'Evacuation Tower Sanctuary Blast Doors',
      type: 'STRUCTURE',
      realAppearance: 'Reinforced bunker fortress with massive hydraulic blast doors and green guidance landing lights',
      color: 0x022c22,
      emissiveColor: 0x22c55e,
      radius: 130,
      initialOrbitRadius: 900,
      orbitSpeed: 0.25,
      revolutionEccentricity: 0.05,
      collisionTimeRatio: 0.6,
      spaghettificationRate: 0.6,
      particleCount: 350,
      particleColor: 0x4ade80,
      occurrenceDescription: 'Shines beacon lights across the collapsing void, hydraulic blast doors cycling down to seal.',
      completionGuidance: 'Aim directly for the center green landing light array inside the shelter entrance hangar.',
    },
    eventOccurrenceNarrative: 'The Terminal Evacuation Runway collapses into spaghettified particle filaments right behind you as the Evacuation Tower Sanctuary beckons ahead with blazing green beacon arrays.',
    completionStrategy: 'Engage full booster burn straight through the closing blast doors of the Evacuation Tower Sanctuary.',
  },

  39: {
    eventIndex: 39,
    eventId: 'final_cosmic_compression',
    element1: {
      id: 'e1_converging_stars',
      name: 'Gravitationally Compressed Starfield Veil',
      type: 'GAS_CLOUD',
      realAppearance: 'Entire celestial vault compressed into a blinding blue Einstein funnel pointing into the singularity',
      color: 0x1e1b4b,
      emissiveColor: 0x38bdf8,
      radius: 220,
      initialOrbitRadius: 900,
      orbitSpeed: 0.7,
      revolutionEccentricity: 0.5,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 0.98,
      particleCount: 580,
      particleColor: 0x7dd3fc,
      occurrenceDescription: 'Stars stretch into curved arcs, converging at light speed and spaghettifying into brilliant particle rays.',
      completionGuidance: 'Inside the secured vault: witness the universal compression through heavy blast door periscopes.',
    },
    element2: {
      id: 'e2_infall_funnel',
      name: 'Universal Infall Singularity Funnel',
      type: 'PLASMA_JET',
      realAppearance: 'Towering gravitational funnel where all surrounding matter accelerates at 0.99c into the event horizon',
      color: 0x000000,
      emissiveColor: 0xa855f7,
      radius: 170,
      initialOrbitRadius: 750,
      orbitSpeed: 0.85,
      revolutionEccentricity: 0.4,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 1.0,
      particleCount: 600,
      particleColor: 0xc084fc,
      occurrenceDescription: 'Revolves at extreme relativistic speed, consuming all remaining universe matter into the singularity.',
      completionGuidance: 'Ensure all four hydraulic landing clamps are locked to anchor the craft against extreme metric compression.',
    },
    eventOccurrenceNarrative: 'All remaining matter of the cosmos converges into the Universal Infall Singularity Funnel; stars revolve and stretch into infinite spaghettified particle filaments plunging into the singularity core.',
    completionStrategy: 'Engage hydraulic clamps and seal reactor core to ride out the universal metric compression from the safety vault.',
  },

  40: {
    eventIndex: 40,
    eventId: 'absolute_cosmic_end',
    element1: {
      id: 'e1_singularity_core',
      name: 'The Persistent Supermassive Singularity',
      type: 'CORE_REMNANT',
      realAppearance: 'The absolute infinitely dense singularity sphere, completely black, warping all space and time around it',
      color: 0x000000,
      emissiveColor: 0x000000,
      radius: 140,
      initialOrbitRadius: 0,
      orbitSpeed: 0,
      revolutionEccentricity: 0,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 1.0,
      particleCount: 650,
      particleColor: 0x020617,
      occurrenceDescription: 'The final, eternal center of the universe. All matter has collapsed into its dark, silent horizon.',
      completionGuidance: 'You have survived the 40 events of the cosmic catastrophe. The universe has collapsed into silence.',
    },
    element2: {
      id: 'e2_dark_pulse',
      name: 'Dark Gravitational Implosion Pulse',
      type: 'GAS_CLOUD',
      realAppearance: 'Expanding dark shockwave of pure gravitation (no fire, no white flash): sudden silence -> deep boom -> darkness',
      color: 0x020617,
      emissiveColor: 0x0f172a,
      radius: 300,
      initialOrbitRadius: 300,
      orbitSpeed: 0.9,
      revolutionEccentricity: 0.1,
      collisionTimeRatio: 0.5,
      spaghettificationRate: 1.0,
      particleCount: 600,
      particleColor: 0x1e293b,
      occurrenceDescription: 'Revolves and implodes inward in pure silence, terminating all sound and light into the absolute black screen.',
      completionGuidance: 'Mission accomplished: complete evacuation success. The persistent black hole remains eternal.',
    },
    eventOccurrenceNarrative: 'The final astrophysical collapse: no white flash, no Hollywood fireball. Pure dark gravitational implosion, sudden absolute silence, a deep cosmic boom, and transition to the eternal singularity.',
    completionStrategy: 'Remain secure inside the underground vault as the universe collapses outside into total, peaceful silence.',
  },
};
