import { GameMode } from '../../types';
import { ModeFinishCinematicConfig } from './routeCinematicTypes';

export const MODE_FINISH_CONFIGS: Partial<Record<GameMode, ModeFinishCinematicConfig>> = {
  SINGULARITY_RUN: {
    modeId: 'SINGULARITY_RUN',
    title: 'SINGULARITY ESCAPED',
    subtitle: 'EVENT HORIZON CLEARED // TIME DILATION COMPENSATED',
    victoryMessage: 'GRAVITATIONAL VORTEX CONQUERED — ESCAPE VELOCITY ACHIEVED',
    particleColor: 0x9933ff,
    totalDurationSec: 5.5,
    shots: [
      {
        durationSec: 2.0,
        cameraStartOffset: [0, -2, -10],
        cameraEndOffset: [6, 4, -14],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1.5, 15],
        fovStart: 75,
        fovEnd: 55,
        timeScale: 0.35,
      },
      {
        durationSec: 2.0,
        cameraStartOffset: [-12, 6, -8],
        cameraEndOffset: [10, 8, 12],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 60,
        fovEnd: 50,
        timeScale: 0.5,
      },
      {
        durationSec: 1.5,
        cameraStartOffset: [0, 2, 16],
        cameraEndOffset: [0, 5, 24],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 65,
        timeScale: 0.8,
      },
    ],
  },

  NEON_CIRCUIT: {
    modeId: 'NEON_CIRCUIT',
    title: 'GRAND PRIX PODIUM',
    subtitle: 'NEON SECTOR DOMINATED // CHECKERED ARCH CLEARED',
    victoryMessage: 'URBAN APEX RECORD SHATTERED — CLEAN METROPOLIS TRIUMPH',
    particleColor: 0x00f0ff,
    totalDurationSec: 5.2,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [-8, 2, -6],
        cameraEndOffset: [8, 3, -12],
        lookAtStartOffset: [0, 1, 5],
        lookAtEndOffset: [0, 1, 10],
        fovStart: 68,
        fovEnd: 58,
        timeScale: 0.4,
      },
      {
        durationSec: 2.0,
        cameraStartOffset: [12, 5, 0],
        cameraEndOffset: [-12, 7, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 52,
        timeScale: 0.6,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, -1, 12],
        cameraEndOffset: [0, 4, 20],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 55,
        fovEnd: 65,
        timeScale: 0.9,
      },
    ],
  },

  ASTEROID_RUN: {
    modeId: 'ASTEROID_RUN',
    title: 'BELT RUN SURVIVED',
    subtitle: 'DEEP SPACE MINERAL MATRIX CLEARED // ZERO CRITICAL BREACHES',
    victoryMessage: 'ASTEROID CHAOS OUTRUN — HIGH-G TRAJECTORY SECURED',
    particleColor: 0xffaa00,
    totalDurationSec: 5.0,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [0, 8, -14],
        cameraEndOffset: [0, 2, -18],
        lookAtStartOffset: [0, 1, 20],
        lookAtEndOffset: [0, 1, 25],
        fovStart: 72,
        fovEnd: 60,
        timeScale: 0.35,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-14, 2, 4],
        cameraEndOffset: [14, 6, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 60,
        fovEnd: 52,
        timeScale: 0.55,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, 3, 14],
        cameraEndOffset: [0, 8, 22],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 52,
        fovEnd: 64,
        timeScale: 0.85,
      },
    ],
  },

  WORMHOLE_EXPRESS: {
    modeId: 'WORMHOLE_EXPRESS',
    title: 'TRANS-DIMENSIONAL EXIT',
    subtitle: 'SUBSPACE MANIFOLD EXHAUSTED // SPATIO-TEMPORAL RE-ENTRY LOCKED',
    victoryMessage: 'WARP-TUNNEL TRAVERSED AT RECORD DRIFT COEFFICIENT',
    particleColor: 0xcc00ff,
    totalDurationSec: 5.4,
    shots: [
      {
        durationSec: 2.0,
        cameraStartOffset: [0, -3, -12],
        cameraEndOffset: [-6, 3, -16],
        lookAtStartOffset: [0, 1, 15],
        lookAtEndOffset: [0, 1, 20],
        fovStart: 80,
        fovEnd: 58,
        timeScale: 0.3,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [10, 4, -4],
        cameraEndOffset: [-10, 8, 10],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 50,
        timeScale: 0.6,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 2, 14],
        cameraEndOffset: [0, 6, 26],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 70,
        timeScale: 0.9,
      },
    ],
  },

  SOLAR_STORM: {
    modeId: 'SOLAR_STORM',
    title: 'SOLAR CORONA OUTRUN',
    subtitle: 'THERMAL SHIELDS HELD // CORONAL MASS EJECTION AVERTED',
    victoryMessage: 'STELLAR FLUX SURVIVED — MAXIMUM HEAT COEFFICIENT WITHSTOOD',
    particleColor: 0xff3300,
    totalDurationSec: 5.2,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [8, -1, -10],
        cameraEndOffset: [-8, 4, -15],
        lookAtStartOffset: [0, 1, 12],
        lookAtEndOffset: [0, 1, 16],
        fovStart: 70,
        fovEnd: 56,
        timeScale: 0.35,
      },
      {
        durationSec: 2.0,
        cameraStartOffset: [-12, 5, 2],
        cameraEndOffset: [12, 7, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 56,
        fovEnd: 50,
        timeScale: 0.55,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, 3, 14],
        cameraEndOffset: [0, 7, 24],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 65,
        timeScale: 0.9,
      },
    ],
  },

  GRAVITY_FREE: {
    modeId: 'GRAVITY_FREE',
    title: 'ZERO-G FLUIDITY MASTERED',
    subtitle: 'ORBITAL DYNAMICS BALANCED // INERTIAL CONTROL PERFECTED',
    victoryMessage: 'WEIGHTLESS CENTRIFUGAL VICTORY ACHIEVED',
    particleColor: 0x33ffff,
    totalDurationSec: 5.0,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [0, 6, -12],
        cameraEndOffset: [6, -3, -16],
        lookAtStartOffset: [0, 0, 8],
        lookAtEndOffset: [0, 1, 12],
        fovStart: 66,
        fovEnd: 56,
        timeScale: 0.4,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [14, 2, -2],
        cameraEndOffset: [-14, 5, 6],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 56,
        fovEnd: 50,
        timeScale: 0.6,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, 4, 12],
        cameraEndOffset: [0, 8, 20],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 62,
        timeScale: 0.85,
      },
    ],
  },

  PLASMA_STORM: {
    modeId: 'PLASMA_STORM',
    title: 'PLASMA MATRIX WEATHERED',
    subtitle: 'ION DISCHARGE GROUNDED // ELECTROMAGNETIC CORE STABILIZED',
    victoryMessage: 'STORM CELL EXHAUSTED — LIGHTNING ARCS DISSIPATED',
    particleColor: 0xaa00ff,
    totalDurationSec: 5.2,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [-10, 2, -10],
        cameraEndOffset: [10, 4, -14],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1, 15],
        fovStart: 72,
        fovEnd: 58,
        timeScale: 0.35,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [8, 7, -2],
        cameraEndOffset: [-8, 5, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 50,
        timeScale: 0.55,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 1, 14],
        cameraEndOffset: [0, 6, 22],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 66,
        timeScale: 0.85,
      },
    ],
  },

  SKYLINE_RUSH: {
    modeId: 'SKYLINE_RUSH',
    title: 'METROPOLIS CROWN SECURED',
    subtitle: 'SKYWAY CORRIDORS DOMINATED // URBAN PINNACLE CONQUERED',
    victoryMessage: 'SUPERSTRUCTURE HIGH-RISE CANYONS SWEPT CLEAN',
    particleColor: 0x00e5ff,
    totalDurationSec: 5.1,
    shots: [
      {
        durationSec: 1.7,
        cameraStartOffset: [0, -2, -12],
        cameraEndOffset: [5, 3, -15],
        lookAtStartOffset: [0, 1, 8],
        lookAtEndOffset: [0, 1, 14],
        fovStart: 68,
        fovEnd: 58,
        timeScale: 0.4,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-12, 6, 0],
        cameraEndOffset: [12, 4, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 52,
        timeScale: 0.6,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 2, 12],
        cameraEndOffset: [0, 7, 22],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 52,
        fovEnd: 64,
        timeScale: 0.9,
      },
    ],
  },

  DEBRIS_SURVIVAL: {
    modeId: 'DEBRIS_SURVIVAL',
    title: 'DERELICT GRAVEYARD OUTRUN',
    subtitle: 'WRECKAGE FIELD HAZARDS CLEARED // HULL INTEGRITY PRESERVED',
    victoryMessage: 'DEBRIS COLLISION AVOIDANCE MATRIX EXCELLENT',
    particleColor: 0xff6600,
    totalDurationSec: 5.0,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [6, 4, -12],
        cameraEndOffset: [-6, 2, -16],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1, 15],
        fovStart: 70,
        fovEnd: 58,
        timeScale: 0.35,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-10, 5, 2],
        cameraEndOffset: [10, 7, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 50,
        timeScale: 0.55,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, 2, 14],
        cameraEndOffset: [0, 6, 24],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 64,
        timeScale: 0.85,
      },
    ],
  },

  QUANTUM_TIME_TRIAL: {
    modeId: 'QUANTUM_TIME_TRIAL',
    title: 'TEMPORAL GHOST CRUSHED',
    subtitle: 'CHRONO-SPLIT RECORD SHATTERED // ABSOLUTE MINIMUM TIME ACHIEVED',
    victoryMessage: 'CHRONOMETRIC PARADOX AVERTED — APEX LAP TIME LOCKED',
    particleColor: 0x00ff88,
    totalDurationSec: 5.3,
    shots: [
      {
        durationSec: 1.9,
        cameraStartOffset: [0, -1, -14],
        cameraEndOffset: [4, 2, -18],
        lookAtStartOffset: [0, 1, 12],
        lookAtEndOffset: [0, 1, 16],
        fovStart: 74,
        fovEnd: 56,
        timeScale: 0.3,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-12, 4, 0],
        cameraEndOffset: [12, 6, 10],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 56,
        fovEnd: 48,
        timeScale: 0.5,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 3, 15],
        cameraEndOffset: [0, 8, 25],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 48,
        fovEnd: 65,
        timeScale: 0.85,
      },
    ],
  },

  ENERGY_HEIST: {
    modeId: 'ENERGY_HEIST',
    title: 'CARGO VAULT SECURED',
    subtitle: 'PAYLOAD TRANSMISSION COMPLETE // PATROL PERIMETER EVADED',
    victoryMessage: 'ENERGY SYPHON EXTRACTION VERIFIED — CLEAN GETAWAY',
    particleColor: 0xff0055,
    totalDurationSec: 5.1,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [-6, 3, -10],
        cameraEndOffset: [6, 2, -14],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1, 15],
        fovStart: 68,
        fovEnd: 58,
        timeScale: 0.4,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [10, 5, 2],
        cameraEndOffset: [-10, 7, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 52,
        timeScale: 0.6,
      },
      {
        durationSec: 1.5,
        cameraStartOffset: [0, 2, 12],
        cameraEndOffset: [0, 5, 22],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 52,
        fovEnd: 64,
        timeScale: 0.9,
      },
    ],
  },

  DRONE_ASSAULT: {
    modeId: 'DRONE_ASSAULT',
    title: 'SWARM DEFENSE CRUSHED',
    subtitle: 'TARGET LOCKS EVADED // INTERCEPTOR NETWORK OVERRIDDEN',
    victoryMessage: 'HOSTILE PATROLS NEUTRALIZED — PERIMETER BREACH COMPLETED',
    particleColor: 0xff0033,
    totalDurationSec: 5.2,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [0, 5, -14],
        cameraEndOffset: [6, 2, -18],
        lookAtStartOffset: [0, 1, 12],
        lookAtEndOffset: [0, 1, 18],
        fovStart: 72,
        fovEnd: 58,
        timeScale: 0.35,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-12, 4, 4],
        cameraEndOffset: [12, 6, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 50,
        timeScale: 0.55,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 3, 15],
        cameraEndOffset: [0, 7, 24],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 65,
        timeScale: 0.85,
      },
    ],
  },

  COLLAPSING_TRACK: {
    modeId: 'COLLAPSING_TRACK',
    title: 'CHASM LEAP EXECUTED',
    subtitle: 'SUBSTRUCTURE DISINTEGRATION SURVIVED // ABYSS EVADED',
    victoryMessage: 'CATACLYSMIC FALL DISREGARDED — APEX RECOVERY RECORD',
    particleColor: 0xffaa00,
    totalDurationSec: 5.3,
    shots: [
      {
        durationSec: 1.9,
        cameraStartOffset: [0, -3, -12],
        cameraEndOffset: [-6, 4, -16],
        lookAtStartOffset: [0, 1, 14],
        lookAtEndOffset: [0, 1, 20],
        fovStart: 75,
        fovEnd: 58,
        timeScale: 0.3,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [12, 6, -2],
        cameraEndOffset: [-12, 8, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 50,
        timeScale: 0.55,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 2, 14],
        cameraEndOffset: [0, 6, 26],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 66,
        timeScale: 0.85,
      },
    ],
  },

  RING_RUNNER: {
    modeId: 'RING_RUNNER',
    title: 'RESONANCE MATRIX 100%',
    subtitle: 'QUANTUM GATES ALIGNED // HARMONIC VELOCITY MAXIMIZED',
    victoryMessage: 'ALL RESONANCE ARCS SYNCED — PERFECT GATE VELOCITY',
    particleColor: 0x00f0ff,
    totalDurationSec: 5.0,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [-8, 2, -12],
        cameraEndOffset: [8, 3, -16],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1, 15],
        fovStart: 70,
        fovEnd: 58,
        timeScale: 0.4,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [12, 4, 0],
        cameraEndOffset: [-12, 6, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 52,
        timeScale: 0.6,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, 3, 12],
        cameraEndOffset: [0, 7, 20],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 52,
        fovEnd: 64,
        timeScale: 0.85,
      },
    ],
  },

  HYPERSPACE_SPRINT: {
    modeId: 'HYPERSPACE_SPRINT',
    title: 'LIGHTSPEED BARRIER CRUSHED',
    subtitle: 'TACHYON OVERDRIVE CONCLUDED // MAXIMUM HYPER-VELOCITY RECORD',
    victoryMessage: 'TRANSLUMINAL DRIFT LOCKED — APEX FINISH ARCH CROSSED',
    particleColor: 0x00ffff,
    totalDurationSec: 5.4,
    shots: [
      {
        durationSec: 2.0,
        cameraStartOffset: [0, -2, -14],
        cameraEndOffset: [4, 3, -18],
        lookAtStartOffset: [0, 1, 15],
        lookAtEndOffset: [0, 1, 22],
        fovStart: 82,
        fovEnd: 58,
        timeScale: 0.28,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-14, 5, 2],
        cameraEndOffset: [14, 7, 10],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 48,
        timeScale: 0.5,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 2, 16],
        cameraEndOffset: [0, 6, 26],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 48,
        fovEnd: 68,
        timeScale: 0.9,
      },
    ],
  },

  RIVAL_DUEL: {
    modeId: 'RIVAL_DUEL',
    title: 'RIVAL DETHRONED',
    subtitle: 'NEMESIS DRIFT CONTEST WON // SUPREME ACE STATUS ESTABLISHED',
    victoryMessage: 'HEAD-TO-HEAD TACTICAL APEX SECURED — RIVAL HUMBLED',
    particleColor: 0xff0055,
    totalDurationSec: 5.2,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [-10, 2, -10],
        cameraEndOffset: [10, 4, -14],
        lookAtStartOffset: [0, 1, 8],
        lookAtEndOffset: [0, 1, 14],
        fovStart: 70,
        fovEnd: 56,
        timeScale: 0.35,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [12, 5, -2],
        cameraEndOffset: [-12, 7, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 56,
        fovEnd: 50,
        timeScale: 0.55,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 2, 14],
        cameraEndOffset: [0, 6, 22],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 65,
        timeScale: 0.9,
      },
    ],
  },

  RELAY_RACE: {
    modeId: 'RELAY_RACE',
    title: 'SQUAD TRANSMISSION COMPLETE',
    subtitle: 'BATON SYNC PERFECT // ANCHOR LEG DELIVERED ON TARGET',
    victoryMessage: 'TEAM FORMATION TELEMETRY FLAWLESS — ALL STAGES WON',
    particleColor: 0x39ff14,
    totalDurationSec: 5.0,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [0, 5, -12],
        cameraEndOffset: [6, 2, -16],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1, 15],
        fovStart: 68,
        fovEnd: 58,
        timeScale: 0.4,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-12, 4, 2],
        cameraEndOffset: [12, 6, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 58,
        fovEnd: 52,
        timeScale: 0.6,
      },
      {
        durationSec: 1.4,
        cameraStartOffset: [0, 3, 12],
        cameraEndOffset: [0, 7, 20],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 52,
        fovEnd: 64,
        timeScale: 0.85,
      },
    ],
  },

  SURVIVAL_ELIMINATION: {
    modeId: 'SURVIVAL_ELIMINATION',
    title: 'SOLE SURVIVOR STANDING',
    subtitle: 'ELIMINATION PULSES SURVIVED // LAST RACER IN THE ARENA',
    victoryMessage: 'ARENA PURGE SURPASSED — GLADIATOR PROTOCOL COMPLETE',
    particleColor: 0xff0033,
    totalDurationSec: 5.3,
    shots: [
      {
        durationSec: 1.9,
        cameraStartOffset: [0, -2, -14],
        cameraEndOffset: [5, 4, -18],
        lookAtStartOffset: [0, 1, 12],
        lookAtEndOffset: [0, 1, 18],
        fovStart: 72,
        fovEnd: 56,
        timeScale: 0.35,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [-14, 5, 2],
        cameraEndOffset: [14, 7, 10],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 56,
        fovEnd: 48,
        timeScale: 0.55,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 3, 14],
        cameraEndOffset: [0, 7, 24],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 48,
        fovEnd: 66,
        timeScale: 0.85,
      },
    ],
  },

  COSMIC_TREASURE_HUNT: {
    modeId: 'COSMIC_TREASURE_HUNT',
    title: 'RELIC MATRIX UNLOCKED',
    subtitle: 'COSMIC ORBS ASSEMBLED // ANCIENT CIPHER RESOLVED',
    victoryMessage: 'STELLAR HOARD SECURED — PROGENITOR VAULT EMBARKED',
    particleColor: 0xffea00,
    totalDurationSec: 5.2,
    shots: [
      {
        durationSec: 1.8,
        cameraStartOffset: [-6, 3, -12],
        cameraEndOffset: [6, 2, -16],
        lookAtStartOffset: [0, 1, 10],
        lookAtEndOffset: [0, 1, 15],
        fovStart: 68,
        fovEnd: 56,
        timeScale: 0.4,
      },
      {
        durationSec: 1.8,
        cameraStartOffset: [12, 5, 2],
        cameraEndOffset: [-12, 7, 8],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 56,
        fovEnd: 50,
        timeScale: 0.6,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 3, 14],
        cameraEndOffset: [0, 6, 24],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 50,
        fovEnd: 65,
        timeScale: 0.9,
      },
    ],
  },

  VOID_CHAMPIONSHIP: {
    modeId: 'VOID_CHAMPIONSHIP',
    title: 'VOID CHAMPION SUPREME',
    subtitle: 'APEX RACING PINNACLE // GRAND TOURNAMENT VICTOR',
    victoryMessage: 'HALL OF IMMORTALS ENSHRINED — THE VOID BOWS TO THE CHAMPION',
    particleColor: 0xffd700,
    totalDurationSec: 6.0,
    shots: [
      {
        durationSec: 2.2,
        cameraStartOffset: [0, -3, -14],
        cameraEndOffset: [6, 4, -18],
        lookAtStartOffset: [0, 1, 14],
        lookAtEndOffset: [0, 1, 20],
        fovStart: 76,
        fovEnd: 54,
        timeScale: 0.3,
      },
      {
        durationSec: 2.2,
        cameraStartOffset: [-14, 6, 2],
        cameraEndOffset: [14, 8, 12],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 54,
        fovEnd: 46,
        timeScale: 0.5,
      },
      {
        durationSec: 1.6,
        cameraStartOffset: [0, 3, 16],
        cameraEndOffset: [0, 8, 28],
        lookAtStartOffset: [0, 1, 0],
        lookAtEndOffset: [0, 1, 0],
        fovStart: 46,
        fovEnd: 68,
        timeScale: 0.9,
      },
    ],
  },
};

export function getFinishCinematicConfig(mode: GameMode): ModeFinishCinematicConfig {
  return (MODE_FINISH_CONFIGS[mode] || MODE_FINISH_CONFIGS.NEON_CIRCUIT)!;
}
