import { GameMode } from '../../types';
import { ModeIntroConfig } from './cinematicTypes';

/**
 * 20 Unique Cinematic Mode Configurations for VOID-RIDER 3D.
 * Each mode features its own distinct story opening, environment reveal,
 * starting location, player reveal, grid formation, countdown visual style,
 * launch effect, and opening hazard warnings.
 */

export const ALL_MODE_INTRO_CONFIGS: Record<string, ModeIntroConfig> = {
  // 01 — SINGULARITY RUN
  SINGULARITY_RUN: {
    modeId: 'SINGULARITY_RUN',
    variationName: 'DEEP HORIZON GAUNTLET',
    locationName: 'STATION HORIZON-9 // EVENT HORIZON APEX',
    missionName: 'OPERATION GRAVITY WELL',
    objectiveText: 'ENTER THE GRAVITY WELL. COMPLETE THE SLINGSHOT. ESCAPE.',
    storyIntro: {
      title: 'SINGULARITY RUN: POINT OF NO RETURN',
      locationName: 'DEEP SPACE OBSERVATION PLATFORM // SECTOR ZERO',
      missionName: 'OPERATION GRAVITY WELL',
      objectiveText: 'ENTER GRAVITY WELL. COMPLETE THE SLINGSHOT. ESCAPE.',
      loreSnippet: 'A colossal Kerr black hole twists space-time. Research telemetry demands flight through the photon sphere.',
      scenes: [
        {
          id: 'sing_scene_1',
          name: 'Colossal Singularity & Fleet Overwatch',
          durationSec: 3.2,
          cameraStartOffset: [0, 80, -220],
          cameraEndOffset: [0, 45, -110],
          lookAtStartOffset: [0, -10, 80],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 75,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_sing_1',
              sender: 'HORIZON OVERWATCH',
              text: 'RESEARCH FLEET DETECTS CRITICAL FRAME-DRAGGING. SINGULARITY CORE UNSTABLE.',
              timeSec: 0.4,
              type: 'MISSION',
              callsign: 'OBS-01',
            },
          ],
        },
        {
          id: 'sing_scene_2',
          name: 'Gravitational Light Lensing',
          durationSec: 2.8,
          cameraStartOffset: [-60, 30, -50],
          cameraEndOffset: [15, 12, -20],
          lookAtStartOffset: [0, 0, 40],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_sing_2',
              sender: 'MISSION CONTROL',
              text: 'MISSION DIRECTIVE: ENTER THE GRAVITY WELL. COMPLETE THE SLINGSHOT. ESCAPE.',
              timeSec: 0.3,
              type: 'WARNING',
              callsign: 'CMD-CORE',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 38,
      orbitHeight: 14,
      fov: 62,
      shake: 0.35,
    },
    environmentReveal: {
      title: 'SUPERMASSIVE SINGULARITY // ACCRETION DISK',
      subtitle: 'GRAVITATIONAL TIME DILATION: 4.8X // RADIATION SHIELDS NOMINAL',
      landmarkType: 'BLACK_HOLE_OBSERVATION_DECK',
    },
    playerReveal: {
      type: 'UNDERNEATH_FLYBY',
      durationSec: 2.2,
      thrusterIntensity: 1.8,
      tagline: 'GRAV-INVERTER ENGAGED // SINGULARITY DESCENT PRIMED',
    },
    startingLocation: {
      name: 'DEEP SPACE OBSERVATION PLATFORM',
      description: 'Suspended 120km above the photon sphere with quantum mooring clamps.',
      startGridT: 0.0,
      landmarkMeshType: 'OBSERVATION_PLATFORM',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 38,
    },
    countdownStyle: 'SINGULARITY_DISTORTION',
    countdownEffects: {
      primaryColor: '#d000ff',
      secondaryColor: '#00f0ff',
      soundType: 'GRAVITY_PULSE',
      glitchIntensity: 0.6,
      sublabel: 'EVENT HORIZON SHEAR // GRAV-LOCK RELEASE',
    },
    launchAnimation: {
      fovPunch: 88,
      boostDuration: 1.2,
      gateReaction: 'DISSIPATE',
      launchSpeed: 65,
    },
    firstHazard: {
      name: 'GRAVITY SHEAR CORRIDOR',
      warningText: 'CENTRIPETAL TIDAL FORCES DETECTED // VECTOR OUTWARD',
      leadTimeSec: 2.2,
      color: '#d000ff',
    },
    openingCinematic: {
      totalDurationSec: 8.5,
      skipAvailableAtSec: 1.0,
    },
  },

  // 02 — NEON CIRCUIT
  NEON_CIRCUIT: {
    modeId: 'NEON_CIRCUIT',
    variationName: 'CYBER-METROPOLIS EXPRESSWAY',
    locationName: 'NEO-SHANGHAI LEVEL 400 // ORBITAL HIGHWAY',
    missionName: 'METROPOLIS GRAND PRIX',
    objectiveText: 'DOMINATE THE THREE-LANE HIGHWAY. OUTRUN THE GRID PATROL.',
    storyIntro: {
      title: 'NEON CIRCUIT: GLOW OF THE UPPER STRATA',
      locationName: 'ORBITAL HIGHWAY A-9 // MEGACITY SKYLINE',
      missionName: 'METROPOLIS GRAND PRIX',
      objectiveText: 'DOMINATE THE THREE-LANE HIGHWAY. OUTRUN THE GRID PATROL.',
      loreSnippet: 'A shimmering sea of skyscrapers shines beneath the 8-lane magnetic raceway.',
      scenes: [
        {
          id: 'neon_scene_1',
          name: 'City Skyline & Civilian Traffic Streams',
          durationSec: 3.0,
          cameraStartOffset: [120, 140, -180],
          cameraEndOffset: [20, 60, -70],
          lookAtStartOffset: [0, -30, 0],
          lookAtEndOffset: [0, 5, 0],
          fovStart: 80,
          fovEnd: 62,
          transmissions: [
            {
              id: 't_neon_1',
              sender: 'CITY RACING NETWORK',
              text: 'ALL CIVILIAN TRAFFIC CLEARED FROM GRID CORRIDOR 7. SECTOR LIVE IN T-MINUS 10.',
              timeSec: 0.5,
              type: 'CONTROL',
              callsign: 'GRID-AI',
            },
          ],
        },
        {
          id: 'neon_scene_2',
          name: 'Skyscraper Canyon & Neon Billboards',
          durationSec: 2.5,
          cameraStartOffset: [-40, 25, -50],
          cameraEndOffset: [-10, 8, -15],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 65,
          fovEnd: 58,
          transmissions: [
            {
              id: 't_neon_2',
              sender: 'RACE ANNOUNCER',
              text: 'PILOTS TO YOUR MARKS. 80,000 METERS OF LIQUID LIGHT AWAIT.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'VOX-NEON',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 10,
      fov: 60,
      shake: 0.15,
    },
    environmentReveal: {
      title: 'NEO-TOKYO // ORBITAL FREEWAY DECK',
      subtitle: 'ALTITUDE: 8,400M // 12 MILLION SPECTATORS ONLINE',
      landmarkType: 'MEGACITY_TOWER_CLUSTER',
    },
    playerReveal: {
      type: 'TUNNEL_EXIT',
      durationSec: 2.0,
      thrusterIntensity: 1.5,
      tagline: 'LAUNCH BAY DEPRESSURIZED // TAXIING TO START GATE',
    },
    startingLocation: {
      name: 'ORBITAL NEON HIGHWAY TERMINAL',
      description: 'Luminous magnetic launch platform suspended between twin megatowers.',
      startGridT: 0.0,
      landmarkMeshType: 'NEON_HIGHWAY_GANTRY',
    },
    gridFormation: {
      type: 'HIGHWAY_LANES',
      rowSpacing: 12,
      colSpacing: 6,
      racerEntranceSpeed: 32,
    },
    countdownStyle: 'NEON_HOLOGRAM',
    countdownEffects: {
      primaryColor: '#00f0ff',
      secondaryColor: '#ff00e5',
      soundType: 'SYNTH_CHIME',
      glitchIntensity: 0.2,
      sublabel: 'RACE NETWORK ONLINE // GREEN LIGHT SEQUENCING',
    },
    launchAnimation: {
      fovPunch: 82,
      boostDuration: 1.0,
      gateReaction: 'OPEN',
      launchSpeed: 60,
    },
    firstHazard: {
      name: 'TRAFFIC BARRIER LASER',
      warningText: 'SPEED TRAP LASER EMITTERS ACTIVE AT MILE 1.2',
      leadTimeSec: 2.8,
      color: '#ff0055',
    },
    openingCinematic: {
      totalDurationSec: 8.0,
      skipAvailableAtSec: 0.8,
    },
  },

  // 03 — ASTEROID RUN
  ASTEROID_RUN: {
    modeId: 'ASTEROID_RUN',
    variationName: 'FORGOTTEN CHASM CUT',
    locationName: 'TARTARUS BELT // SECTOR OMEGA-4',
    missionName: 'UNSTABLE PASSAGE ASSAULT',
    objectiveText: 'THE PATH WILL NOT REMAIN OPEN. NAVIGATE THE CRUMBLING CANYON.',
    storyIntro: {
      title: 'ASTEROID RUN: CHASM OF SHATTERED STONE',
      locationName: 'TARTARUS DEBRIS BELT // UNCHARTED CHASM',
      missionName: 'UNSTABLE PASSAGE ASSAULT',
      objectiveText: 'THE PATH WILL NOT REMAIN OPEN. NAVIGATE CRUMBLING CANYON.',
      loreSnippet: 'Dense asteroid swarms grind against each other in the void. A short-lived fissure offers a lethal passage.',
      scenes: [
        {
          id: 'ast_scene_1',
          name: 'Colliding Asteroid Giant Field',
          durationSec: 3.2,
          cameraStartOffset: [-140, 90, -180],
          cameraEndOffset: [-30, 40, -80],
          lookAtStartOffset: [50, 0, 50],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 85,
          fovEnd: 65,
          transmissions: [
            {
              id: 't_ast_1',
              sender: 'MINING DRILL OVERWATCH',
              text: 'SECTOR COLLISION DETECTED. MEGATON ASTEROID CRUSH VECTOR ENGAGED.',
              timeSec: 0.3,
              type: 'WARNING',
              callsign: 'DRILL-04',
            },
          ],
        },
        {
          id: 'ast_scene_2',
          name: 'Canyon Breach & Narrow Fissure',
          durationSec: 2.6,
          cameraStartOffset: [25, 20, -45],
          cameraEndOffset: [5, 7, -18],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 58,
          transmissions: [
            {
              id: 't_ast_2',
              sender: 'RACE DIRECTOR',
              text: 'WARNING: THE PATH WILL NOT REMAIN OPEN. MOVE FAST OR BE CRUSHED.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'CONTROL',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 35,
      orbitHeight: 12,
      fov: 65,
      shake: 0.45,
    },
    environmentReveal: {
      title: 'TARTARUS ASTEROID CRAG',
      subtitle: 'ROCK ROTATION: DANGEROUS // SHIELD REINFORCEMENT ACTIVE',
      landmarkType: 'ASTEROID_CANYON_ENTRANCE',
    },
    playerReveal: {
      type: 'ASTEROID_ESCAPE',
      durationSec: 2.2,
      thrusterIntensity: 1.6,
      tagline: 'TERRAIN AVOIDANCE OVERRIDDEN // DRIFT RUDDERS HOT',
    },
    startingLocation: {
      name: 'PROTECTED ASTEROID CANYON',
      description: 'Natural cavern carved through an ancient iron nickel planetoid.',
      startGridT: 0.0,
      landmarkMeshType: 'ROCK_CANYON_GATE',
    },
    gridFormation: {
      type: 'ECHELON',
      rowSpacing: 15,
      colSpacing: 7,
      racerEntranceSpeed: 30,
    },
    countdownStyle: 'TACTICAL_HUD',
    countdownEffects: {
      primaryColor: '#ffaa00',
      secondaryColor: '#00f0ff',
      soundType: 'RADAR_BEEP',
      glitchIntensity: 0.4,
      sublabel: 'PROXIMITY RADAR: HOT // IMPACT HORIZON CLEAR',
    },
    launchAnimation: {
      fovPunch: 84,
      boostDuration: 1.1,
      gateReaction: 'FLASH',
      launchSpeed: 58,
    },
    firstHazard: {
      name: 'FALLING IRON BOULDER',
      warningText: 'GRAVITATIONAL TUMBLE OVERHEAD // HARD SLALOM LEFT',
      leadTimeSec: 2.0,
      color: '#ffaa00',
    },
    openingCinematic: {
      totalDurationSec: 8.4,
      skipAvailableAtSec: 0.8,
    },
  },

  // 04 — WORMHOLE EXPRESS
  WORMHOLE_EXPRESS: {
    modeId: 'WORMHOLE_EXPRESS',
    variationName: 'EINSTEIN-ROSEN ACCELERATOR',
    locationName: 'APERTURE ALPHA // TRANSLUMINAL CORRIDOR',
    missionName: 'WORMHOLE STABILIZATION SPRINT',
    objectiveText: 'RUSH THE CONDUIT BEFORE THE SINGULARITY SINGLET COLLAPSES.',
    storyIntro: {
      title: 'WORMHOLE EXPRESS: TRANSLUMINAL CORRIDOR',
      locationName: 'APERTURE ALPHA // TRANSLUMINAL GATE',
      missionName: 'WORMHOLE SPRINT',
      objectiveText: 'ENTER THE PORTAL BEFORE COLLAPSE. SURVIVE CHRONO SURGE.',
      loreSnippet: 'A localized Einstein-Rosen aperture pulses with unstable exotic matter. Only the fastest survive.',
      scenes: [
        {
          id: 'wh_scene_1',
          name: 'Gigantic Wormhole Aperture Swirl',
          durationSec: 3.4,
          cameraStartOffset: [0, 90, -200],
          cameraEndOffset: [0, 30, -90],
          lookAtStartOffset: [0, 0, 100],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 85,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_wh_1',
              sender: 'GATE CONTROLLER',
              text: 'SUB-QUANTUM APERTURE BALANCED. WINDOW DURATION ESTIMATED: 90 SECONDS.',
              timeSec: 0.4,
              type: 'MISSION',
              callsign: 'GATE-01',
            },
          ],
        },
        {
          id: 'wh_scene_2',
          name: 'Hyperspace Induction Rings',
          durationSec: 2.6,
          cameraStartOffset: [-35, 18, -40],
          cameraEndOffset: [0, 7, -16],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 70,
          fovEnd: 56,
          transmissions: [
            {
              id: 't_wh_2',
              sender: 'WARP NAVIGATOR',
              text: 'ALL CRAFT LOCK STABILIZER FINS. CHRONO-DISTORTION IMMINENT.',
              timeSec: 0.2,
              type: 'WARNING',
              callsign: 'NAV-PRIME',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 30,
      orbitHeight: 11,
      fov: 64,
      shake: 0.3,
    },
    environmentReveal: {
      title: 'SINGULARITY INJECTION RING',
      subtitle: 'FIELD COHERENCE: 94.2% // TACHYON FLUX SURGING',
      landmarkType: 'WORMHOLE_APERTURE_STATION',
    },
    playerReveal: {
      type: 'WORMHOLE_EMERGE',
      durationSec: 2.0,
      thrusterIntensity: 1.9,
      tagline: 'QUANTUM ENTAGLEMENT SYNCHRONIZED',
    },
    startingLocation: {
      name: 'GIGANTIC WORMHOLE LAUNCH STATION',
      description: 'Triple-ring accelerator floating before the swirling vortex portal.',
      startGridT: 0.0,
      landmarkMeshType: 'WARP_PORTAL_GATE',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 40,
    },
    countdownStyle: 'WORMHOLE_PULSE',
    countdownEffects: {
      primaryColor: '#00f0ff',
      secondaryColor: '#9900ff',
      soundType: 'WARP_PULSE',
      glitchIntensity: 0.5,
      sublabel: 'WARP COILS PRIMED // TRANSLUMINAL BURST READY',
    },
    launchAnimation: {
      fovPunch: 90,
      boostDuration: 1.3,
      gateReaction: 'DISSIPATE',
      launchSpeed: 70,
    },
    firstHazard: {
      name: 'CHRONO-WARP DISRUPTION',
      warningText: 'TACHYON WAVE INVERSION AT FIRST CORNER',
      leadTimeSec: 2.4,
      color: '#00f0ff',
    },
    openingCinematic: {
      totalDurationSec: 8.5,
      skipAvailableAtSec: 1.0,
    },
  },

  // 05 — SOLAR STORM
  SOLAR_STORM: {
    modeId: 'SOLAR_STORM',
    variationName: 'HELIOSPHERE CORONA SURGE',
    locationName: 'SOLAR OBSERVATORY DELTA-3 // CORONA PERIMETER',
    missionName: 'SOLAR PROXIMITY RUSH',
    objectiveText: 'MAINTAIN HEAT SHIELD INTEGRITY. OUTRUN THE CORONAL MASS EJECTION.',
    storyIntro: {
      title: 'SOLAR STORM: FURY OF THE PROTOCELL STAR',
      locationName: 'HELIOS CORONAL STATION // 0.08 AU',
      missionName: 'SOLAR PROXIMITY RUSH',
      objectiveText: 'OUTRUN CORONAL MASS EJECTION. MONITOR HEAT TILES.',
      loreSnippet: 'Racing across the photosphere of an hyper-giant star. Massive solar prominences arc over the track.',
      scenes: [
        {
          id: 'sol_scene_1',
          name: 'Blinding Solar Prominence Arc',
          durationSec: 3.3,
          cameraStartOffset: [-100, 110, -210],
          cameraEndOffset: [10, 45, -95],
          lookAtStartOffset: [0, -20, 50],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 80,
          fovEnd: 62,
          transmissions: [
            {
              id: 't_sol_1',
              sender: 'SOLAR DYNAMICS OVERWATCH',
              text: 'CLASS-X FLARE DETECTED. THERMAL WAVEFRONT IMPACTING CORRIDOR NOW.',
              timeSec: 0.4,
              type: 'WARNING',
              callsign: 'HELIOS-1',
            },
          ],
        },
        {
          id: 'sol_scene_2',
          name: 'Solar Heat Shields & Flare Eruption',
          durationSec: 2.5,
          cameraStartOffset: [30, 15, -45],
          cameraEndOffset: [0, 8, -17],
          lookAtStartOffset: [0, 0, 25],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 57,
          transmissions: [
            {
              id: 't_sol_2',
              sender: 'RACE CONTROL',
              text: 'STORM LEVEL INCREASING. ACTIVATE HEAT DISPERSION ARRAYS.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'CONTROL',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 34,
      orbitHeight: 12,
      fov: 63,
      shake: 0.35,
    },
    environmentReveal: {
      title: 'SOLAR PHOTO-SPHERE OBSERVATORY',
      subtitle: 'SURFACE TEMP: 8,400 K // MAGNETIC LOOPS EXPANDING',
      landmarkType: 'SOLAR_OBSERVATION_DISH',
    },
    playerReveal: {
      type: 'AFTERBURNER_IGNITE',
      durationSec: 2.1,
      thrusterIntensity: 2.0,
      tagline: 'THERMAL SHIELDS AT MAXIMUM DENSITY',
    },
    startingLocation: {
      name: 'SOLAR OBSERVATION STATION',
      description: 'Gold-plated thermal barrier platforms anchored in the star magnetic wake.',
      startGridT: 0.0,
      landmarkMeshType: 'SOLAR_STATION_GANTRY',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 13,
      colSpacing: 8,
      racerEntranceSpeed: 35,
    },
    countdownStyle: 'SOLAR_FLARE',
    countdownEffects: {
      primaryColor: '#ff5500',
      secondaryColor: '#ffff00',
      soundType: 'PLASMA_HISS',
      glitchIntensity: 0.35,
      sublabel: 'CORONA SHIELD MAXIMUM // FLARE LOCKOUT ACTIVE',
    },
    launchAnimation: {
      fovPunch: 86,
      boostDuration: 1.1,
      gateReaction: 'OPEN',
      launchSpeed: 62,
    },
    firstHazard: {
      name: 'CORONAL FLAME JET',
      warningText: 'SUPERHEATED PLASMA GEYSER CROSSING APEX',
      leadTimeSec: 2.1,
      color: '#ff5500',
    },
    openingCinematic: {
      totalDurationSec: 8.2,
      skipAvailableAtSec: 0.9,
    },
  },

  // 06 — GRAVITY FREE
  GRAVITY_FREE: {
    modeId: 'GRAVITY_FREE',
    variationName: 'NULL-MASS VECTOR ARENA',
    locationName: 'ORBITAL HIGHWAY HUB-X // ZERO-G SPHERE',
    missionName: 'MICROGRAVITY DRIFT CHALLENGE',
    objectiveText: 'ARTIFICIAL GRAVITY DISABLED. HARNESS GYROSCOPIC MOMENTUM.',
    storyIntro: {
      title: 'GRAVITY FREE: TETHER DISCONNECTED',
      locationName: 'ORBITAL STATION 14 // NULL-G DRIFT BAY',
      missionName: 'MICROGRAVITY SPRINT',
      objectiveText: 'ARTIFICIAL GRAVITY DISABLED. HARNESS GYROSCOPIC MOMENTUM.',
      loreSnippet: 'The orbital race facility disables centrifugal gravity arrays. Racing craft float freely in space.',
      scenes: [
        {
          id: 'gf_scene_1',
          name: 'Floating Facility & Weightless Vessels',
          durationSec: 3.2,
          cameraStartOffset: [70, 70, -160],
          cameraEndOffset: [-10, 35, -75],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 78,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_gf_1',
              sender: 'ORBITAL PLATFORM AI',
              text: 'ARTIFICIAL GRAVITY DE-ENERGIZED. MASS DAMPENERS AT ZERO PERCENT.',
              timeSec: 0.4,
              type: 'CONTROL',
              callsign: 'ZERO-AI',
            },
          ],
        },
        {
          id: 'gf_scene_2',
          name: 'Rotating Starting Platforms',
          durationSec: 2.6,
          cameraStartOffset: [-25, 16, -35],
          cameraEndOffset: [0, 6, -14],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_gf_2',
              sender: 'RACE CONTROLLER',
              text: 'CALIBRATE RCS VECTOR THRUSTERS. THREE DIMENSIONS OF FREEDOM.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'CONTROL',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 28,
      orbitHeight: 9,
      fov: 62,
      shake: 0.1,
    },
    environmentReveal: {
      title: 'NULL-GRAVITY ORBITAL CRADLE',
      subtitle: 'GRAV-COILS SHUT DOWN // GYRO DRIFT BOOST ACTIVE',
      landmarkType: 'ORBITAL_ZERO_G_ARRAY',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 2.0,
      thrusterIntensity: 1.4,
      tagline: 'RCS MICRO-THRUSTERS INITIALIZED',
    },
    startingLocation: {
      name: 'ZERO-GRAVITY LAUNCH ZONE',
      description: 'Floating magnetic cradle in open vacuum outside the station rings.',
      startGridT: 0.0,
      landmarkMeshType: 'ZERO_G_LAUNCH_CRADLE',
    },
    gridFormation: {
      type: 'ARENA_RING',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 28,
    },
    countdownStyle: 'GRAVITY_FLOATING',
    countdownEffects: {
      primaryColor: '#00e5ff',
      secondaryColor: '#ffffff',
      soundType: 'ZERO_G_RING',
      glitchIntensity: 0.15,
      sublabel: 'WEIGHTLESS VECTORS LOCKED // FREE LAUNCH',
    },
    launchAnimation: {
      fovPunch: 80,
      boostDuration: 1.0,
      gateReaction: 'RETRACT',
      launchSpeed: 55,
    },
    firstHazard: {
      name: 'SPINNING DEBRIS TURBINE',
      warningText: 'SLOW AXIAL ROTATION ON FIRST PLATFORM',
      leadTimeSec: 2.6,
      color: '#00e5ff',
    },
    openingCinematic: {
      totalDurationSec: 8.2,
      skipAvailableAtSec: 0.8,
    },
  },

  // 07 — PLASMA STORM
  PLASMA_STORM: {
    modeId: 'PLASMA_STORM',
    variationName: 'IONIC DISCHARGE MAELSTROM',
    locationName: 'NEBULA PERIMETER // SECTOR 11-ARC',
    missionName: 'ION STORM EVASION',
    objectiveText: 'RACE THROUGH THE TEMPORARY ENERGY CORRIDOR. AVOID LIGHTNING STRIKES.',
    storyIntro: {
      title: 'PLASMA STORM: LIGHTNING FRONTIER',
      locationName: 'IONIZED NEBULA VEIL // SECTOR 11',
      missionName: 'ION STORM EVASION',
      objectiveText: 'SURVIVE IONIC ARCS. STAY INSIDE ENERGY CORRIDOR.',
      loreSnippet: 'A volatile plasma cloud arcs across the race corridor, discharging megavolts of atmospheric electricity.',
      scenes: [
        {
          id: 'ps_scene_1',
          name: 'Towering Plasma Clouds & Arc Discharges',
          durationSec: 3.2,
          cameraStartOffset: [-110, 80, -190],
          cameraEndOffset: [20, 35, -85],
          lookAtStartOffset: [0, 0, 40],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 82,
          fovEnd: 64,
          transmissions: [
            {
              id: 't_ps_1',
              sender: 'WEATHER COMMAND',
              text: 'HIGH DENSITY ION SURGE INCOMING. EMERGENCY MAGNETIC CORRIDOR OPEN.',
              timeSec: 0.4,
              type: 'WARNING',
              callsign: 'RADAR-ARC',
            },
          ],
        },
        {
          id: 'ps_scene_2',
          name: 'Temporary Forcefield Gantry',
          durationSec: 2.6,
          cameraStartOffset: [30, 18, -40],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 70,
          fovEnd: 58,
          transmissions: [
            {
              id: 't_ps_2',
              sender: 'RACE MARSHAL',
              text: 'DEVIATE FROM THE FLIGHTPATH AND THE DISCHARGE WILL FRY YOUR AVIONICS.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'CONTROL',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 11,
      fov: 63,
      shake: 0.4,
    },
    environmentReveal: {
      title: 'IONIC PLASMA CONVERGENCE',
      subtitle: 'STATIC POTENTIAL: 40 GIGAVOLTS // FARADAY MESH ENERZIED',
      landmarkType: 'PLASMA_STORM_CORRIDOR',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 2.0,
      thrusterIntensity: 1.7,
      tagline: 'FARADAY COATINGS ACTIVE // LIGHTNING GROUNDING ARMORED',
    },
    startingLocation: {
      name: 'EDGE OF AN ENORMOUS PLASMA CLOUD',
      description: 'Stabilizer gates channeling safe passage through turbulent violet lightning clouds.',
      startGridT: 0.0,
      landmarkMeshType: 'PLASMA_FIELD_GATE',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 13,
      colSpacing: 7,
      racerEntranceSpeed: 34,
    },
    countdownStyle: 'PLASMA_LIGHTNING',
    countdownEffects: {
      primaryColor: '#b000ff',
      secondaryColor: '#00f0ff',
      soundType: 'ELECTRIC_SPARK',
      glitchIntensity: 0.5,
      sublabel: 'ION CHANNELS CLEAR // ARC WARNING ENFORCED',
    },
    launchAnimation: {
      fovPunch: 85,
      boostDuration: 1.1,
      gateReaction: 'DISSIPATE',
      launchSpeed: 62,
    },
    firstHazard: {
      name: 'BALL LIGHTNING CLUSTER',
      warningText: 'FLOATING IONIZED CHARGE DRIFTING CENTER-TRACK',
      leadTimeSec: 2.2,
      color: '#b000ff',
    },
    openingCinematic: {
      totalDurationSec: 8.3,
      skipAvailableAtSec: 0.8,
    },
  },

  // 08 — SKYLINE RUSH
  SKYLINE_RUSH: {
    modeId: 'SKYLINE_RUSH',
    variationName: 'AERODYNAMIC APEX RUN',
    locationName: 'OLYMPUS TOWER SUMMIT // LEVEL 950',
    missionName: 'DOWNTOWN MEGATOWER RUSH',
    objectiveText: 'THREAD THE SKYSCRAPERS. WEAVE THROUGH ORBITAL SPIRES.',
    storyIntro: {
      title: 'SKYLINE RUSH: ARCHITECTURE OF SPEED',
      locationName: 'METROPOLIS VERTICALS // SECTOR 7',
      missionName: 'DOWNTOWN MEGATOWER RUSH',
      objectiveText: 'THREAD THE SKYSCRAPERS. WEAVE THROUGH ORBITAL SPIRES.',
      loreSnippet: 'Distant spectator ships illuminate colossal spires that pierce cloud layers.',
      scenes: [
        {
          id: 'sk_scene_1',
          name: 'Descending from Upper Orbital Highway',
          durationSec: 3.1,
          cameraStartOffset: [0, 160, -200],
          cameraEndOffset: [0, 45, -80],
          lookAtStartOffset: [0, -30, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 85,
          fovEnd: 62,
          transmissions: [
            {
              id: 't_sk_1',
              sender: 'TOWER TRAFFIC DISPATCH',
              text: 'VECTORED DESCENT FROM HIGH ORBIT COMPLETE. WELCOME TO SKYLINE RUSH.',
              timeSec: 0.4,
              type: 'CONTROL',
              callsign: 'DISPATCH',
            },
          ],
        },
        {
          id: 'sk_scene_2',
          name: 'Skyscraper Rooftop Grid Formation',
          durationSec: 2.5,
          cameraStartOffset: [-35, 20, -40],
          cameraEndOffset: [-5, 8, -16],
          lookAtStartOffset: [0, 0, 25],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 56,
          transmissions: [
            {
              id: 't_sk_2',
              sender: 'RACE COMMODORE',
              text: 'HIGH-G BANKING AT TOWER CORNERS. MAINTAIN LINEAR APEX.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'COMMODORE',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 30,
      orbitHeight: 11,
      fov: 62,
      shake: 0.2,
    },
    environmentReveal: {
      title: 'OLYMPUS SPIRE LEVEL 950',
      subtitle: 'ELEVATION: 14,000M // LOWER CLOUD DECK SHADOW',
      landmarkType: 'MEGATOWER_SUMMIT',
    },
    playerReveal: {
      type: 'ORBITAL_DROP',
      durationSec: 2.1,
      thrusterIntensity: 1.7,
      tagline: 'DESCENDING TOUCHDOWN // MAGNETIC SKIDS ATTACHED',
    },
    startingLocation: {
      name: 'FUTURISTIC MEGACITY TOWER HIGHWAY',
      description: 'Suspended asphalt ribbon curving between towering corporate spires.',
      startGridT: 0.0,
      landmarkMeshType: 'TOWER_ROOFTOP_GATE',
    },
    gridFormation: {
      type: 'HIGHWAY_LANES',
      rowSpacing: 13,
      colSpacing: 6,
      racerEntranceSpeed: 36,
    },
    countdownStyle: 'SKYLINE_BILLBOARD',
    countdownEffects: {
      primaryColor: '#00f0ff',
      secondaryColor: '#ff00aa',
      soundType: 'CITY_HORN',
      glitchIntensity: 0.2,
      sublabel: 'METROPOLITAN COMMERCE DISPLAY // SYNC LIGHTS',
    },
    launchAnimation: {
      fovPunch: 84,
      boostDuration: 1.1,
      gateReaction: 'OPEN',
      launchSpeed: 60,
    },
    firstHazard: {
      name: 'AERIAL COMMERCE CRANE',
      warningText: 'CONSTRUCTION GANTRY OBSTRUCTION // EVADE RIGHT',
      leadTimeSec: 2.4,
      color: '#ffaa00',
    },
    openingCinematic: {
      totalDurationSec: 8.1,
      skipAvailableAtSec: 0.8,
    },
  },

  // 09 — DEBRIS SURVIVAL
  DEBRIS_SURVIVAL: {
    modeId: 'DEBRIS_SURVIVAL',
    variationName: 'DERELICT GRAVEYARD RUN',
    locationName: 'ABANDONED ORBITAL HABITAT // WRECKAGE APEX',
    missionName: 'SALVAGE EXPEDITION RUN',
    objectiveText: 'NAVIGATE COLLAPSING SUPERSTRUCTURES. AVOID DISASTER FRAGMENTS.',
    storyIntro: {
      title: 'DEBRIS SURVIVAL: GRAVEYARD OF TITANS',
      locationName: 'WRECKAGE FIELD // SECTOR OMEGA',
      missionName: 'SALVAGE RUN',
      objectiveText: 'SURVIVE FLOATING METALLIC DEBRIS. FIND THE SAFE FLIGHT LINE.',
      loreSnippet: 'A shattered orbital station tumbles slowly through the void. Race organizers turn the cataclysm into a crucible.',
      scenes: [
        {
          id: 'deb_scene_1',
          name: 'Destroyed Megastructure Collapsing',
          durationSec: 3.3,
          cameraStartOffset: [110, 85, -200],
          cameraEndOffset: [-10, 40, -85],
          lookAtStartOffset: [0, 0, 40],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 84,
          fovEnd: 63,
          transmissions: [
            {
              id: 't_deb_1',
              sender: 'EMERGENCY BEACON',
              text: 'AUTOMATED DISTRESS: HABITAT CORE EXPIRING. STRUCTURAL FAILURE IN 3, 2...',
              timeSec: 0.4,
              type: 'WARNING',
              callsign: 'SOS-HAB',
            },
          ],
        },
        {
          id: 'deb_scene_2',
          name: 'Navigating Through Scrap Fissures',
          durationSec: 2.5,
          cameraStartOffset: [-30, 16, -40],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 57,
          transmissions: [
            {
              id: 't_deb_2',
              sender: 'SALVAGE GUILD DISPATCH',
              text: 'KEEP YOUR SHIELDS HIGH. UNCHARTED TITANIUM GIRDERS EVERYWHERE.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'SALVAGE-1',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 11,
      fov: 64,
      shake: 0.4,
    },
    environmentReveal: {
      title: 'SHATTERED SOLAR ARRAY SECTOR',
      subtitle: 'DEBRIS DENSITY: CRITICAL // BULKHEAD ROTATION ACTIVE',
      landmarkType: 'DAMAGED_SPACE_STATION',
    },
    playerReveal: {
      type: 'ASTEROID_ESCAPE',
      durationSec: 2.0,
      thrusterIntensity: 1.6,
      tagline: 'DEFLECTOR SCREENS TUNED TO METALLIC IMPACT',
    },
    startingLocation: {
      name: 'BESIDE DAMAGED ABANDONED SPACE STATION',
      description: 'Emergency flight staging area near the twisted atmospheric habitat ring.',
      startGridT: 0.0,
      landmarkMeshType: 'DERELICT_DOCKING_ARM',
    },
    gridFormation: {
      type: 'ECHELON',
      rowSpacing: 14,
      colSpacing: 7,
      racerEntranceSpeed: 30,
    },
    countdownStyle: 'DEBRIS_EMERGENCY',
    countdownEffects: {
      primaryColor: '#ff2200',
      secondaryColor: '#ffaa00',
      soundType: 'ALARM_KLAXON',
      glitchIntensity: 0.65,
      sublabel: 'EMERGENCY BEACONS FLASHING // RUN FOR LIFE',
    },
    launchAnimation: {
      fovPunch: 85,
      boostDuration: 1.1,
      gateReaction: 'FLASH',
      launchSpeed: 58,
    },
    firstHazard: {
      name: 'TUMBLING SOLAR GANGWAY',
      warningText: 'ROTATING STEEL HULL SECTION BLOCKING APEX',
      leadTimeSec: 2.0,
      color: '#ff2200',
    },
    openingCinematic: {
      totalDurationSec: 8.3,
      skipAvailableAtSec: 0.8,
    },
  },

  // 10 — QUANTUM TIME TRIAL
  QUANTUM_TIME_TRIAL: {
    modeId: 'QUANTUM_TIME_TRIAL',
    variationName: 'CHRONO-CALIBRATED APEX',
    locationName: 'CHRONOS RESEARCH COMPLEX // QUANTUM GAUNTLET',
    missionName: 'QUANTUM TIME ASSAULT',
    objectiveText: 'OUTPACE THE QUANTUM GHOST RECORD. ACHIEVE SUB-ATOMIC PERFECTION.',
    storyIntro: {
      title: 'QUANTUM TIME TRIAL: PRECISION CHRONOMETRY',
      locationName: 'CHRONOS LABORATORY // SYNCHRONIZED CORE',
      missionName: 'QUANTUM TIME ASSAULT',
      objectiveText: 'OUTPACE QUANTUM GHOST. SUB-ATOMIC DRIFT TIMING.',
      loreSnippet: 'A precision quantum racing facility calculates optimal racing lines across parallel time loops.',
      scenes: [
        {
          id: 'qtt_scene_1',
          name: 'Precision Laser Quantum Race Corridor',
          durationSec: 3.1,
          cameraStartOffset: [0, 60, -180],
          cameraEndOffset: [0, 25, -75],
          lookAtStartOffset: [0, 0, 50],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 76,
          fovEnd: 58,
          transmissions: [
            {
              id: 't_qtt_1',
              sender: 'CHRONO COMPUTER',
              text: 'QUANTUM SECTOR CALIBRATED. PREVIOUS SECTOR RECORD GHOST PROJECTED.',
              timeSec: 0.4,
              type: 'MISSION',
              callsign: 'Q-AI',
            },
          ],
        },
        {
          id: 'qtt_scene_2',
          name: 'Ghost Racer Accelerates Away',
          durationSec: 2.5,
          cameraStartOffset: [-25, 14, -35],
          cameraEndOffset: [0, 6, -14],
          lookAtStartOffset: [0, 0, 25],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 66,
          fovEnd: 54,
          transmissions: [
            {
              id: 't_qtt_2',
              sender: 'CHIEF ENGINEER',
              text: 'MICROSECOND TELEMETRY ACTIVE. PURE SOLO TIME ATTACK. ENGAGE.',
              timeSec: 0.2,
              type: 'CONTROL',
              callsign: 'TECH-1',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 26,
      orbitHeight: 8,
      fov: 60,
      shake: 0.1,
    },
    environmentReveal: {
      title: 'QUANTUM ATOMIC RACING LAB',
      subtitle: 'CHRONO VARIANCE: 0.0001 SEC // GHOST ENGINE ONLINE',
      landmarkType: 'QUANTUM_FACILITY_RING',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 1.9,
      thrusterIntensity: 1.4,
      tagline: 'CHRONO-TELEMETRY SYNCED // ATOMIC CLOCK ZEROED',
    },
    startingLocation: {
      name: 'PRECISION RACING FACILITY',
      description: 'Sterile high-precision quantum laboratory chamber with laser timing grid.',
      startGridT: 0.0,
      landmarkMeshType: 'QUANTUM_GATE_APERTURE',
    },
    gridFormation: {
      type: 'SIDE_BY_SIDE',
      rowSpacing: 10,
      colSpacing: 8,
      racerEntranceSpeed: 32,
    },
    countdownStyle: 'QUANTUM_GATE',
    countdownEffects: {
      primaryColor: '#00f0ff',
      secondaryColor: '#39ff14',
      soundType: 'DIGITAL_CLICK',
      glitchIntensity: 0.1,
      sublabel: 'PRECISION ATOMIC GATE // 00.000s TARGET',
    },
    launchAnimation: {
      fovPunch: 80,
      boostDuration: 1.0,
      gateReaction: 'OPEN',
      launchSpeed: 60,
    },
    firstHazard: {
      name: 'QUANTUM CHRONO GATE',
      warningText: 'LASER TIMING GATE // CLIP APEX FOR BONUS ACCELERATION',
      leadTimeSec: 2.2,
      color: '#39ff14',
    },
    openingCinematic: {
      totalDurationSec: 8.0,
      skipAvailableAtSec: 0.7,
    },
  },

  // 11 — ENERGY HEIST
  ENERGY_HEIST: {
    modeId: 'ENERGY_HEIST',
    variationName: 'SILENT INFILTRATION SPRINT',
    locationName: 'VALKYRIE POWER COMPLEX // RESTRICTED AIRSPACE',
    missionName: 'OPERATION ENERGY HEIST',
    objectiveText: 'INFILTRATE. STEAL THE CORE. ESCAPE.',
    storyIntro: {
      title: 'ENERGY HEIST: CLASSIFIED INFILTRATION',
      locationName: 'VALKYRIE VAULT // SECTOR CLASSIFIED',
      missionName: 'OPERATION HEIST',
      objectiveText: 'INFILTRATE. STEAL THE CORE. ESCAPE SECURITY DRONES.',
      loreSnippet: 'Approaching a heavily guarded military energy facility under radio silence. Stealth transponders active.',
      scenes: [
        {
          id: 'eh_scene_1',
          name: 'Patrolling Security Drones & Searchlights',
          durationSec: 3.2,
          cameraStartOffset: [-90, 70, -170],
          cameraEndOffset: [15, 30, -75],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 80,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_eh_1',
              sender: 'SYNDICATE HANDLER',
              text: 'RADAR SILENCE CONFIRMED. TRANSPONDER TRANSMISSION DISCONNECTED.',
              timeSec: 0.4,
              type: 'MISSION',
              callsign: 'CIPHER',
            },
          ],
        },
        {
          id: 'eh_scene_2',
          name: 'Covert Infiltration Gate Lockdown',
          durationSec: 2.5,
          cameraStartOffset: [25, 14, -35],
          cameraEndOffset: [0, 6, -14],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_eh_2',
              sender: 'SYNDICATE HANDLER',
              text: 'OBJECTIVE: INFILTRATE. STEAL THE CORE. ESCAPE BEFORE ALARMS BIND.',
              timeSec: 0.2,
              type: 'WARNING',
              callsign: 'CIPHER',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 28,
      orbitHeight: 10,
      fov: 62,
      shake: 0.25,
    },
    environmentReveal: {
      title: 'HIGH SECURITY ENERGY COMPLEX',
      subtitle: 'ENERGY CORE DOCK: 2.4KM // SEARCHLIGHT SWEEP ARMED',
      landmarkType: 'ENERGY_FACILITY_VAULT',
    },
    playerReveal: {
      type: 'HANGAR_LAUNCH',
      durationSec: 2.0,
      thrusterIntensity: 1.5,
      tagline: 'STEALTH CLOAK DISENGAGING // MAXIMUM THRUST PRIMED',
    },
    startingLocation: {
      name: 'COVERT INFILTRATION ZONE OUTSIDE FACILITY',
      description: 'Shadowed access conduit tucked beneath giant coolant pipes.',
      startGridT: 0.0,
      landmarkMeshType: 'HEIST_INFILTRATION_TUBE',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 12,
      colSpacing: 7,
      racerEntranceSpeed: 32,
    },
    countdownStyle: 'COVERT_HEIST',
    countdownEffects: {
      primaryColor: '#ff0055',
      secondaryColor: '#00f0ff',
      soundType: 'STEALTH_SONAR',
      glitchIntensity: 0.45,
      sublabel: 'SECURITY OVERRIDE IN PROGRESS // TRIGGER ALARM AT ZERO',
    },
    launchAnimation: {
      fovPunch: 86,
      boostDuration: 1.1,
      gateReaction: 'OPEN',
      launchSpeed: 64,
    },
    firstHazard: {
      name: 'PERIMETER LASER TRIPWIRE',
      warningText: 'SECURITY GRID ACTIVATED // BOOST UNDER DETECTOR BEAM',
      leadTimeSec: 2.2,
      color: '#ff0055',
    },
    openingCinematic: {
      totalDurationSec: 8.2,
      skipAvailableAtSec: 0.8,
    },
  },

  // 12 — DRONE ASSAULT
  DRONE_ASSAULT: {
    modeId: 'DRONE_ASSAULT',
    variationName: 'CARRIER CATAPULT SCRIMMAGE',
    locationName: 'DREADNOUGHT LEVIATHAN // FLIGHT DECK ALPHA',
    missionName: 'HOSTILE DRONE INTERCEPTION',
    objectiveText: 'COMBAT RACE. DODGE AIR COMBAT DRONES. USE MISSILES FREELY.',
    storyIntro: {
      title: 'DRONE ASSAULT: COMBAT CARRIER WAKE',
      locationName: 'DREADNOUGHT FLIGHT DECK // COMBAT SECTOR',
      missionName: 'COMBAT INTERCEPTION',
      objectiveText: 'COMBAT RACE. DODGE SWARM DRONES. WEAPONS AUTHORIZED.',
      loreSnippet: 'A massive military carrier releases combat drones into the racing sector. Missile warnings flash red.',
      scenes: [
        {
          id: 'da_scene_1',
          name: 'Carrier Catapult Flight Deck & Drone Swarms',
          durationSec: 3.3,
          cameraStartOffset: [-120, 95, -190],
          cameraEndOffset: [20, 40, -80],
          lookAtStartOffset: [0, 0, 40],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 82,
          fovEnd: 62,
          transmissions: [
            {
              id: 't_da_1',
              sender: 'CARRIER COMMAND',
              text: 'HOSTILE DRONE SWARM DEPLOYED. ALL RACERS ARM SHIP COMBAT SYSTEMS.',
              timeSec: 0.4,
              type: 'WARNING',
              callsign: 'CARRIER-01',
            },
          ],
        },
        {
          id: 'da_scene_2',
          name: 'Missile Target Lock Calibration',
          durationSec: 2.5,
          cameraStartOffset: [30, 16, -38],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 70,
          fovEnd: 56,
          transmissions: [
            {
              id: 't_da_2',
              sender: 'WEAPONS OFFICER',
              text: 'HOMING MISSILES AND ACTIVE DEFENSE SHIELDS ARMED. ENGAGE AT WILL.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'GUNNER',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 11,
      fov: 64,
      shake: 0.35,
    },
    environmentReveal: {
      title: 'SPACE CARRIER BATTLE WAKE',
      subtitle: 'DRONE THREAT: HIGH // TARGETING COMPUTERS LOCKING',
      landmarkType: 'MILITARY_CARRIER_DECK',
    },
    playerReveal: {
      type: 'CARRIER_CATAPULT',
      durationSec: 2.1,
      thrusterIntensity: 1.9,
      tagline: 'CATAPULT MOORING RELEASED // WEAPONS HOT',
    },
    startingLocation: {
      name: 'MILITARY CARRIER FLIGHT DECK',
      description: 'Armored carrier runway illuminated by red combat emergency beacons.',
      startGridT: 0.0,
      landmarkMeshType: 'CARRIER_CATAPULT_GANTRY',
    },
    gridFormation: {
      type: 'CARRIER_FLIGHT_DECK',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 36,
    },
    countdownStyle: 'DRONE_TARGETING',
    countdownEffects: {
      primaryColor: '#ff0033',
      secondaryColor: '#ffcc00',
      soundType: 'RADAR_LOCK',
      glitchIntensity: 0.4,
      sublabel: 'COMBAT TARGETING READY // WEAPONS FREE ON GREEN',
    },
    launchAnimation: {
      fovPunch: 88,
      boostDuration: 1.2,
      gateReaction: 'OPEN',
      launchSpeed: 66,
    },
    firstHazard: {
      name: 'INTERCEPTOR COMBAT DRONE',
      warningText: 'KAMIKAZE DRONE ON HEAD-ON INTERCEPT VECTOR',
      leadTimeSec: 2.1,
      color: '#ff0033',
    },
    openingCinematic: {
      totalDurationSec: 8.3,
      skipAvailableAtSec: 0.8,
    },
  },

  // 13 — COLLAPSING TRACK
  COLLAPSING_TRACK: {
    modeId: 'COLLAPSING_TRACK',
    variationName: 'SHATTERED RUNWAY FALL',
    locationName: 'FAILING SECTOR SIGMA // STRUCTURAL CRACK',
    missionName: 'ROUTE STABILITY SPRINT',
    objectiveText: 'THE TRACK COLLAPSES BEHIND YOU. DO NOT SLOW DOWN.',
    storyIntro: {
      title: 'COLLAPSING TRACK: STRUCTURAL FAILURE',
      locationName: 'CRITICAL SECTOR // INSTABILITY HORIZON',
      missionName: 'ROUTE STABILITY SPRINT',
      objectiveText: 'TRACK IS FAILING. MAINTAIN FORWARD MOMENTUM.',
      loreSnippet: 'Energy bridges flicker and structural beams tear loose into space. The route collapses behind the racers.',
      scenes: [
        {
          id: 'ct_scene_1',
          name: 'Track Segments Tearing and Falling',
          durationSec: 3.3,
          cameraStartOffset: [0, 85, -190],
          cameraEndOffset: [0, 35, -80],
          lookAtStartOffset: [0, -10, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 84,
          fovEnd: 62,
          transmissions: [
            {
              id: 't_ct_1',
              sender: 'MONITORING AI',
              text: 'ROUTE STABILITY: CRITICAL. 70% STRUCTURAL DISSOLUTION INBOUND.',
              timeSec: 0.4,
              type: 'WARNING',
              callsign: 'FAIL-SAFE',
            },
          ],
        },
        {
          id: 'ct_scene_2',
          name: 'Last Stable Starting Platform',
          durationSec: 2.5,
          cameraStartOffset: [-28, 16, -38],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 56,
          transmissions: [
            {
              id: 't_ct_2',
              sender: 'RACE DIRECTOR',
              text: 'ONCE YOU CROSS THE GATE, THE ROAD VANISHES BEHIND YOU. ACCELERATE.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'DIRECTOR',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 30,
      orbitHeight: 11,
      fov: 63,
      shake: 0.45,
    },
    environmentReveal: {
      title: 'FAILING MAGNETIC SUPERSTRUCTURE',
      subtitle: 'STRUCTURAL LIFE: 110 SECONDS // COLLAPSE SENSORS HOT',
      landmarkType: 'SHATTERED_BRIDGE_SECTION',
    },
    playerReveal: {
      type: 'UNDERNEATH_FLYBY',
      durationSec: 2.0,
      thrusterIntensity: 1.8,
      tagline: 'EMERGENCY OVERDRIVE PRIMED // RECOVERY SYSTEM ACTIVE',
    },
    startingLocation: {
      name: 'DAMAGED TEMPORARY STARTING PLATFORM',
      description: 'Vibrating energy deck holding together on auxiliary capacitor power.',
      startGridT: 0.0,
      landmarkMeshType: 'FAILING_ENERGY_PAD',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 13,
      colSpacing: 7,
      racerEntranceSpeed: 34,
    },
    countdownStyle: 'COLLAPSE_WARNING',
    countdownEffects: {
      primaryColor: '#ff2255',
      secondaryColor: '#ffaa00',
      soundType: 'STRUCTURAL_GROAN',
      glitchIntensity: 0.7,
      sublabel: 'ROUTE INTEGRITY CRITICAL // FULL THROTTLE MANDATORY',
    },
    launchAnimation: {
      fovPunch: 86,
      boostDuration: 1.2,
      gateReaction: 'DISSIPATE',
      launchSpeed: 64,
    },
    firstHazard: {
      name: 'DETACHING ROADWAY PLATE',
      warningText: 'TRACK CHUNK FREE-FALLING // LEAP UPPER APEX',
      leadTimeSec: 2.0,
      color: '#ff2255',
    },
    openingCinematic: {
      totalDurationSec: 8.3,
      skipAvailableAtSec: 0.8,
    },
  },

  // 14 — RING RUNNER
  RING_RUNNER: {
    modeId: 'RING_RUNNER',
    variationName: 'EQUATORIAL MEGACYCLE',
    locationName: 'PLANETARY RING GAUNTLET // ALTITUDE 40,000KM',
    missionName: 'PLANETARY CIRCUMFERENCE CIRCUIT',
    objectiveText: 'RACE ALONG THE GIGANTIC ORBITAL RING SURROUNDING THE PLANET.',
    storyIntro: {
      title: 'RING RUNNER: CIRCUMFERENCE OF A WORLD',
      locationName: 'EQUATORIAL ORBITAL RING // WORLD PERIMETER',
      missionName: 'CIRCUMFERENCE SPRINT',
      objectiveText: 'NAVIGATE PLANETARY RINGWAY. HIT ALL BEACON GATES.',
      loreSnippet: 'A colossal orbital megastructure encircles the entire blue gas giant like a shining metallic halo.',
      scenes: [
        {
          id: 'rr_scene_1',
          name: 'Enormous Orbital Ring Zoom from Far Orbit',
          durationSec: 3.5,
          cameraStartOffset: [0, 220, -320],
          cameraEndOffset: [0, 50, -90],
          lookAtStartOffset: [0, -60, 50],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 88,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_rr_1',
              sender: 'ORBITAL RING CONTROL',
              text: 'SYNCHRONIZING WITH PLANETARY ROTATION. 128,000 KILOMETERS OF TRACK.',
              timeSec: 0.4,
              type: 'CONTROL',
              callsign: 'RING-AI',
            },
          ],
        },
        {
          id: 'rr_scene_2',
          name: 'Thousands of Ring Lights & Gantry Beacons',
          durationSec: 2.5,
          cameraStartOffset: [-35, 18, -40],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 25],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_rr_2',
              sender: 'CHAMPIONSHIP COMMISSION',
              text: 'THE HALO CIRCUIT IS ACTIVE. SYNCHRONIZED BEACONS GUIDE THE LINE.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'COMMISSION',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 12,
      fov: 62,
      shake: 0.15,
    },
    environmentReveal: {
      title: 'EQUATORIAL PLANETARY MEGA-RING',
      subtitle: 'ORBITAL SPEED: 7.8 KM/S // PERPETUAL SUNSET PROFILE',
      landmarkType: 'ORBITAL_RING_BEACON_CLUSTER',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 2.0,
      thrusterIntensity: 1.6,
      tagline: 'CENTRIFUGAL LOCK ESTABLISHED',
    },
    startingLocation: {
      name: 'GIGANTIC ORBITAL RING SURROUNDING PLANET',
      description: 'Vast crystalline bridge hovering in geosynchronous orbital equilibrium.',
      startGridT: 0.0,
      landmarkMeshType: 'RING_STATION_TOWER',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 38,
    },
    countdownStyle: 'ORBITAL_RING',
    countdownEffects: {
      primaryColor: '#00f0ff',
      secondaryColor: '#ffffff',
      soundType: 'RING_CHIME',
      glitchIntensity: 0.15,
      sublabel: 'PLANETARY BEACONS PULSING // SEQUENTIAL ACCEL',
    },
    launchAnimation: {
      fovPunch: 84,
      boostDuration: 1.1,
      gateReaction: 'OPEN',
      launchSpeed: 62,
    },
    firstHazard: {
      name: 'EQUATORIAL MOORING PYLON',
      warningText: 'TETHER TOWER APEX // NARROW MARGIN THROUGH CENTER',
      leadTimeSec: 2.5,
      color: '#00f0ff',
    },
    openingCinematic: {
      totalDurationSec: 8.5,
      skipAvailableAtSec: 0.8,
    },
  },

  // 15 — HYPERSPACE SPRINT
  HYPERSPACE_SPRINT: {
    modeId: 'HYPERSPACE_SPRINT',
    variationName: 'TACHYON ACCELERATOR SPRINT',
    locationName: 'HYPER-INDUCTION CHAMBER // SECTOR WARP-1',
    missionName: 'RELATIVISTIC SPEED ACCELERATION',
    objectiveText: 'BUILD ENERGY. ENGAGE SEQUENTIAL GATES. BREACH HYPERSPACE.',
    storyIntro: {
      title: 'HYPERSPACE SPRINT: TRANSLUMINAL INJECTION',
      locationName: 'ACCELERATION CHAMBER // WARP INDUCTION',
      missionName: 'HYPERSPACE SPRINT',
      objectiveText: 'CHARGE WARP DRIVE. POWER THROUGH SEQUENTIAL GATES.',
      loreSnippet: 'Entering a gargantuan vacuum acceleration tube. Sequential magnetic gates pulse with kinetic energy.',
      scenes: [
        {
          id: 'hs_scene_1',
          name: 'Chamber Powering Up & Sequential Energy Rings',
          durationSec: 3.2,
          cameraStartOffset: [0, 50, -180],
          cameraEndOffset: [0, 20, -70],
          lookAtStartOffset: [0, 0, 60],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 80,
          fovEnd: 58,
          transmissions: [
            {
              id: 't_hs_1',
              sender: 'INDUCTION ENGINE AI',
              text: 'CHAMBER 7 POWERING UP. CAPACITOR BANKS DUMPING INTO INDUCTION COILS.',
              timeSec: 0.4,
              type: 'MISSION',
              callsign: 'WARP-AI',
            },
          ],
        },
        {
          id: 'hs_scene_2',
          name: 'Relativistic Speed Distortion',
          durationSec: 2.5,
          cameraStartOffset: [-25, 12, -35],
          cameraEndOffset: [0, 6, -14],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 54,
          transmissions: [
            {
              id: 't_hs_2',
              sender: 'FLIGHT CONTROLLER',
              text: 'GATES 1 THROUGH 10 ARMED. MAXIMUM REACTION TIME REQUIRED.',
              timeSec: 0.2,
              type: 'CONTROL',
              callsign: 'DISPATCH',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 28,
      orbitHeight: 9,
      fov: 62,
      shake: 0.2,
    },
    environmentReveal: {
      title: 'HYPERSPACE ACCELERATION TUBE',
      subtitle: 'VACUUM EVACUATION: 99.9% // TACHYON DRIVE CHARGED',
      landmarkType: 'HYPERSPACE_CHAMBER_TUBE',
    },
    playerReveal: {
      type: 'AFTERBURNER_IGNITE',
      durationSec: 1.9,
      thrusterIntensity: 2.0,
      tagline: 'HYPER-BOOST CAPACITORS 100% PRIMED',
    },
    startingLocation: {
      name: 'HYPERSPACE ACCELERATION CHAMBER',
      description: 'Hexagonal particle accelerator tube lined with blue superconduction rings.',
      startGridT: 0.0,
      landmarkMeshType: 'WARP_INDUCTION_GATE',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 12,
      colSpacing: 6,
      racerEntranceSpeed: 42,
    },
    countdownStyle: 'WARP_STRETCH',
    countdownEffects: {
      primaryColor: '#00f0ff',
      secondaryColor: '#ffffff',
      soundType: 'WARP_BUILD',
      glitchIntensity: 0.3,
      sublabel: 'RELATIVISTIC DILATION // ENGAGE WARP',
    },
    launchAnimation: {
      fovPunch: 92,
      boostDuration: 1.4,
      gateReaction: 'FLASH',
      launchSpeed: 75,
    },
    firstHazard: {
      name: 'MAGNETIC GATE APERTURE',
      warningText: 'NARROW INJECTION CHOKE POINT // ALIGN TO PERFECT CENTER',
      leadTimeSec: 2.0,
      color: '#00f0ff',
    },
    openingCinematic: {
      totalDurationSec: 8.1,
      skipAvailableAtSec: 0.7,
    },
  },

  // 16 — RIVAL DUEL
  RIVAL_DUEL: {
    modeId: 'RIVAL_DUEL',
    variationName: 'NEMESIS FACE-OFF',
    locationName: 'PROVING GROUNDS DELTA // 1V1 DUEL ARENA',
    missionName: 'HEAD-TO-HEAD NEMESIS DUEL',
    objectiveText: 'DEFEAT YOUR RIVAL ZER0 IN A DIRECT 1V1 SHOWDOWN.',
    storyIntro: {
      title: 'RIVAL DUEL: CLASH OF TITANS',
      locationName: 'SOLITARY ARENA // SECTOR DUEL',
      missionName: 'HEAD-TO-HEAD DUEL',
      objectiveText: 'OUTRACE AND OUTFIGHT YOUR RIVAL ZER0. WINNER TAKES ALL.',
      loreSnippet: 'No pack. No crowd. Only two elite pilots facing each other on a high-speed duel platform.',
      scenes: [
        {
          id: 'rd_scene_1',
          name: 'Rival Ship Enters from Opposite Vector',
          durationSec: 3.2,
          cameraStartOffset: [50, 40, -120],
          cameraEndOffset: [-10, 18, -50],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 76,
          fovEnd: 58,
          transmissions: [
            {
              id: 't_rd_1',
              sender: 'RIVAL ZER0',
              text: 'YOU THOUGHT YOU WERE THE ONLY APEX RACER IN THIS QUADRANT? PROVE IT.',
              timeSec: 0.4,
              type: 'RIVAL',
              callsign: 'ZER0',
            },
          ],
        },
        {
          id: 'rd_scene_2',
          name: 'Face-off Camera Sweeps Between Both Ships',
          durationSec: 2.6,
          cameraStartOffset: [0, 10, -25],
          cameraEndOffset: [0, 5, -12],
          lookAtStartOffset: [0, 0, 10],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 66,
          fovEnd: 52,
          transmissions: [
            {
              id: 't_rd_2',
              sender: 'DUEL ARBITER',
              text: 'NO QUARTER. NO EXCUSES. TWO SHIPS ENTER, ONE CHAMPION EMERGES.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'ARBITER',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 24,
      orbitHeight: 8,
      fov: 58,
      shake: 0.2,
    },
    environmentReveal: {
      title: 'NEUTRAL PROVING PLATFORM',
      subtitle: 'CONFRONTATION MODE: 1V1 // MISSILES AND RAMMING AUTHORIZED',
      landmarkType: 'DUEL_ARENA_PLATFORM',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 2.0,
      thrusterIntensity: 1.8,
      tagline: 'RIVAL COMBAT ENGINES LOCKED // REVS MATCHED',
    },
    startingLocation: {
      name: 'DEDICATED DUEL PLATFORM',
      description: 'Elevated two-lane platform surrounded by holographic confrontation displays.',
      startGridT: 0.0,
      landmarkMeshType: 'DUEL_FACEOFF_GATE',
    },
    gridFormation: {
      type: 'SIDE_BY_SIDE',
      rowSpacing: 0,
      colSpacing: 10,
      racerEntranceSpeed: 34,
    },
    countdownStyle: 'RIVAL_DUEL',
    countdownEffects: {
      primaryColor: '#ff0055',
      secondaryColor: '#00f0ff',
      soundType: 'DUEL_GONG',
      glitchIntensity: 0.3,
      sublabel: 'RIVAL LOCKED EYE-TO-EYE // LAUNCH TOGETHER',
    },
    launchAnimation: {
      fovPunch: 86,
      boostDuration: 1.2,
      gateReaction: 'OPEN',
      launchSpeed: 65,
    },
    firstHazard: {
      name: 'RIVAL DRIFT CONTEST APEX',
      warningText: 'ZER0 WILL ATTEMPT TO PIN YOU TO THE RAILS AT TURN 1',
      leadTimeSec: 2.2,
      color: '#ff0055',
    },
    openingCinematic: {
      totalDurationSec: 8.2,
      skipAvailableAtSec: 0.8,
    },
  },

  // 17 — RELAY RACE
  RELAY_RACE: {
    modeId: 'RELAY_RACE',
    variationName: 'SQUADRON BATON PASS',
    locationName: 'PADDOCK COLISEUM // TEAM PITS',
    missionName: 'MULTI-TEAM RELAY EXPEDITION',
    objectiveText: 'TAKE THE RELAY SIGNAL. RUN SECTOR 1. HAND OFF THE LEAD.',
    storyIntro: {
      title: 'RELAY RACE: SQUADRON SYNCHRONY',
      locationName: 'RELAY ARENA PADDOCK // SECTOR TEAMS',
      missionName: 'TEAM RELAY SPRINT',
      objectiveText: 'TAKE RELAY SIGNAL. RUN FIRST LEG. CRUSH RIVAL SQUADS.',
      loreSnippet: 'Four professional racing teams line up in the paddock. Each team vehicle waits for the handoff signal.',
      scenes: [
        {
          id: 'rr_scene_1',
          name: 'Camera Travels Through Teams A, B, C, D',
          durationSec: 3.3,
          cameraStartOffset: [-130, 80, -180],
          cameraEndOffset: [20, 35, -75],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 82,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_rel_1',
              sender: 'TEAM PIT BOSS',
              text: 'TEAMS ALPHA, BETA, GAMMA, DELTA CONFIRMED ON PIT APRON.',
              timeSec: 0.4,
              type: 'CONTROL',
              callsign: 'PIT-BOSS',
            },
          ],
        },
        {
          id: 'rr_scene_2',
          name: 'Player Receives Relay Signal',
          durationSec: 2.5,
          cameraStartOffset: [-28, 16, -38],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 68,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_rel_2',
              sender: 'TACTICAL SPOTTER',
              text: 'LEAD BATON TRANSMITTED TO YOUR FLIGHT COMPUTER. BRING HOME LAP 1.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'SPOTTER',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 30,
      orbitHeight: 11,
      fov: 62,
      shake: 0.2,
    },
    environmentReveal: {
      title: 'PADDOCK RELAY COLISEUM',
      subtitle: '4 TEAMS REGISTERED // SECTOR BATON ACTIVE',
      landmarkType: 'RELAY_PADDOCK_STATION',
    },
    playerReveal: {
      type: 'TUNNEL_EXIT',
      durationSec: 2.0,
      thrusterIntensity: 1.6,
      tagline: 'TEAM ALPHA LEAD CRAFT ROLLING TO MARKS',
    },
    startingLocation: {
      name: 'MASSIVE RELAY LAUNCH ARENA',
      description: 'Four multi-lane team bays equipped with overhead electronic telemetry bars.',
      startGridT: 0.0,
      landmarkMeshType: 'RELAY_ARENA_GANTRY',
    },
    gridFormation: {
      type: 'WEDGE',
      rowSpacing: 13,
      colSpacing: 8,
      racerEntranceSpeed: 32,
    },
    countdownStyle: 'RELAY_PADDOCK',
    countdownEffects: {
      primaryColor: '#39ff14',
      secondaryColor: '#00f0ff',
      soundType: 'STADIUM_HORN',
      glitchIntensity: 0.2,
      sublabel: 'TEAM PADDOCK GATES RAISING // LEG 1 COMMENCES',
    },
    launchAnimation: {
      fovPunch: 84,
      boostDuration: 1.1,
      gateReaction: 'OPEN',
      launchSpeed: 60,
    },
    firstHazard: {
      name: 'PADDOCK EXIT MERGE POINT',
      warningText: 'FOUR LANES BOTTLENECK INTO SINGLE APEX // JOCKEY FOR POSITION',
      leadTimeSec: 2.3,
      color: '#39ff14',
    },
    openingCinematic: {
      totalDurationSec: 8.2,
      skipAvailableAtSec: 0.8,
    },
  },

  // 18 — SURVIVAL ELIMINATION
  SURVIVAL_ELIMINATION: {
    modeId: 'SURVIVAL_ELIMINATION',
    variationName: 'COLOSSEUM EXTINCTION LAP',
    locationName: 'GLADIATOR ORBITAL ARENA // SECTOR APOCALYPSE',
    missionName: 'SURVIVAL ELIMINATION GAUNTLET',
    objectiveText: 'EVERY 30 SECONDS, THE LAST-PLACE CRAFT IS ELIMINATED.',
    storyIntro: {
      title: 'SURVIVAL ELIMINATION: THE EXTINCTION ARENA',
      locationName: 'ELIMINATION DOME // ORBITAL COLOSSEUM',
      missionName: 'SURVIVAL ELIMINATION',
      objectiveText: 'AVOID LAST PLACE. LAST CRAFT STANDING WINS.',
      loreSnippet: 'A vast orbital elimination arena surrounded by stadium laser walls. Warning indicators flash around the perimeter.',
      scenes: [
        {
          id: 'se_scene_1',
          name: 'Arena Overview & Competitor Sweep',
          durationSec: 3.3,
          cameraStartOffset: [0, 130, -210],
          cameraEndOffset: [0, 45, -85],
          lookAtStartOffset: [0, -20, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 85,
          fovEnd: 62,
          transmissions: [
            {
              id: 't_se_1',
              sender: 'ARENA MARSHAL',
              text: 'ATTENTION SURVIVORS: LAST PLACE VESSEL PURGED EVERY 30 SECONDS.',
              timeSec: 0.4,
              type: 'WARNING',
              callsign: 'ARENA-AI',
            },
          ],
        },
        {
          id: 'se_scene_2',
          name: 'Arena Gate Opens & Racers Accelerate',
          durationSec: 2.5,
          cameraStartOffset: [-32, 18, -40],
          cameraEndOffset: [0, 8, -16],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 70,
          fovEnd: 56,
          transmissions: [
            {
              id: 't_se_2',
              sender: 'ARENA MARSHAL',
              text: 'NO POINTS FOR SECOND. RUN FOR YOUR LIFE AND CLIMB THE RANKS.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'ARENA-AI',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 12,
      fov: 64,
      shake: 0.35,
    },
    environmentReveal: {
      title: 'EXTINCTION COLOSSEUM ARENA',
      subtitle: '6 COMPETITORS // PURGE TIMER ARMED',
      landmarkType: 'COLOSSEUM_ARENA_DOME',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 2.1,
      thrusterIntensity: 1.8,
      tagline: 'SURVIVAL SENSORS ACTIVE // OVERTAKE MARGIN PRIMED',
    },
    startingLocation: {
      name: 'GIANT ELIMINATION ARENA',
      description: 'Massive circular gladiator launch bay surrounded by spectator holo-screens.',
      startGridT: 0.0,
      landmarkMeshType: 'ELIMINATION_GATE_ARCH',
    },
    gridFormation: {
      type: 'ARENA_RING',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 35,
    },
    countdownStyle: 'SURVIVAL_ARENA',
    countdownEffects: {
      primaryColor: '#ff0033',
      secondaryColor: '#ff00ff',
      soundType: 'ARENA_BUZZER',
      glitchIntensity: 0.5,
      sublabel: 'PURGE COUNTDOWN LIVE // SURVIVE OR BE VAPORIZED',
    },
    launchAnimation: {
      fovPunch: 88,
      boostDuration: 1.2,
      gateReaction: 'OPEN',
      launchSpeed: 64,
    },
    firstHazard: {
      name: 'ARENA LASER SLICER',
      warningText: 'HORIZONTAL LASER BARRIER SWEEPING LAP 1 CORRIDOR',
      leadTimeSec: 2.2,
      color: '#ff0033',
    },
    openingCinematic: {
      totalDurationSec: 8.3,
      skipAvailableAtSec: 0.8,
    },
  },

  // 19 — COSMIC TREASURE HUNT
  COSMIC_TREASURE_HUNT: {
    modeId: 'COSMIC_TREASURE_HUNT',
    variationName: 'FORBIDDEN RUNIC GATEWAY',
    locationName: 'ANCIENT PRECURSOR CITADEL // VEIL REGION',
    missionName: 'RELIC SIGNAL INFILTRATION',
    objectiveText: 'DECIPHER THE ANCIENT ARTIFACT BEACONS. SECURE THE RELIC.',
    storyIntro: {
      title: 'COSMIC TREASURE HUNT: SECRETS OF THE BUILDERS',
      locationName: 'ANCIENT CITADEL // MEGASYMMETRIC CORE',
      missionName: 'RELIC SIGNAL HUNT',
      objectiveText: 'COLLECT ANCIENT RUNIC SEEDS. BEAT RIVALS TO THE VAULT.',
      loreSnippet: 'An incomprehensible megastructure of unknown alien origin illuminates with glowing golden symbols.',
      scenes: [
        {
          id: 'cth_scene_1',
          name: 'Ancient Megastructure & Glowing Glyphs',
          durationSec: 3.4,
          cameraStartOffset: [-140, 110, -210],
          cameraEndOffset: [10, 40, -90],
          lookAtStartOffset: [0, 0, 40],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 84,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_cth_1',
              sender: 'ARCHEOLOGICAL BEACON',
              text: 'PRECURSOR VAULT DOOR ACTIVATED. GOLDEN RESONANCE BEACONS DETECTED.',
              timeSec: 0.4,
              type: 'ANOMALY',
              callsign: 'ARCH-01',
            },
          ],
        },
        {
          id: 'cth_scene_2',
          name: 'Ancient Energy Gates Awakening',
          durationSec: 2.6,
          cameraStartOffset: [30, 18, -40],
          cameraEndOffset: [0, 7, -15],
          lookAtStartOffset: [0, 0, 20],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 70,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_cth_2',
              sender: 'EXPEDITION COMMAND',
              text: 'THE ANCIENT ROUTE HAS OPENED. LOCATE THE TREASURE CORES.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'EXPEDITION',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 32,
      orbitHeight: 11,
      fov: 62,
      shake: 0.2,
    },
    environmentReveal: {
      title: 'PRECURSOR ALIEN CITADEL',
      subtitle: 'AGE: 2.4 BILLION YEARS // UNKNOWN ENERGY SIGNATURE',
      landmarkType: 'ANCIENT_MEGASTRUCTURE_PYLON',
    },
    playerReveal: {
      type: 'CIRCULAR_SWEEP',
      durationSec: 2.0,
      thrusterIntensity: 1.6,
      tagline: 'ARTIFACT SENSORS TUNED TO PRECURSOR FREQUENCY',
    },
    startingLocation: {
      name: 'OUTSIDE ANCIENT UNEXPLORED MEGASTRUCTURE',
      description: 'Luminous alien stones forming a zero-gravity entrance terrace.',
      startGridT: 0.0,
      landmarkMeshType: 'ANCIENT_GLYPH_PORTAL',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 34,
    },
    countdownStyle: 'ANCIENT_GLYPH',
    countdownEffects: {
      primaryColor: '#ffaa00',
      secondaryColor: '#39ff14',
      soundType: 'MYSTIC_CHIME',
      glitchIntensity: 0.25,
      sublabel: 'PRECURSOR GLYPHS ALIGNING // UNLOCK THE TREASURE',
    },
    launchAnimation: {
      fovPunch: 84,
      boostDuration: 1.1,
      gateReaction: 'DISSIPATE',
      launchSpeed: 62,
    },
    firstHazard: {
      name: 'ANCIENT PULSE TRAP',
      warningText: 'GOLDEN HARMONIC PULSE FIELD ACROSS FIRST APEX',
      leadTimeSec: 2.3,
      color: '#ffaa00',
    },
    openingCinematic: {
      totalDurationSec: 8.4,
      skipAvailableAtSec: 0.8,
    },
  },

  // 20 — VOID CHAMPIONSHIP (IMPORTANT: NO BLACK HOLE MECHANICS)
  VOID_CHAMPIONSHIP: {
    modeId: 'VOID_CHAMPIONSHIP',
    variationName: 'THE GRAND GALACTIC FINALE',
    locationName: 'VOID-RIDER APEX STADIUM // CENTRAL GALAXY',
    missionName: 'CHAMPIONSHIP FINAL CIRCUIT',
    objectiveText: 'THE PINNACLE OF SPEED. CLAIM THE GALACTIC CUP.',
    storyIntro: {
      title: 'VOID CHAMPIONSHIP: THE ULTIMATE PODIUM',
      locationName: 'GALACTIC CHAMPIONSHIP STADIUM // HIGH ORBIT',
      missionName: 'VOID CHAMPIONSHIP FINAL',
      objectiveText: 'DEFEAT ALL CHAMPION RIVALS. CLAIM THE VOID-RIDER TROPHY.',
      loreSnippet: 'The greatest spectacle in the galaxy. Millions of spectators and flashlights illuminate the grand circuit.',
      scenes: [
        {
          id: 'vc_scene_1',
          name: 'Grand Panoramic Galaxy Circuit Reveal',
          durationSec: 3.6,
          cameraStartOffset: [0, 240, -350],
          cameraEndOffset: [0, 60, -110],
          lookAtStartOffset: [0, -60, 60],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 88,
          fovEnd: 60,
          transmissions: [
            {
              id: 't_vc_1',
              sender: 'GALACTIC RACING FEDERATION',
              text: 'WELCOME CITIZENS TO THE VOID CHAMPIONSHIP FINAL CIRCUIT.',
              timeSec: 0.4,
              type: 'CONTROL',
              callsign: 'FED-PRESIDENT',
            },
          ],
        },
        {
          id: 'vc_scene_2',
          name: 'Championship Fleet & Massive Arena Holo-Banners',
          durationSec: 2.6,
          cameraStartOffset: [-40, 22, -45],
          cameraEndOffset: [0, 8, -17],
          lookAtStartOffset: [0, 0, 30],
          lookAtEndOffset: [0, 0, 0],
          fovStart: 70,
          fovEnd: 55,
          transmissions: [
            {
              id: 't_vc_2',
              sender: 'HEAD MARSHAL',
              text: 'TOP PILOTS OF THE UNIVERSE HAVE ASSEMBLED. GO FOR GLORY.',
              timeSec: 0.2,
              type: 'MISSION',
              callsign: 'MARSHAL',
            },
          ],
        },
      ],
    },
    introCamera: {
      startDistance: 34,
      orbitHeight: 12,
      fov: 62,
      shake: 0.2,
    },
    environmentReveal: {
      title: 'VOID CHAMPIONSHIP STADIUM',
      subtitle: '20 SECTORS CONVERGE // 500 MILLION BROADCAST VIEWERS',
      landmarkType: 'CHAMPIONSHIP_STADIUM_ARCHES',
    },
    playerReveal: {
      type: 'HANGAR_LAUNCH',
      durationSec: 2.2,
      thrusterIntensity: 1.9,
      tagline: 'CHAMPIONSHIP SPEC ENGINES AT FULL REVS',
    },
    startingLocation: {
      name: 'MASSIVE CHAMPIONSHIP STADIUM OVERLOOKING NETWORK',
      description: 'Grand galactic stadium with golden grandstands and celebratory laser beams.',
      startGridT: 0.0,
      landmarkMeshType: 'CHAMPIONSHIP_STADIUM_PODIUM',
    },
    gridFormation: {
      type: 'STAGGERED_DUAL',
      rowSpacing: 14,
      colSpacing: 8,
      racerEntranceSpeed: 38,
    },
    countdownStyle: 'CHAMPIONSHIP_STADIUM',
    countdownEffects: {
      primaryColor: '#ffaa00',
      secondaryColor: '#00f0ff',
      soundType: 'STADIUM_CHEER',
      glitchIntensity: 0.1,
      sublabel: 'VOID CHAMPIONSHIP // FINAL CIRCUIT GREEN LIGHT',
    },
    launchAnimation: {
      fovPunch: 88,
      boostDuration: 1.3,
      gateReaction: 'FLASH',
      launchSpeed: 68,
    },
    firstHazard: {
      name: 'CHAMPIONSHIP FIREWORKS CANNON',
      warningText: 'SPECTACLE PYROTECHNIC SALVO BURSTING OVERHEAD',
      leadTimeSec: 2.4,
      color: '#ffaa00',
    },
    openingCinematic: {
      totalDurationSec: 8.6,
      skipAvailableAtSec: 0.8,
    },
  },
};

/**
 * Helper to retrieve or clone the mode introduction config.
 */
export function getModeIntroConfig(mode: GameMode): ModeIntroConfig {
  if (ALL_MODE_INTRO_CONFIGS[mode]) return ALL_MODE_INTRO_CONFIGS[mode];
  switch (mode) {
    case 'STANDARD':
    case 'GRAND_PRIX':
      return ALL_MODE_INTRO_CONFIGS.NEON_CIRCUIT;
    case 'TIME_TRIAL':
      return ALL_MODE_INTRO_CONFIGS.QUANTUM_TIME_TRIAL;
    case 'SURVIVAL':
    case 'ENDURANCE':
      return ALL_MODE_INTRO_CONFIGS.DEBRIS_SURVIVAL;
    case 'ELIMINATION':
    case 'ELIMINATOR':
      return ALL_MODE_INTRO_CONFIGS.SURVIVAL_ELIMINATION;
    case 'DUEL':
    case 'CHALLENGE':
      return ALL_MODE_INTRO_CONFIGS.RIVAL_DUEL;
    case 'FREE_RIDE':
      return ALL_MODE_INTRO_CONFIGS.GRAVITY_FREE;
    default:
      return ALL_MODE_INTRO_CONFIGS.SINGULARITY_RUN;
  }
}
